name = "Kven Finnish"
version = "0.1.0"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fkv"

[windows]
system_product_code = "8F1DDBFF-F876-4E04-908F-03F26E9A2F9D"
msoffice_product_code = "DDCCAFC4-0981-482E-8DD9-AFC5A75CCC7F"
