spellername = "Kven Finnish"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Kven Finnish spellchecker"
fkv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Kven Finnish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
fkv = "TRANSLATE: A spellchecker for Kven Finnish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fkv"

[windows]
system_product_code = "{DFAA5916-FCDD-4141-AA45-AB091BFEFD70}_is1"
legacy_product_codes = [
    { value = "8F1DDBFF-F876-4E04-908F-03F26E9A2F9D", kind = "nsis" },
    { value = "DDCCAFC4-0981-482E-8DD9-AFC5A75CCC7F", kind = "nsis" },
]
