|                                   |                            |
|-----------------------------------|----------------------------|
| +A+Sg+Ill                         | +A+Sg+Ill                  |
| viimi+A+Sg+Ill                    | viimi+A+Sg+Ill             |
| turkkiisi+A+Sg+Ill                | turkkiisi+A+Sg+Ill         |
| ensi+A+Sg+Ill                     | ensi+A+Sg+Ill              |
| vaiti+A+Sg+Ill                    | vaiti+A+Sg+Ill             |
| irti+A+Sg+Ill                     | irti+A+Sg+Ill              |
| fonologinen+A+Sg+Ill              | fonologinen+A+Sg+Ill       |
| paras+A+Sg+Ill                    | paras+A+Sg+Ill             |
| ohut+A+Sg+Ill                     | ohut+A+Sg+Ill              |
| ehyt+A+Sg+Ill                     | ehyt+A+Sg+Ill              |
| lyhyt+A+Sg+Ill                    | lyhyt+A+Sg+Ill             |
| ohu+A+Sg+Ill                      | ohu+A+Sg+Ill               |
| pikku+A+Sg+Ill                    | pikku+A+Sg+Ill             |
| lyhy+A+Sg+Ill                     | lyhy+A+Sg+Ill              |
| paha+A+Sg+Ill                     | pahhaan                    |
| laiha+A+Sg+Ill                    | laihhaan                   |
| turha+A+Sg+Ill                    | turhhaan                   |
| lauha+A+Sg+Ill                    | lauhhaan                   |
| laaja+A+Sg+Ill                    | laajhaan                   |
| harmaaja+A+Sg+Ill                 | harmaajhaan                |
| hoppeeharmaaja+A+Sg+Ill           | hoppeeharmaajhaan          |
| taaja+A+Sg+Ill                    | taajhaan                   |
| hurja+A+Sg+Ill                    | hurjhaan                   |
| kurja+A+Sg+Ill                    | kurjhaan                   |
| luja+A+Sg+Ill                     | lujhaan                    |
| raaka+A+Sg+Ill                    | raakhaan                   |
| liika+A+Sg+Ill                    | liikhaan                   |
| ilakka+A+Sg+Ill                   | ilakkhaan                  |
| hoikka+A+Sg+Ill                   | hoikkhaan                  |
| vankka+A+Sg+Ill                   | vankkhaan                  |
| tarkka+A+Sg+Ill                   | tarkkhaan                  |
| tiukka+A+Sg+Ill                   | tiukkhaan                  |
| soukka+A+Sg+Ill                   | soukkhaan                  |
| arka+A+Sg+Ill                     | arkhaan                    |
| pimmeenarka+A+Sg+Ill              | pimmeenarkhaan             |
| laiska+A+Sg+Ill                   | laiskhaan                  |
| hauska+A+Sg+Ill                   | hauskhaan                  |
| nuuka+A+Sg+Ill                    | nuukhaan                   |
| hankala+A+Sg+Ill                  | hankalhaan                 |
| kamala+A+Sg+Ill                   | kamalhaan                  |
| matala+A+Sg+Ill                   | matalhaan                  |
| kavala+A+Sg+Ill                   | kavalhaan                  |
| happela+A+Sg+Ill                  | happelhaan                 |
| siila+A+Sg+Ill                    | siilhaan                   |
| sula+A+Sg+Ill                     | sulhaan                    |
| veđenpillaama+A+Sg+Ill            | veđenpillaamhaan           |
| lama+A+Sg+Ill                     | lamhaan                    |
| hapan+A+Sg+Ill                    | happamhaan                 |
| ulosantama+A+Sg+Ill               | ulosantamhaan              |
| vasen+A+Sg+Ill                    | vasemhaan                  |
| parhain+A+Sg+Ill                  | parhaimhaan                |
| kumma+A+Sg+Ill                    | kummhaan                   |
| tumma+A+Sg+Ill                    | tummhaan                   |
| oma+A+Sg+Ill                      | omhaan                     |
| soma+A+Sg+Ill                     | somhaan                    |
| alaston+A+Sg+Ill                  | alastomhaan                |
| rauhaton+A+Sg+Ill                 | rauhattomhaan              |
| viaton+A+Sg+Ill                   | viattomhaan                |
| rajaton+A+Sg+Ill                  | rajattomhaan               |
| pohjaton+A+Sg+Ill                 | pohjattomhaan              |
| vijaton+A+Sg+Ill                  | vijattomhaan               |
| jumalaton+A+Sg+Ill                | jumalattomhaan             |
| vallaton+A+Sg+Ill                 | vallattomhaan              |
| saamaton+A+Sg+Ill                 | saamattomhaan              |
| mittaamaton+A+Sg+Ill              | mittaamattomhaan           |
| maksamaton+A+Sg+Ill               | maksamattomhaan            |
| perhäänantamaton+A+Sg+Ill         | perhäänantamattomhaan      |
| paistamaton+A+Sg+Ill              | paistamattomhaan           |
| luottamaton+A+Sg+Ill              | luottamattomhaan           |
| ajattelematon+A+Sg+Ill            | ajattelemattomhaan         |
| vaihettelematon+A+Sg+Ill          | vaihettelemattomhaan       |
| valettelematon+A+Sg+Ill           | valettelemattomhaan        |
| tottelematon+A+Sg+Ill             | tottelemattomhaan          |
| olematon+A+Sg+Ill                 | olemattomhaan              |
| tuntematon+A+Sg+Ill               | tuntemattomhaan            |
| naimaton+A+Sg+Ill                 | naimattomhaan              |
| huolimaton+A+Sg+Ill               | huolimattomhaan            |
| oppimaton+A+Sg+Ill                | oppimattomhaan             |
| vaatimaton+A+Sg+Ill               | vaatimattomhaan            |
| uskomaton+A+Sg+Ill                | uskomattomhaan             |
| liikkumaton+A+Sg+Ill              | liikkumattomhaan           |
| taipumaton+A+Sg+Ill               | taipumattomhaan            |
| loppumaton+A+Sg+Ill               | loppumattomhaan            |
| muuttumaton+A+Sg+Ill              | muuttumattomhaan           |
| herraton+A+Sg+Ill                 | herrattomhaan              |
| luvaton+A+Sg+Ill                  | luvattomhaan               |
| toimeton+A+Sg+Ill                 | toimettomhaan              |
| onneton+A+Sg+Ill                  | onnettomhaan               |
| ruokoton+A+Sg+Ill                 | ruokottomhaan              |
| uskoton+A+Sg+Ill                  | uskottomhaan               |
| armoton+A+Sg+Ill                  | armottomhaan               |
| painoton+A+Sg+Ill                 | painottomhaan              |
| levoton+A+Sg+Ill                  | levottomhaan               |
| kelvoton+A+Sg+Ill                 | kelvottomhaan              |
| arvoton+A+Sg+Ill                  | arvottomhaan               |
| mahđoton+A+Sg+Ill                 | mahđottomhaan              |
| loputon+A+Sg+Ill                  | loputtomhaan               |
| suruton+A+Sg+Ill                  | suruttomhaan               |
| avuton+A+Sg+Ill                   | avuttomhaan                |
| mavuton+A+Sg+Ill                  | mavuttomhaan               |
| varma+A+Sg+Ill                    | varmhaan                   |
| epävarma+A+Sg+Ill                 | epävarmhaan                |
| ruma+A+Sg+Ill                     | rumhaan                    |
| kuuma+A+Sg+Ill                    | kuumhaan                   |
| ihana+A+Sg+Ill                    | ihanhaan                   |
| halpa+A+Sg+Ill                    | halphaan                   |
| ankara+A+Sg+Ill                   | ankarhaan                  |
| tieđonankara+A+Sg+Ill             | tieđonankarhaan            |
| ahkera+A+Sg+Ill                   | ahkerhaan                  |
| uuttera+A+Sg+Ill                  | uutterhaan                 |
| suora+A+Sg+Ill                    | suorhaan                   |
| pystösuora+A+Sg+Ill               | pystösuorhaan              |
| saura+A+Sg+Ill                    | saurhaan                   |
| kippura+A+Sg+Ill                  | kippurhaan                 |
| fasta+A+Sg+Ill                    | fasthaan                   |
| musta+A+Sg+Ill                    | musthaan                   |
| pikimusta+A+Sg+Ill                | pikimusthaan               |
| kirjaava+A+Sg+Ill                 | kirjaavhaan                |
| yhtheenhenkkaava+A+Sg+Ill         | yhtheenhenkkaavhaan        |
| seuraava+A+Sg+Ill                 | seuraavhaan                |
| mahtaava+A+Sg+Ill                 | mahtaavhaan                |
| loistaava+A+Sg+Ill                | loistaavhaan               |
| valttaava+A+Sg+Ill                | valttaavhaan               |
| virttaava+A+Sg+Ill                | virttaavhaan               |
| jouttaava+A+Sg+Ill                | jouttaavhaan               |
| lihava+A+Sg+Ill                   | lihavhaan                  |
| vakava+A+Sg+Ill                   | vakavhaan                  |
| mukava+A+Sg+Ill                   | mukavhaan                  |
| painava+A+Sg+Ill                  | painavhaan                 |
| herrattava+A+Sg+Ill               | herrattavhaan              |
| pulleeva+A+Sg+Ill                 | pulleevhaan                |
| tulleeva+A+Sg+Ill                 | tulleevhaan                |
| vahva+A+Sg+Ill                    | vahvhaan                   |
| soppiiva+A+Sg+Ill                 | soppiivhaan                |
| kiva+A+Sg+Ill                     | kivhaan                    |
| loiva+A+Sg+Ill                    | loivhaan                   |
| kuiva+A+Sg+Ill                    | kuivhaan                   |
| kova+A+Sg+Ill                     | kovhaan                    |
| harva+A+Sg+Ill                    | harvhaan                   |
| puolikassuuva+A+Sg+Ill            | puolikassuuvhaan           |
| leppääkassuuva+A+Sg+Ill           | leppääkassuuvhaan          |
| tunttuuva+A+Sg+Ill                | tunttuuvhaan               |
| puoli+A+Sg+Ill                    | puolheen                   |
| käsipuoli+A+Sg+Ill                | käsipuolheen               |
| silmäpuoli+A+Sg+Ill               | silmäpuolheen              |
| irtain+A+Sg+Ill                   | irtaimheen                 |
| pieni+A+Sg+Ill                    | pienheen                   |
| tyven+A+Sg+Ill                    | tyvenheen                  |
| tinatyven+A+Sg+Ill                | tinatyvenheen              |
| moni+A+Sg+Ill                     | monheen                    |
| umpi+A+Sg+Ill                     | umpheen                    |
| nuori+A+Sg+Ill                    | nuorheen                   |
| suuri+A+Sg+Ill                    | suurheen                   |
| vihanen+A+Sg+Ill                  | vihasheen                  |
| samanaikhanen+A+Sg+Ill            | samanaikhasheen            |
| uuđenaikhanen+A+Sg+Ill            | uuđenaikhasheen            |
| nykyaikhanen+A+Sg+Ill             | nykyaikhasheen             |
| tuhanen+A+Sg+Ill                  | tuhasheen                  |
| pohjanen+A+Sg+Ill                 | pohjasheen                 |
| sekanen+A+Sg+Ill                  | sekasheen                  |
| hoikkanen+A+Sg+Ill                | hoikkasheen                |
| kukkanen+A+Sg+Ill                 | kukkasheen                 |
| mukkanen+A+Sg+Ill                 | mukkasheen                 |
| tummatukkanen+A+Sg+Ill            | tummatukkasheen            |
| pitkäjalkanen+A+Sg+Ill            | pitkäjalkasheen            |
| lokanen+A+Sg+Ill                  | lokasheen                  |
| neljennuskanen+A+Sg+Ill           | neljennuskasheen           |
| salanen+A+Sg+Ill                  | salasheen                  |
| kiimanen+A+Sg+Ill                 | kiimasheen                 |
| ylivoimanen+A+Sg+Ill              | ylivoimasheen              |
| punanen+A+Sg+Ill                  | punasheen                  |
| vaaleepunanen+A+Sg+Ill            | vaaleepunasheen            |
| aniliinipunanen+A+Sg+Ill          | aniliinipunasheen          |
| vähävoipanen+A+Sg+Ill             | vähävoipasheen             |
| tasanen+A+Sg+Ill                  | tasasheen                  |
| kaitanen+A+Sg+Ill                 | kaitasheen                 |
| keltainen+A+Sg+Ill                | keltasheen                 |
| puolihintanen+A+Sg+Ill            | puolihintasheen            |
| monikertanen+A+Sg+Ill             | monikertasheen             |
| yksinkertanen+A+Sg+Ill            | yksinkertasheen            |
| vihainen+A+Sg+Ill                 | vihaisheen                 |
| vanhaanaikhainen+A+Sg+Ill         | vanhaanaikhaisheen         |
| samanaikhainen+A+Sg+Ill           | samanaikhaisheen           |
| uuđenaikhainen+A+Sg+Ill           | uuđenaikhaisheen           |
| nykyaikhainen+A+Sg+Ill            | nykyaikhaisheen            |
| pitkäaikhainen+A+Sg+Ill           | pitkäaikhaisheen           |
| kaukhainen+A+Sg+Ill               | kaukhaisheen               |
| alhainen+A+Sg+Ill                 | alhaisheen                 |
| salhainen+A+Sg+Ill                | salhaisheen                |
| eriskumhainen+A+Sg+Ill            | eriskumhaisheen            |
| varhainen+A+Sg+Ill                | varhaisheen                |
| aijankohthainen+A+Sg+Ill          | aijankohthaisheen          |
| pohjainen+A+Sg+Ill                | pohjaisheen                |
| hiljainen+A+Sg+Ill                | hiljaisheen                |
| sekainen+A+Sg+Ill                 | sekaisheen                 |
| väliaikainen+A+Sg+Ill             | väliaikaisheen             |
| likainen+A+Sg+Ill                 | likaisheen                 |
| nollapaikkainen+A+Sg+Ill          | nollapaikkaisheen          |
| kolmipaikkainen+A+Sg+Ill          | kolmipaikkaisheen          |
| kaksipaikkainen+A+Sg+Ill          | kaksipaikkaisheen          |
| yksipaikkainen+A+Sg+Ill           | yksipaikkaisheen           |
| tummatukkainen+A+Sg+Ill           | tummatukkaisheen           |
| neljenjalkainen+A+Sg+Ill          | neljenjalkaisheen          |
| pitkäjalkainen+A+Sg+Ill           | pitkäjalkaisheen           |
| vastahankainen+A+Sg+Ill           | vastahankaisheen           |
| kaksirankainen+A+Sg+Ill           | kaksirankaisheen           |
| yksirankainen+A+Sg+Ill            | yksirankaisheen            |
| konsonanttirankainen+A+Sg+Ill     | konsonanttirankaisheen     |
| lokainen+A+Sg+Ill                 | lokaisheen                 |
| paskainen+A+Sg+Ill                | paskaisheen                |
| nelinuskainen+A+Sg+Ill            | nelinuskaisheen            |
| puskainen+A+Sg+Ill                | puskaisheen                |
| latuskainen+A+Sg+Ill              | latuskaisheen              |
| ohukainen+A+Sg+Ill                | ohukaisheen                |
| korkukainen+A+Sg+Ill              | korkukaisheen              |
| oikkeuđenmukainen+A+Sg+Ill        | oikkeuđenmukaisheen        |
| reekelinmukainen+A+Sg+Ill         | reekelinmukaisheen         |
| epäreekelinmukainen+A+Sg+Ill      | epäreekelinmukaisheen      |
| suurukainen+A+Sg+Ill              | suurukaisheen              |
| pitukainen+A+Sg+Ill               | pitukaisheen               |
| maalainen+A+Sg+Ill                | maalaisheen                |
| ulkomaalainen+A+Sg+Ill            | ulkomaalaisheen            |
| ruijalainen+A+Sg+Ill              | ruijalaisheen              |
| talosvankkalainen+A+Sg+Ill        | talosvankkalaisheen        |
| jokalainen+A+Sg+Ill               | jokalaisheen               |
| tuiskalainen+A+Sg+Ill             | tuiskalaisheen             |
| tanskalainen+A+Sg+Ill             | tanskalaisheen             |
| roomalainen+A+Sg+Ill              | roomalaisheen              |
| suomalainen+A+Sg+Ill              | suomalaisheen              |
| norjalais-suomalainen+A+Sg+Ill    | norjalais-suomalaisheen    |
| suursuomalainen+A+Sg+Ill          | suursuomalaisheen          |
| salainen+A+Sg+Ill                 | salaisheen                 |
| saksalainen+A+Sg+Ill              | saksalaisheen              |
| tromssalainen+A+Sg+Ill            | tromssalaisheen            |
| ruottalainen+A+Sg+Ill             | ruottalaisheen             |
| juutalainen+A+Sg+Ill              | juutalaisheen              |
| vesisaarelainen+A+Sg+Ill          | vesisaarelaisheen          |
| pyssyjokilainen+A+Sg+Ill          | pyssyjokilaisheen          |
| puolilainen+A+Sg+Ill              | puolilaisheen              |
| saamilainen+A+Sg+Ill              | saamilaisheen              |
| erilainen+A+Sg+Ill                | erilaisheen                |
| evankeelis-lutherilainen+A+Sg+Ill | evankeelis-lutherilaisheen |
| suomalais-ugrilainen+A+Sg+Ill     | suomalais-ugrilaisheen     |
| raisilainen+A+Sg+Ill              | raisilaisheen              |
| englantilainen+A+Sg+Ill           | englantilaisheen           |
| hollantilainen+A+Sg+Ill           | hollantilaisheen           |
| paavilainen+A+Sg+Ill              | paavilaisheen              |
| villainen+A+Sg+Ill                | villaisheen                |
| tällainen+A+Sg+Ill                | tällaisheen                |
| samanlainen+A+Sg+Ill              | samanlaisheen              |
| muutamanlainen+A+Sg+Ill           | muutamanlaisheen           |
| kaikenlainen+A+Sg+Ill             | kaikenlaisheen             |
| pienenlainen+A+Sg+Ill             | pienenlaisheen             |
| monenlainen+A+Sg+Ill              | monenlaisheen              |
| nuorenlainen+A+Sg+Ill             | nuorenlaisheen             |
| senlainen+A+Sg+Ill                | senlaisheen                |
| toisenlainen+A+Sg+Ill             | toisenlaisheen             |
| kahđenlainen+A+Sg+Ill             | kahđenlaisheen             |
| yhđenlainen+A+Sg+Ill              | yhđenlaisheen              |
| tyyrhinlainen+A+Sg+Ill            | tyyrhinlaisheen            |
| isonlainen+A+Sg+Ill               | isonlaisheen               |
| tämänlainen+A+Sg+Ill              | tämänlaisheen              |
| höperänlainen+A+Sg+Ill            | höperänlaisheen            |
| vanholainen+A+Sg+Ill              | vanholaisheen              |
| lestadiolainen+A+Sg+Ill           | lestadiolaisheen           |
| torniolainen+A+Sg+Ill             | torniolaisheen             |
| vanholaislestaatiolainen+A+Sg+Ill | vanholaislestaatiolaisheen |
| alattiolainen+A+Sg+Ill            | alattiolaisheen            |
| tornionlaksolainen+A+Sg+Ill       | tornionlaksolaisheen       |
| suolainen+A+Sg+Ill                | suolaisheen                |
| tuolainen+A+Sg+Ill                | tuolaisheen                |
| savolainen+A+Sg+Ill               | savolaisheen               |
| jonkulainen+A+Sg+Ill              | jonkulaisheen              |
| kainulainen+A+Sg+Ill              | kainulaisheen              |
| vestakainulainen+A+Sg+Ill         | vestakainulaisheen         |
| minkälainen+A+Sg+Ill              | minkälaisheen              |
| kiimainen+A+Sg+Ill                | kiimaisheen                |
| alimainen+A+Sg+Ill                | alimaisheen                |
| ylivoimainen+A+Sg+Ill             | ylivoimaisheen             |
| ulomainen+A+Sg+Ill                | ulomaisheen                |
| etumainen+A+Sg+Ill                | etumaisheen                |
| yksituumainen+A+Sg+Ill            | yksituumaisheen            |
| hajanainen+A+Sg+Ill               | hajanaisheen               |
| vähäsanainen+A+Sg+Ill             | vähäsanaisheen             |
| aukinainen+A+Sg+Ill               | aukinaisheen               |
| harvinainen+A+Sg+Ill              | harvinaisheen              |
| kokonainen+A+Sg+Ill               | kokonaisheen               |
| punainen+A+Sg+Ill                 | punaisheen                 |
| vaaleepunainen+A+Sg+Ill           | vaaleepunaisheen           |
| aniliinipunainen+A+Sg+Ill         | aniliinipunaisheen         |
| ruusunpunainen+A+Sg+Ill           | ruusunpunaisheen           |
| vähävoipainen+A+Sg+Ill            | vähävoipaisheen            |
| pikkurainen+A+Sg+Ill              | pikkuraisheen              |
| tasainen+A+Sg+Ill                 | tasaisheen                 |
| epätasainen+A+Sg+Ill              | epätasaisheen              |
| hietainen+A+Sg+Ill                | hietaisheen                |
| kaitainen+A+Sg+Ill                | kaitaisheen                |
| ristiraitainen+A+Sg+Ill           | ristiraitaisheen           |
| väkivaltainen+A+Sg+Ill            | väkivaltaisheen            |
| keltainen+A+Sg+Ill                | keltaisheen                |
| punaisenkeltainen+A+Sg+Ill        | punaisenkeltaisheen        |
| puolihintainen+A+Sg+Ill           | puolihintaisheen           |
| monikertainen+A+Sg+Ill            | monikertaisheen            |
| monenkertainen+A+Sg+Ill           | monenkertaisheen           |
| kahđenkertainen+A+Sg+Ill          | kahđenkertaisheen          |
| yhđenkertainen+A+Sg+Ill           | yhđenkertaisheen           |
| yksinkertainen+A+Sg+Ill           | yksinkertaisheen           |
| virtainen+A+Sg+Ill                | virtaisheen                |
| vestainen+A+Sg+Ill                | vestaisheen                |
| luottavainen+A+Sg+Ill             | luottavaisheen             |
| vaivainen+A+Sg+Ill                | vaivaisheen                |
| uskovainen+A+Sg+Ill               | uskovaisheen               |
| varovainen+A+Sg+Ill               | varovaisheen               |
| karvainen+A+Sg+Ill                | karvaisheen                |
| rasvainen+A+Sg+Ill                | rasvaisheen                |
| likheinen+A+Sg+Ill                | likheisheen                |
| melkheinen+A+Sg+Ill               | melkheisheen               |
| ylheinen+A+Sg+Ill                 | ylheisheen                 |
| yhtheinen+A+Sg+Ill                | yhtheisheen                |
| myöntheinen+A+Sg+Ill              | myöntheisheen              |
| auringonpaistheinen+A+Sg+Ill      | auringonpaistheisheen      |
| fonoginen+A+Sg+Ill                | fonologisheen              |
| morfofonologinen+A+Sg+Ill         | morfofonologisheen         |
| biolooginen+A+Sg+Ill              | bioloogisheen              |
| psykolooginen+A+Sg+Ill            | psykoloogisheen            |
| ökolooginen+A+Sg+Ill              | ökoloogisheen              |
| vierhiinen+A+Sg+Ill               | vierhiisheen               |
| produktiivinen+A+Sg+Ill           | produktiisheen             |
| iänkaikkinen+A+Sg+Ill             | iänkaikkisheen             |
| piikkinen+A+Sg+Ill                | piikkisheen                |
| pahanilkinen+A+Sg+Ill             | pahanilkisheen             |
| nokinen+A+Sg+Ill                  | nokisheen                  |
| modaalinen+A+Sg+Ill               | modaalisheen               |
| sosiaalinen+A+Sg+Ill              | sosiaalisheen              |
| lyhykäisvokaalinen+A+Sg+Ill       | lyhykäisvokaalisheen       |
| maalinen+A+Sg+Ill                 | maalisheen                 |
| tradittiinaalinen+A+Sg+Ill        | tradittiinaalisheen        |
| pluraalinen+A+Sg+Ill              | pluraalisheen              |
| digitaalinen+A+Sg+Ill             | digitaalisheen             |
| aspektuaalinen+A+Sg+Ill           | aspektuaalisheen           |
| rauhalinen+A+Sg+Ill               | rauhalisheen               |
| histoorialinen+A+Sg+Ill           | histoorialisheen           |
| historialinen+A+Sg+Ill            | historialisheen            |
| paikalinen+A+Sg+Ill               | paikalisheen               |
| kummalinen+A+Sg+Ill               | kummalisheen               |
| vaaralinen+A+Sg+Ill               | vaaralisheen               |
| viralinen+A+Sg+Ill                | viralisheen                |
| kansalinen+A+Sg+Ill               | kansalisheen               |
| osalinen+A+Sg+Ill                 | osalisheen                 |
| tavalinen+A+Sg+Ill                | tavalisheen                |
| epätavalinen+A+Sg+Ill             | epätavalisheen             |
| turvalinen+A+Sg+Ill               | turvalisheen               |
| luvalinen+A+Sg+Ill                | luvalisheen                |
| raiđalinen+A+Sg+Ill               | raiđalisheen               |
| tarpheelinen+A+Sg+Ill             | tarpheelisheen             |
| murheelinen+A+Sg+Ill              | murheelisheen              |
| katheelinen+A+Sg+Ill              | katheelisheen              |
| satheelinen+A+Sg+Ill              | satheelisheen              |
| puutheelinen+A+Sg+Ill             | puutheelisheen             |
| tervheelinen+A+Sg+Ill             | tervheelisheen             |
| hengelinen+A+Sg+Ill               | hengelisheen               |
| rehelinen+A+Sg+Ill                | rehelisheen                |
| kolmikielinen+A+Sg+Ill            | kolmikielisheen            |
| kaksikielinen+A+Sg+Ill            | kaksikielisheen            |
| suomenkielinen+A+Sg+Ill           | suomenkielisheen           |
| kainunkielinen+A+Sg+Ill           | kainunkielisheen           |
| ylimielinen+A+Sg+Ill              | ylimielisheen              |
| yksmielinen+A+Sg+Ill              | yksmielisheen              |
| onnelinen+A+Sg+Ill                | onnelisheen                |
| äänelinen+A+Sg+Ill                | äänelisheen                |
| lapselinen+A+Sg+Ill               | lapselisheen               |
| ittelinen+A+Sg+Ill                | ittelisheen                |
| tähđelinen+A+Sg+Ill               | tähđelisheen               |
| tođelinen+A+Sg+Ill                | tođelisheen                |
| täyđelinen+A+Sg+Ill               | täyđelisheen               |
| eilinen+A+Sg+Ill                  | eilisheen                  |
| ruumhiilinen+A+Sg+Ill             | ruumhiilisheen             |
| faakilinen+A+Sg+Ill               | faakilisheen               |
| arkiivifaakilinen+A+Sg+Ill        | arkiivifaakilisheen        |
| merkilinen+A+Sg+Ill               | merkilisheen               |
| teknilinen+A+Sg+Ill               | teknilisheen               |
| kropilinen+A+Sg+Ill               | kropilisheen               |
| tyypilinen+A+Sg+Ill               | tyypilisheen               |
| sportilinen+A+Sg+Ill              | sportilisheen              |
| kristilinen+A+Sg+Ill              | kristilisheen              |
| paralellinen+A+Sg+Ill             | paralellisheen             |
| histoorillinen+A+Sg+Ill           | histoorillisheen           |
| uskonollinen+A+Sg+Ill             | uskonollisheen             |
| ystävällinen+A+Sg+Ill             | ystävällisheen             |
| pakolinen+A+Sg+Ill                | pakolisheen                |
| uskolinen+A+Sg+Ill                | uskolisheen                |
| joukolinen+A+Sg+Ill               | joukolisheen               |
| armolinen+A+Sg+Ill                | armolisheen                |
| painolinen+A+Sg+Ill               | painolisheen               |
| valtapainolinen+A+Sg+Ill          | valtapainolisheen          |
| sivvupainolinen+A+Sg+Ill          | sivvupainolisheen          |
| kunnolinen+A+Sg+Ill               | kunnolisheen               |
| luonolinen+A+Sg+Ill               | luonolisheen               |
| urhoolinen+A+Sg+Ill               | urhoolisheen               |
| ehtoolinen+A+Sg+Ill               | ehtoolisheen               |
| kiitolinen+A+Sg+Ill               | kiitolisheen               |
| luontolinen+A+Sg+Ill              | luontolisheen              |
| javolinen+A+Sg+Ill                | javolisheen                |
| velvolinen+A+Sg+Ill               | velvolisheen               |
| mahđolinen+A+Sg+Ill               | mahđolisheen               |
| prikulinen+A+Sg+Ill               | prikulisheen               |
| lopulinen+A+Sg+Ill                | lopulisheen                |
| pirulinen+A+Sg+Ill                | pirulisheen                |
| surulinen+A+Sg+Ill                | surulisheen                |
| ruuđulinen+A+Sg+Ill               | ruuđulisheen               |
| ylinen+A+Sg+Ill                   | ylisheen                   |
| myrkylinen+A+Sg+Ill               | myrkylisheen               |
| lykylinen+A+Sg+Ill                | lykylisheen                |
| hyöđylinen+A+Sg+Ill               | hyöđylisheen               |
| pitkälinen+A+Sg+Ill               | pitkälisheen               |
| välinen+A+Sg+Ill                  | välisheen                  |
| viiminen+A+Sg+Ill                 | viimisheen                 |
| ekonominen+A+Sg+Ill               | ekonomisheen               |
| autonoominen+A+Sg+Ill             | autonoomisheen             |
| luminen+A+Sg+Ill                  | lumisheen                  |
| synonyyminen+A+Sg+Ill             | synonyymisheen             |
| sininen+A+Sg+Ill                  | sinisheen                  |
| vaaleesininen+A+Sg+Ill            | vaaleesinisheen            |
| elektroninen+A+Sg+Ill             | elektronisheen             |
| pahanjuoninen+A+Sg+Ill            | pahanjuonisheen            |
| vastahakoinen+A+Sg+Ill            | vastahakoisheen            |
| kotitekoinen+A+Sg+Ill             | kotitekoisheen             |
| erikoinen+A+Sg+Ill                | erikoisheen                |
| louhikkoinen+A+Sg+Ill             | louhikkoisheen             |
| alinkoinen+A+Sg+Ill               | alinkoisheen               |
| aurinkoinen+A+Sg+Ill              | aurinkoisheen              |
| kokoinen+A+Sg+Ill                 | kokoisheen                 |
| puolikokoinen+A+Sg+Ill            | puolikokoisheen            |
| epäuskoinen+A+Sg+Ill              | epäuskoisheen              |
| iloinen+A+Sg+Ill                  | iloisheen                  |
| kiloinen+A+Sg+Ill                 | kiloisheen                 |
| suloinen+A+Sg+Ill                 | suloisheen                 |
| epäluuloinen+A+Sg+Ill             | epäluuloisheen             |
| kivuloinen+A+Sg+Ill               | kivuloisheen               |
| aikamoinen+A+Sg+Ill               | aikamoisheen               |
| semmoinen+A+Sg+Ill                | semmoisheen                |
| tuomoinen+A+Sg+Ill                | tuomoisheen                |
| toinen+A+Sg+Ill                   | toisheen                   |
| pitkävetoinen+A+Sg+Ill            | pitkävetoisheen            |
| vapaaehtoinen+A+Sg+Ill            | vapaaehtoisheen            |
| hyvämuistoinen+A+Sg+Ill           | hyvämuistoisheen           |
| samanarvoinen+A+Sg+Ill            | samanarvoisheen            |
| prototyyppinen+A+Sg+Ill           | prototyyppisheen           |
| populaarinen+A+Sg+Ill             | populaarisheen             |
| porvarinen+A+Sg+Ill               | porvarisheen               |
| geneerinen+A+Sg+Ill               | geneerisheen               |
| tummaverinen+A+Sg+Ill             | tummaverisheen             |
| vihrinen+A+Sg+Ill                 | vihrisheen                 |
| kelta-vihrinen+A+Sg+Ill           | kelta-vihrisheen           |
| sini-vihrinen+A+Sg+Ill            | sini-vihrisheen            |
| obligatoorinen+A+Sg+Ill           | obligatoorisheen           |
| elektrinen+A+Sg+Ill               | elektrisheen               |
| pahankurinen+A+Sg+Ill             | pahankurisheen             |
| hullunkurinen+A+Sg+Ill            | hullunkurisheen            |
| kulttuurinen+A+Sg+Ill             | kulttuurisheen             |
| färinen+A+Sg+Ill                  | färisheen                  |
| erifärinen+A+Sg+Ill               | erifärisheen               |
| samanfärinen+A+Sg+Ill             | samanfärisheen             |
| vesinen+A+Sg+Ill                  | vesisheen                  |
| kaksinen+A+Sg+Ill                 | kaksisheen                 |
| kompleksinen+A+Sg+Ill             | kompleksisheen             |
| pitkävarsinen+A+Sg+Ill            | pitkävarsisheen            |
| saftinen+A+Sg+Ill                 | saftisheen                 |
| syntaktinen+A+Sg+Ill              | syntaktisheen              |
| entinen+A+Sg+Ill                  | entisheen                  |
| syntinen+A+Sg+Ill                 | syntisheen                 |
| läntinen+A+Sg+Ill                 | läntisheen                 |
| totinen+A+Sg+Ill                  | totisheen                  |
| vuotinen+A+Sg+Ill                 | vuotisheen                 |
| dramaattinen+A+Sg+Ill             | dramaattisheen             |
| systemaattinen+A+Sg+Ill           | systemaattisheen           |
| symptomaattinen+A+Sg+Ill          | symptomaattisheen          |
| sympaattinen+A+Sg+Ill             | sympaattisheen             |
| konkreettinen+A+Sg+Ill            | konkreettisheen            |
| poliittinen+A+Sg+Ill              | poliittisheen              |
| polittinen+A+Sg+Ill               | polittisheen               |
| pulittinen+A+Sg+Ill               | pulittisheen               |
| neljenkanttinen+A+Sg+Ill          | neljenkanttisheen          |
| kahđeksenkanttinen+A+Sg+Ill       | kahđeksenkanttisheen       |
| neliskanttinen+A+Sg+Ill           | neliskanttisheen           |
| semanttinen+A+Sg+Ill              | semanttisheen              |
| romanttinen+A+Sg+Ill              | romanttisheen              |
| identtinen+A+Sg+Ill               | identtisheen               |
| yhđensorttinen+A+Sg+Ill           | yhđensorttisheen           |
| uuđenaikhuinen+A+Sg+Ill           | uuđenaikhuisheen           |
| mielhuinen+A+Sg+Ill               | mielhuisheen               |
| ikuinen+A+Sg+Ill                  | ikuisheen                  |
| pikkuinen+A+Sg+Ill                | pikkuisheen                |
| harkkuinen+A+Sg+Ill               | harkkuisheen               |
| korkuinen+A+Sg+Ill                | korkuisheen                |
| suomensukuinen+A+Sg+Ill           | suomensukuisheen           |
| luinen+A+Sg+Ill                   | luisheen                   |
| viluinen+A+Sg+Ill                 | viluisheen                 |
| hirmuinen+A+Sg+Ill                | hirmuisheen                |
| sumuinen+A+Sg+Ill                 | sumuisheen                 |
| hoppuinen+A+Sg+Ill                | hoppuisheen                |
| sananloppuinen+A+Sg+Ill           | sananloppuisheen           |
| vakituinen+A+Sg+Ill               | vakituisheen               |
| omituinen+A+Sg+Ill                | omituisheen                |
| pituinen+A+Sg+Ill                 | pituisheen                 |
| vasituinen+A+Sg+Ill               | vasituisheen               |
| joutuinen+A+Sg+Ill                | joutuisheen                |
| usheempitavuinen+A+Sg+Ill         | usheempitavuisheen         |
| kaksitavuinen+A+Sg+Ill            | kaksitavuisheen            |
| yksitavuinen+A+Sg+Ill             | yksitavuisheen             |
| skandinaavinen+A+Sg+Ill           | skandinaavisheen           |
| passiivinen+A+Sg+Ill              | passiivisheen              |
| abessiivinen+A+Sg+Ill             | abessiivisheen             |
| kreatiivinen+A+Sg+Ill             | kreatiivisheen             |
| nekatiivinen+A+Sg+Ill             | nekatiivisheen             |
| administratiivinen+A+Sg+Ill       | administratiivisheen       |
| kausatiivinen+A+Sg+Ill            | kausatiivisheen            |
| primitiivinen+A+Sg+Ill            | primitiivisheen            |
| positiivinen+A+Sg+Ill             | positiivisheen             |
| pusitiivinen+A+Sg+Ill             | pusitiivisheen             |
| aktiivinen+A+Sg+Ill               | aktiivisheen               |
| effektiivinen+A+Sg+Ill            | effektiivisheen            |
| konnektiivinen+A+Sg+Ill           | konnektiivisheen           |
| fiktiivinen+A+Sg+Ill              | fiktiivisheen              |
| disjunktiivinen+A+Sg+Ill          | disjunktiivisheen          |
| kivinen+A+Sg+Ill                  | kivisheen                  |
| pilvinen+A+Sg+Ill                 | pilvisheen                 |
| rynkkyinen+A+Sg+Ill               | rynkkyisheen               |
| nykyinen+A+Sg+Ill                 | nykyisheen                 |
| pölyinen+A+Sg+Ill                 | pölyisheen                 |
| erityinen+A+Sg+Ill                | erityisheen                |
| ikhäinen+A+Sg+Ill                 | ikhäisheen                 |
| keski-ikhäinen+A+Sg+Ill           | keski-ikhäisheen           |
| alaikhäinen+A+Sg+Ill              | alaikhäisheen              |
| vähäinen+A+Sg+Ill                 | vähäisheen                 |
| alaikäinen+A+Sg+Ill               | alaikäisheen               |
| reikäinen+A+Sg+Ill                | reikäisheen                |
| koukkuselkäinen+A+Sg+Ill          | koukkuselkäisheen          |
| koukkusölkäinen+A+Sg+Ill          | koukkusölkäisheen          |
| ymmyrkäinen+A+Sg+Ill              | ymmyrkäisheen              |
| lyhykäinen+A+Sg+Ill               | lyhykäisheen               |
| äkäinen+A+Sg+Ill                  | äkäisheen                  |
| itteläinen+A+Sg+Ill               | itteläisheen               |
| briittiläinen+A+Sg+Ill            | briittiläisheen            |
| pitkyläinen+A+Sg+Ill              | pitkyläisheen              |
| yykeäläinen+A+Sg+Ill              | yykeäläisheen              |
| pykejäläinen+A+Sg+Ill             | pykejäläisheen             |
| tyskäläinen+A+Sg+Ill              | tyskäläisheen              |
| venäläinen+A+Sg+Ill               | venäläisheen               |
| ryssäläinen+A+Sg+Ill              | ryssäläisheen              |
| likimäinen+A+Sg+Ill               | likimäisheen               |
| jälkimäinen+A+Sg+Ill              | jälkimäisheen              |
| keskimäinen+A+Sg+Ill              | keskimäisheen              |
| täkimäinen+A+Sg+Ill               | täkimäisheen               |
| ylimäinen+A+Sg+Ill                | ylimäisheen                |
| päälimäinen+A+Sg+Ill              | päälimäisheen              |
| ensimäinen+A+Sg+Ill               | ensimäisheen               |
| tämmäinen+A+Sg+Ill                | tämmäisheen                |
| pörämäinen+A+Sg+Ill               | pörämäisheen               |
| ittenäinen+A+Sg+Ill               | ittenäisheen               |
| äkkinäinen+A+Sg+Ill               | äkkinäisheen               |
| yksinäinen+A+Sg+Ill               | yksinäisheen               |
| ittepäinen+A+Sg+Ill               | ittepäisheen               |
| kaljupäinen+A+Sg+Ill              | kaljupäisheen              |
| ymmyräinen+A+Sg+Ill               | ymmyräisheen               |
| alkupöräinen+A+Sg+Ill             | alkupöräisheen             |
| pahasäinen+A+Sg+Ill               | pahasäisheen               |
| sisäinen+A+Sg+Ill                 | sisäisheen                 |
| öystäinen+A+Sg+Ill                | öystäisheen                |
| myötäinen+A+Sg+Ill                | myötäisheen                |
| tytyväinen+A+Sg+Ill               | tytyväisheen               |
| näköinen+A+Sg+Ill                 | näköisheen                 |
| pirunnäköinen+A+Sg+Ill            | pirunnäköisheen            |
| tämmöinen+A+Sg+Ill                | tämmöisheen                |
| vähätöinen+A+Sg+Ill               | vähätöisheen               |
| veres+A+Sg+Ill                    | vereksheen                 |
| kotitekonen+A+Sg+Ill              | kotitekosheen              |
| louhikkonen+A+Sg+Ill              | louhikkosheen              |
| pilkkonen+A+Sg+Ill                | pilkkosheen                |
| puolikokonen+A+Sg+Ill             | puolikokosheen             |
| semmonen+A+Sg+Ill                 | semmosheen                 |
| tuomoinen+A+Sg+Ill                | tuomosheen                 |
| vapaaehtonen+A+Sg+Ill             | vapaaehtosheen             |
| kotonen+A+Sg+Ill                  | kotosheen                  |
| ikunen+A+Sg+Ill                   | ikusheen                   |
| pikkunen+A+Sg+Ill                 | pikkusheen                 |
| harkkunen+A+Sg+Ill                | harkkusheen                |
| vilunen+A+Sg+Ill                  | vilusheen                  |
| hirmunen+A+Sg+Ill                 | hirmusheen                 |
| rynkkynen+A+Sg+Ill                | rynkkysheen                |
| nykynen+A+Sg+Ill                  | nykysheen                  |
| pölynen+A+Sg+Ill                  | pölysheen                  |
| vähänen+A+Sg+Ill                  | vähäsheen                  |
| alaikänen+A+Sg+Ill                | alaikäsheen                |
| äkänen+A+Sg+Ill                   | äkäsheen                   |
| tämmänen+A+Sg+Ill                 | tämmäsheen                 |
| alkupöränen+A+Sg+Ill              | alkupöräsheen              |
| sisänen+A+Sg+Ill                  | sisäsheen                  |
| näkönen+A+Sg+Ill                  | näkösheen                  |
| pirunnäkönen+A+Sg+Ill             | pirunnäkösheen             |
| tosi+A+Sg+Ill                     | totheen                    |
| uusi+A+Sg+Ill                     | uutheen                    |
| täysi+A+Sg+Ill                    | täytheen                   |
| pälvi+A+Sg+Ill                    | pälvheen                   |
| pahas+A+Sg+Ill                    | pahhaasseen                |
| puhelias+A+Sg+Ill                 | puhelihaasseen             |
| laupias+A+Sg+Ill                  | laupihaasseen              |
| kaikkivaltias+A+Sg+Ill            | kaikkivaltihaasseen        |
| paljas+A+Sg+Ill                   | paljhaasseen               |
| voimakas+A+Sg+Ill                 | voimakkhaasseen            |
| rakas+A+Sg+Ill                    | rakkhaasseen               |
| viekas+A+Sg+Ill                   | viekkhaasseen              |
| onnekas+A+Sg+Ill                  | onnekkhaasseen             |
| raikas+A+Sg+Ill                   | raikkhaasseen              |
| vitamiinikas+A+Sg+Ill             | vitamiinikkhaasseen        |
| rikas+A+Sg+Ill                    | rikkhaasseen               |
| raharikas+A+Sg+Ill                | raharikkhaasseen           |
| fantasiirikas+A+Sg+Ill            | fantasiirikkhaasseen       |
| lajirikas+A+Sg+Ill                | lajirikkhaasseen           |
| färirikas+A+Sg+Ill                | färirikkhaasseen           |
| tietorikas+A+Sg+Ill               | tietorikkhaasseen          |
| sađetrikas+A+Sg+Ill               | sađetrikkhaasseen          |
| lapsikas+A+Sg+Ill                 | lapsikkhaasseen            |
| praatikas+A+Sg+Ill                | praatikkhaasseen           |
| vilkas+A+Sg+Ill                   | vilkkhaasseen              |
| nerokas+A+Sg+Ill                  | nerokkhaasseen             |
| arvokas+A+Sg+Ill                  | arvokkhaasseen             |
| kirkas+A+Sg+Ill                   | kirkkhaasseen              |
| liukas+A+Sg+Ill                   | liukkhaasseen              |
| raskas+A+Sg+Ill                   | raskhaasseen               |
| hurskas+A+Sg+Ill                  | hurskhaasseen              |
| vanhurskas+A+Sg+Ill               | vanhurskhaasseen           |
| joutilas+A+Sg+Ill                 | joutilhaasseen             |
| armas+A+Sg+Ill                    | armhaasseen                |
| vanhaa+A+Sg+Ill                   | vanhaasseen                |
| vapaa+A+Sg+Ill                    | vaphaasseen                |
| reipas+A+Sg+Ill                   | reipphaasseen              |
| opas+A+Sg+Ill                     | opphaasseen                |
| vieras+A+Sg+Ill                   | vierhaasseen               |
| ventovieras+A+Sg+Ill              | ventovierhaasseen          |
| sairas+A+Sg+Ill                   | sairhaasseen               |
| viisas+A+Sg+Ill                   | viishaasseen               |
| itteviisas+A+Sg+Ill               | itteviishaasseen           |
| runsas+A+Sg+Ill                   | runshaasseen               |
| karsas+A+Sg+Ill                   | karshaasseen               |
| ahđas+A+Sg+Ill                    | ahthaasseen                |
| puhđas+A+Sg+Ill                   | puhthaasseen               |
| hiđas+A+Sg+Ill                    | hithaasseen                |
| harras+A+Sg+Ill                   | harthaasseen               |
| laatas+A+Sg+Ill                   | laatthaasseen              |
| rietas+A+Sg+Ill                   | rietthaasseen              |
| autuas+A+Sg+Ill                   | autuhaasseen               |
| raavas+A+Sg+Ill                   | raavhaasseen               |
| karvas+A+Sg+Ill                   | karvhaasseen               |
| sakea+A+Sg+Ill                    | sakeasseen                 |
| korkea+A+Sg+Ill                   | korkeasseen                |
| ruskea+A+Sg+Ill                   | ruskeasseen                |
| ehhee+A+Sg+Ill                    | ehheesseen                 |
| tihhee+A+Sg+Ill                   | tihheesseen                |
| kuolu+A+Sg+Ill                    | kuolheesseen               |
| kokenu+A+Sg+Ill                   | kokenheesseen              |
| ahnet+A+Sg+Ill                    | ahnheesseen                |
| nainu+A+Sg+Ill                    | nainheesseen               |
| tiinet+A+Sg+Ill                   | tiinheesseen               |
| oppinu+A+Sg+Ill                   | oppinheesseen              |
| ravistunnu+A+Sg+Ill               | ravistunnheesseen          |
| hermostunnu+A+Sg+Ill              | hermostunnheesseen         |
| hengestynny+A+Sg+Ill              | hengestynnheesseen         |
| hengistynny+A+Sg+Ill              | hengistynnheesseen         |
| vaipunu+A+Sg+Ill                  | vaipunheesseen             |
| suuttunu+A+Sg+Ill                 | suuttunheesseen            |
| väsyny+A+Sg+Ill                   | väsynheesseen              |
| tuoret+A+Sg+Ill                   | tuorheesseen               |
| ussee+A+Sg+Ill                    | usheesseen                 |
| kauhhee+A+Sg+Ill                  | kauheesseen                |
| tervet+A+Sg+Ill                   | tervheesseen               |
| rohkee+A+Sg+Ill                   | rohkeesseen                |
| laakkee+A+Sg+Ill                  | laakkeesseen               |
| makkee+A+Sg+Ill                   | makkeesseen                |
| sakkee+A+Sg+Ill                   | sakkeesseen                |
| vaikkee+A+Sg+Ill                  | vaikkeesseen               |
| oikkee+A+Sg+Ill                   | oikkeesseen                |
| muikkee+A+Sg+Ill                  | muikkeesseen               |
| valkkee+A+Sg+Ill                  | valkkeesseen               |
| ilmivalkkee+A+Sg+Ill              | ilmivalkkeesseen           |
| vitivalkkee+A+Sg+Ill              | vitivalkkeesseen           |
| selkkee+A+Sg+Ill                  | selkkeesseen               |
| ilkkee+A+Sg+Ill                   | ilkkeesseen                |
| sokkee+A+Sg+Ill                   | sokkeesseen                |
| huokkee+A+Sg+Ill                  | huokkeesseen               |
| karkkee+A+Sg+Ill                  | karkkeesseen               |
| korkkee+A+Sg+Ill                  | korkkeesseen               |
| tärkkee+A+Sg+Ill                  | tärkkeesseen               |
| aukkee+A+Sg+Ill                   | aukkeesseen                |
| laukkee+A+Sg+Ill                  | laukkeesseen               |
| ruskee+A+Sg+Ill                   | ruskeesseen                |
| sitkee+A+Sg+Ill                   | sitkeesseen                |
| notkee+A+Sg+Ill                   | notkeesseen                |
| haalee+A+Sg+Ill                   | haaleesseen                |
| vaalee+A+Sg+Ill                   | vaaleesseen                |
| haalee+A+Sg+Ill                   | halleesseen                |
| sillee+A+Sg+Ill                   | silleesseen                |
| pehmee+A+Sg+Ill                   | pehmeesseen                |
| himmee+A+Sg+Ill                   | himmeesseen                |
| pimmee+A+Sg+Ill                   | pimmeesseen                |
| pilkkapimmee+A+Sg+Ill             | pilkkapimmeesseen          |
| säkkipimmee+A+Sg+Ill              | säkkipimmeesseen           |
| syyspimmee+A+Sg+Ill               | syyspimmeesseen            |
| kommee+A+Sg+Ill                   | kommeesseen                |
| kirmee+A+Sg+Ill                   | kirmeesseen                |
| ahnee+A+Sg+Ill                    | ahneesseen                 |
| kappee+A+Sg+Ill                   | kappeesseen                |
| rappee+A+Sg+Ill                   | rappeesseen                |
| lieppee+A+Sg+Ill                  | lieppeesseen               |
| kippee+A+Sg+Ill                   | kippeesseen                |
| merikippee+A+Sg+Ill               | merikippeesseen            |
| ylppee+A+Sg+Ill                   | ylppeesseen                |
| noppee+A+Sg+Ill                   | noppeesseen                |
| virree+A+Sg+Ill                   | virreesseen                |
| korree+A+Sg+Ill                   | korreesseen                |
| murree+A+Sg+Ill                   | murreesseen                |
| pyöree+A+Sg+Ill                   | pyöreesseen                |
| kalssee+A+Sg+Ill                  | kalsseesseen               |
| kostee+A+Sg+Ill                   | kosteesseen                |
| laattee+A+Sg+Ill                  | laatteesseen               |
| kiinttee+A+Sg+Ill                 | kiintteesseen              |
| hirvee+A+Sg+Ill                   | hirveesseen                |
| kevvee+A+Sg+Ill                   | kevveesseen                |
| levvee+A+Sg+Ill                   | levveesseen                |
| kallis+A+Sg+Ill                   | kallhiisseen               |
| valmis+A+Sg+Ill                   | valmhiisseen               |
| kaunis+A+Sg+Ill                   | kaunhiisseen               |
| tyyris+A+Sg+Ill                   | tyyrhiisseen               |
| raitis+A+Sg+Ill                   | raitthiisseen              |
| tivis+A+Sg+Ill                    | tivhiisseen                |
| auttii+A+Sg+Ill                   | auttiisseen                |
| liehmuu+A+Sg+Ill                  | liehmuusseen               |
| kärys+A+Sg+Ill                    | kärhyysseen                |
| sinnikäs+A+Sg+Ill                 | sinnikkhäässeen            |
| fakki+A+Sg+Ill                    | fakkhiin                   |
| plankki+A+Sg+Ill                  | plankkhiin                 |
| flinkki+A+Sg+Ill                  | flinkkhiin                 |
| härski+A+Sg+Ill                   | härskhiin                  |
| ratikaali+A+Sg+Ill                | ratikaalhiin               |
| normaali+A+Sg+Ill                 | normaalhiin                |
| rekiunaali+A+Sg+Ill               | rekiunaalhiin              |
| liberaali+A+Sg+Ill                | liberaalhiin               |
| sentraali+A+Sg+Ill                | sentraalhiin               |
| simppeli+A+Sg+Ill                 | simppelhiin                |
| passeli+A+Sg+Ill                  | passelhiin                 |
| villi+A+Sg+Ill                    | villhiin                   |
| hööli+A+Sg+Ill                    | höölhiin                   |
| himmi+A+Sg+Ill                    | himmhiin                   |
| kleini+A+Sg+Ill                   | kleinhiin                  |
| fiini+A+Sg+Ill                    | fiinhiin                   |
| pruuni+A+Sg+Ill                   | pruunhiin                  |
| klaari+A+Sg+Ill                   | klaarhiin                  |
| naakkari+A+Sg+Ill                 | naakkarhiin                |
| sikkari+A+Sg+Ill                  | sikkarhiin                 |
| eri+A+Sg+Ill                      | erhiin                     |
| primääri+A+Sg+Ill                 | primäärhiin                |
| oransi+A+Sg+Ill                   | oranshiin                  |
| vissi+A+Sg+Ill                    | visshiin                   |
| epävissi+A+Sg+Ill                 | epävisshiin                |
| oranssi+A+Sg+Ill                  | oransshiin                 |
| siisti+A+Sg+Ill                   | siisthiin                  |
| fioletti+A+Sg+Ill                 | fioletthiin                |
| ultrafioletti+A+Sg+Ill            | ultrafioletthiin           |
| interesantti+A+Sg+Ill             | interesantthiin            |
| ekvivalentti+A+Sg+Ill             | ekvivalentthiin            |
| söötti+A+Sg+Ill                   | söötthiin                  |
| nekatiivi+A+Sg+Ill                | nekatiivhiin               |
| primitiivi+A+Sg+Ill               | primitiivhiin              |
| krouvi+A+Sg+Ill                   | krouvhiin                  |
| oranši+A+Sg+Ill                   | oranšhiin                  |
| laho+A+Sg+Ill                     | lahhoon                    |
| mainio+A+Sg+Ill                   | mainihoon                  |
| ujo+A+Sg+Ill                      | ujhoon                     |
| heikko+A+Sg+Ill                   | heikkhoon                  |
| silko+A+Sg+Ill                    | silkhoon                   |
| ulko+A+Sg+Ill                     | ulkhoon                    |
| kaalo+A+Sg+Ill                    | kaalhoon                   |
| tollo+A+Sg+Ill                    | tollhoon                   |
| kolo+A+Sg+Ill                     | kolhoon                    |
| hieno+A+Sg+Ill                    | hienhoon                   |
| kehno+A+Sg+Ill                    | kehnhoon                   |
| huono+A+Sg+Ill                    | huonhoon                   |
| helppo+A+Sg+Ill                   | helpphoon                  |
| juoppo+A+Sg+Ill                   | juopphoon                  |
| suipero+A+Sg+Ill                  | suiperhoon                 |
| kuuro+A+Sg+Ill                    | kuurhoon                   |
| iso+A+Sg+Ill                      | ishoon                     |
| lakso+A+Sg+Ill                    | lakshoon                   |
| viinto+A+Sg+Ill                   | viinthoon                  |
| vaisto+A+Sg+Ill                   | vaisthoon                  |
| pisto+A+Sg+Ill                    | pisthoon                   |
| visto+A+Sg+Ill                    | visthoon                   |
| kaltto+A+Sg+Ill                   | kaltthoon                  |
| ontto+A+Sg+Ill                    | ontthoon                   |
| rutto+A+Sg+Ill                    | rutthoon                   |
| outo+A+Sg+Ill                     | outhoon                    |
| siivo+A+Sg+Ill                    | siivhoon                   |
| raju+A+Sg+Ill                     | rajhuun                    |
| kalju+A+Sg+Ill                    | kaljhuun                   |
| virkku+A+Sg+Ill                   | virkkhuun                  |
| hullu+A+Sg+Ill                    | hullhuun                   |
| sotahullu+A+Sg+Ill                | sotahullhuun               |
| kuulu+A+Sg+Ill                    | kuulhuun                   |
| lamu+A+Sg+Ill                     | lamhuun                    |
| karu+A+Sg+Ill                     | karhuun                    |
| kesu+A+Sg+Ill                     | keshuun                    |
| visu+A+Sg+Ill                     | vishuun                    |
| paksu+A+Sg+Ill                    | pakshuun                   |
| kalsu+A+Sg+Ill                    | kalshuun                   |
| kuvailtu+A+Sg+Ill                 | kuvailthuun                |
| merkattu+A+Sg+Ill                 | merkatthuun                |
| maalattu+A+Sg+Ill                 | maalatthuun                |
| ulkokullattu+A+Sg+Ill             | ulkokullatthuun            |
| kevveestisuolattu+A+Sg+Ill        | kevveestisuolatthuun       |
| siunattu+A+Sg+Ill                 | siunatthuun                |
| tunnettu+A+Sg+Ill                 | tunnetthuun                |
| opetettu+A+Sg+Ill                 | opetetthuun                |
| valittu+A+Sg+Ill                  | valitthuun                 |
| vasittu+A+Sg+Ill                  | vasitthuun                 |
| kranttu+A+Sg+Ill                  | krantthuun                 |
| kattottu+A+Sg+Ill                 | kattotthuun                |
| kotonakuottu+A+Sg+Ill             | kotonakuotthuun            |
| tuttu+A+Sg+Ill                    | tutthuun                   |
| koutu+A+Sg+Ill                    | kouthuun                   |
| häijy+A+Sg+Ill                    | häijhyyn                   |
| syyry+A+Sg+Ill                    | syyrhyyn                   |
| kypsy+A+Sg+Ill                    | kypshyyn                   |
| niinkäsketty+A+Sg+Ill             | niinkäsketthyyn            |
| kylmetty+A+Sg+Ill                 | kylmetthyyn                |
| pyhitetty+A+Sg+Ill                | pyhitetthyyn               |
| käytetty+A+Sg+Ill                 | käytetthyyn                |
| kristitty+A+Sg+Ill                | kristitthyyn               |
| määrätty+A+Sg+Ill                 | määrätthyyn                |
| präntätty+A+Sg+Ill                | präntätthyyn               |
| pyhä+A+Sg+Ill                     | pyhhään                    |
| tyyhä+A+Sg+Ill                    | tyyhhään                   |
| köyhä+A+Sg+Ill                    | köyhhään                   |
| löyhä+A+Sg+Ill                    | löyhhään                   |
| vähä+A+Sg+Ill                     | vähhään                    |
| tyhjä+A+Sg+Ill                    | tyhjhään                   |
| väljä+A+Sg+Ill                    | väljhään                   |
| pelkkä+A+Sg+Ill                   | pelkkhään                  |
| synkkä+A+Sg+Ill                   | synkkhään                  |
| herkkä+A+Sg+Ill                   | herkkhään                  |
| jyrkkä+A+Sg+Ill                   | jyrkkhään                  |
| nyrkkä+A+Sg+Ill                   | nyrkkhään                  |
| mykkä+A+Sg+Ill                    | mykkhään                   |
| märkä+A+Sg+Ill                    | märkhään                   |
| läpimärkä+A+Sg+Ill                | läpimärkhään               |
| pitkä+A+Sg+Ill                    | pitkhään                   |
| ytelä+A+Sg+Ill                    | ytelhään                   |
| tyhmä+A+Sg+Ill                    | tyhmhään                   |
| lämmin+A+Sg+Ill                   | lämpimhään                 |
| kylmä+A+Sg+Ill                    | kylmhään                   |
| jääkylmä+A+Sg+Ill                 | jääkylmhään                |
| hengetön+A+Sg+Ill                 | hengettömhään              |
| äänetön+A+Sg+Ill                  | äänettömhään               |
| pilvetön+A+Sg+Ill                 | pilvettömhään              |
| färitön+A+Sg+Ill                  | färittömhään               |
| hävitön+A+Sg+Ill                  | hävittömhään               |
| hävytön+A+Sg+Ill                  | hävyttömhään               |
| kykenemätön+A+Sg+Ill              | kykenemättömhään           |
| kärsimätön+A+Sg+Ill               | kärsimättömhään            |
| näkymätön+A+Sg+Ill                | näkymättömhään             |
| tietämätön+A+Sg+Ill               | tietämättömhään            |
| ymmärtämätön+A+Sg+Ill             | ymmärtämättömhään          |
| välttämätön+A+Sg+Ill              | välttämättömhään           |
| määrätön+A+Sg+Ill                 | määrättömhään              |
| mitätön+A+Sg+Ill                  | mitättömhään               |
| seppä+A+Sg+Ill                    | sepphään                   |
| näpperä+A+Sg+Ill                  | näpperhään                 |
| höperä+A+Sg+Ill                   | höperhään                  |
| kiverä+A+Sg+Ill                   | kiverhään                  |
| käyrä+A+Sg+Ill                    | käyrhään                   |
| nöyrä+A+Sg+Ill                    | nöyrhään                   |
| näppärä+A+Sg+Ill                  | näppärhään                 |
| väärä+A+Sg+Ill                    | väärhään                   |
| sisä+A+Sg+Ill                     | sishään                    |
| tylsä+A+Sg+Ill                    | tylshään                   |
| käpsä+A+Sg+Ill                    | käpshään                   |
| näpsä+A+Sg+Ill                    | näpshään                   |
| löysä+A+Sg+Ill                    | löyshään                   |
| ryöttä+A+Sg+Ill                   | ryötthään                  |
| mätä+A+Sg+Ill                     | mäthään                    |
| yhđentekkeevä+A+Sg+Ill            | yhđentekkeevhään           |
| järkkeevä+A+Sg+Ill                | järkkeevhään               |
| väkkeevä+A+Sg+Ill                 | väkkeevhään                |
| lievä+A+Sg+Ill                    | lievhään                   |
| sievä+A+Sg+Ill                    | sievhään                   |
| tyhvä+A+Sg+Ill                    | tyhvhään                   |
| kärsiivä+A+Sg+Ill                 | kärsiivhään                |
| selvä+A+Sg+Ill                    | selvhään                   |
| epäselvä+A+Sg+Ill                 | epäselvhään                |
| hyvä+A+Sg+Ill                     | hyvhään                    |
| syvä+A+Sg+Ill                     | syvhään                    |
| ikävä+A+Sg+Ill                    | ikävhään                   |
| terävä+A+Sg+Ill                   | terävhään                  |
| veđenpitävä+A+Sg+Ill              | veđenpitävhään             |
| merkittävä+A+Sg+Ill               | merkittävhään              |
| syötävä+A+Sg+Ill                  | syötävhään                 |
| elläävä+A+Sg+Ill                  | elläävhään                 |
| ymmärettäävä+A+Sg+Ill             | ymmärettäävhään            |
| jännittäävä+A+Sg+Ill              | jännittäävhään             |
| kiilttäävä+A+Sg+Ill               | kiilttäävhään              |
| virkistyttäävä+A+Sg+Ill           | virkistyttäävhään          |
| pystö+A+Sg+Ill                    | pysthöön                   |
