|                                          |                             |
|------------------------------------------|-----------------------------|
| +A+Sg+Superl+Nom                         | +A+Sg+Superl+Nom            |
| oma+A+Sg+Superl+Nom                      | oma+A+Sg+Superl+Nom         |
| viimi+A+Sg+Superl+Nom                    | viimi+A+Sg+Superl+Nom       |
| turkkiisi+A+Sg+Superl+Nom                | turkkiisi+A+Sg+Superl+Nom   |
| ensi+A+Sg+Superl+Nom                     | ensi+A+Sg+Superl+Nom        |
| vaiti+A+Sg+Superl+Nom                    | vaiti+A+Sg+Superl+Nom       |
| irti+A+Sg+Superl+Nom                     | irti+A+Sg+Superl+Nom        |
| fonologinen+A+Sg+Superl+Nom              | fonologinen+A+Sg+Superl+Nom |
| paras+A+Sg+Superl+Nom                    | paras+A+Sg+Superl+Nom       |
| ohut+A+Sg+Superl+Nom                     | ohut+A+Sg+Superl+Nom        |
| ehyt+A+Sg+Superl+Nom                     | ehyt+A+Sg+Superl+Nom        |
| lyhyt+A+Sg+Superl+Nom                    | lyhyt+A+Sg+Superl+Nom       |
| ohu+A+Sg+Superl+Nom                      | ohu+A+Sg+Superl+Nom         |
| pikku+A+Sg+Superl+Nom                    | pikku+A+Sg+Superl+Nom       |
| lyhy+A+Sg+Superl+Nom                     | lyhy+A+Sg+Superl+Nom        |
| pahas+A+Sg+Superl+Nom                    | pahhain                     |
| puhelias+A+Sg+Superl+Nom                 | puhelihain                  |
| laupias+A+Sg+Superl+Nom                  | laupihain                   |
| kaikkivaltias+A+Sg+Superl+Nom            | kaikkivaltihain             |
| paljas+A+Sg+Superl+Nom                   | paljhain                    |
| voimakas+A+Sg+Superl+Nom                 | voimakkhain                 |
| rakas+A+Sg+Superl+Nom                    | rakkhain                    |
| viekas+A+Sg+Superl+Nom                   | viekkhain                   |
| onnekas+A+Sg+Superl+Nom                  | onnekkhain                  |
| raikas+A+Sg+Superl+Nom                   | raikkhain                   |
| vitamiinikas+A+Sg+Superl+Nom             | vitamiinikkhain             |
| rikas+A+Sg+Superl+Nom                    | rikkhain                    |
| raharikas+A+Sg+Superl+Nom                | raharikkhain                |
| fantasiirikas+A+Sg+Superl+Nom            | fantasiirikkhain            |
| lajirikas+A+Sg+Superl+Nom                | lajirikkhain                |
| färirikas+A+Sg+Superl+Nom                | färirikkhain                |
| tietorikas+A+Sg+Superl+Nom               | tietorikkhain               |
| sađetrikas+A+Sg+Superl+Nom               | sađetrikkhain               |
| lapsikas+A+Sg+Superl+Nom                 | lapsikkhain                 |
| praatikas+A+Sg+Superl+Nom                | praatikkhain                |
| vilkas+A+Sg+Superl+Nom                   | vilkkhain                   |
| nerokas+A+Sg+Superl+Nom                  | nerokkhain                  |
| arvokas+A+Sg+Superl+Nom                  | arvokkhain                  |
| kirkas+A+Sg+Superl+Nom                   | kirkkhain                   |
| liukas+A+Sg+Superl+Nom                   | liukkhain                   |
| raskas+A+Sg+Superl+Nom                   | raskhain                    |
| hurskas+A+Sg+Superl+Nom                  | hurskhain                   |
| vanhurskas+A+Sg+Superl+Nom               | vanhurskhain                |
| joutilas+A+Sg+Superl+Nom                 | joutilhain                  |
| armas+A+Sg+Superl+Nom                    | armhain                     |
| vapaa+A+Sg+Superl+Nom                    | vaphain                     |
| reipas+A+Sg+Superl+Nom                   | reipphain                   |
| opas+A+Sg+Superl+Nom                     | opphain                     |
| hyvä+A+Sg+Superl+Nom                     | parhain                     |
| vieras+A+Sg+Superl+Nom                   | vierhain                    |
| ventovieras+A+Sg+Superl+Nom              | ventovierhain               |
| sairas+A+Sg+Superl+Nom                   | sairhain                    |
| viisas+A+Sg+Superl+Nom                   | viishain                    |
| itteviisas+A+Sg+Superl+Nom               | itteviishain                |
| runsas+A+Sg+Superl+Nom                   | runshain                    |
| karsas+A+Sg+Superl+Nom                   | karshain                    |
| ahđas+A+Sg+Superl+Nom                    | ahthain                     |
| puhđas+A+Sg+Superl+Nom                   | puhthain                    |
| hiđas+A+Sg+Superl+Nom                    | hithain                     |
| harras+A+Sg+Superl+Nom                   | harthain                    |
| laatas+A+Sg+Superl+Nom                   | laatthain                   |
| rietas+A+Sg+Superl+Nom                   | rietthain                   |
| autuas+A+Sg+Superl+Nom                   | autuhain                    |
| raavas+A+Sg+Superl+Nom                   | raavhain                    |
| karvas+A+Sg+Superl+Nom                   | karvhain                    |
| ehhee+A+Sg+Superl+Nom                    | ehhein                      |
| ehhee+A+Sg+Superl+Nom                    | ehhein                      |
| tihhee+A+Sg+Superl+Nom                   | tihhein                     |
| tihhee+A+Sg+Superl+Nom                   | tihhein                     |
| kuolu+A+Sg+Superl+Nom                    | kuolhein                    |
| kokenu+A+Sg+Superl+Nom                   | kokenhein                   |
| ahnet+A+Sg+Superl+Nom                    | ahnhein                     |
| nainu+A+Sg+Superl+Nom                    | nainhein                    |
| tiinet+A+Sg+Superl+Nom                   | tiinhein                    |
| oppinu+A+Sg+Superl+Nom                   | oppinhein                   |
| ravistunnu+A+Sg+Superl+Nom               | ravistunnhein               |
| hermostunnu+A+Sg+Superl+Nom              | hermostunnhein              |
| hengestynny+A+Sg+Superl+Nom              | hengestynnhein              |
| hengistynny+A+Sg+Superl+Nom              | hengistynnhein              |
| vaipunu+A+Sg+Superl+Nom                  | vaipunhein                  |
| suuttunu+A+Sg+Superl+Nom                 | suuttunhein                 |
| väsyny+A+Sg+Superl+Nom                   | väsynhein                   |
| tuoret+A+Sg+Superl+Nom                   | tuorhein                    |
| ussee+A+Sg+Superl+Nom                    | ushein                      |
| ussee+A+Sg+Superl+Nom                    | ushein                      |
| kauhhee+A+Sg+Superl+Nom                  | kauhein                     |
| kauhhee+A+Sg+Superl+Nom                  | kauhein                     |
| tervet+A+Sg+Superl+Nom                   | tervhein                    |
| sakea+A+Sg+Superl+Nom                    | sakein                      |
| rohkee+A+Sg+Superl+Nom                   | rohkein                     |
| rohkee+A+Sg+Superl+Nom                   | rohkein                     |
| laakkee+A+Sg+Superl+Nom                  | laakkein                    |
| laakkee+A+Sg+Superl+Nom                  | laakkein                    |
| makkee+A+Sg+Superl+Nom                   | makkein                     |
| makkee+A+Sg+Superl+Nom                   | makkein                     |
| sakkee+A+Sg+Superl+Nom                   | sakkein                     |
| sakkee+A+Sg+Superl+Nom                   | sakkein                     |
| vaikkee+A+Sg+Superl+Nom                  | vaikkein                    |
| vaikkee+A+Sg+Superl+Nom                  | vaikkein                    |
| oikkee+A+Sg+Superl+Nom                   | oikkein                     |
| oikkee+A+Sg+Superl+Nom                   | oikkein                     |
| muikkee+A+Sg+Superl+Nom                  | muikkein                    |
| muikkee+A+Sg+Superl+Nom                  | muikkein                    |
| valkkee+A+Sg+Superl+Nom                  | valkkein                    |
| valkkee+A+Sg+Superl+Nom                  | valkkein                    |
| ilmivalkkee+A+Sg+Superl+Nom              | ilmivalkkein                |
| ilmivalkkee+A+Sg+Superl+Nom              | ilmivalkkein                |
| vitivalkkee+A+Sg+Superl+Nom              | vitivalkkein                |
| vitivalkkee+A+Sg+Superl+Nom              | vitivalkkein                |
| selkkee+A+Sg+Superl+Nom                  | selkkein                    |
| selkkee+A+Sg+Superl+Nom                  | selkkein                    |
| ilkkee+A+Sg+Superl+Nom                   | ilkkein                     |
| ilkkee+A+Sg+Superl+Nom                   | ilkkein                     |
| sokkee+A+Sg+Superl+Nom                   | sokkein                     |
| sokkee+A+Sg+Superl+Nom                   | sokkein                     |
| huokkee+A+Sg+Superl+Nom                  | huokkein                    |
| huokkee+A+Sg+Superl+Nom                  | huokkein                    |
| karkkee+A+Sg+Superl+Nom                  | karkkein                    |
| karkkee+A+Sg+Superl+Nom                  | karkkein                    |
| korkkee+A+Sg+Superl+Nom                  | korkkein                    |
| korkkee+A+Sg+Superl+Nom                  | korkkein                    |
| tärkkee+A+Sg+Superl+Nom                  | tärkkein                    |
| tärkkee+A+Sg+Superl+Nom                  | tärkkein                    |
| aukkee+A+Sg+Superl+Nom                   | aukkein                     |
| aukkee+A+Sg+Superl+Nom                   | aukkein                     |
| laukkee+A+Sg+Superl+Nom                  | laukkein                    |
| laukkee+A+Sg+Superl+Nom                  | laukkein                    |
| korkea+A+Sg+Superl+Nom                   | korkein                     |
| ruskea+A+Sg+Superl+Nom                   | ruskein                     |
| ruskee+A+Sg+Superl+Nom                   | ruskein                     |
| ruskee+A+Sg+Superl+Nom                   | ruskein                     |
| sitkee+A+Sg+Superl+Nom                   | sitkein                     |
| sitkee+A+Sg+Superl+Nom                   | sitkein                     |
| notkee+A+Sg+Superl+Nom                   | notkein                     |
| notkee+A+Sg+Superl+Nom                   | notkein                     |
| haalee+A+Sg+Superl+Nom                   | haalein                     |
| haalee+A+Sg+Superl+Nom                   | haalein                     |
| vaalee+A+Sg+Superl+Nom                   | vaalein                     |
| vaalee+A+Sg+Superl+Nom                   | vaalein                     |
| haalee+A+Sg+Superl+Nom                   | hallein                     |
| haalee+A+Sg+Superl+Nom                   | hallein                     |
| sillee+A+Sg+Superl+Nom                   | sillein                     |
| sillee+A+Sg+Superl+Nom                   | sillein                     |
| pehmee+A+Sg+Superl+Nom                   | pehmein                     |
| pehmee+A+Sg+Superl+Nom                   | pehmein                     |
| himmee+A+Sg+Superl+Nom                   | himmein                     |
| himmee+A+Sg+Superl+Nom                   | himmein                     |
| pimmee+A+Sg+Superl+Nom                   | pimmein                     |
| pimmee+A+Sg+Superl+Nom                   | pimmein                     |
| pilkkapimmee+A+Sg+Superl+Nom             | pilkkapimmein               |
| pilkkapimmee+A+Sg+Superl+Nom             | pilkkapimmein               |
| säkkipimmee+A+Sg+Superl+Nom              | säkkipimmein                |
| säkkipimmee+A+Sg+Superl+Nom              | säkkipimmein                |
| syyspimmee+A+Sg+Superl+Nom               | syyspimmein                 |
| syyspimmee+A+Sg+Superl+Nom               | syyspimmein                 |
| kommee+A+Sg+Superl+Nom                   | kommein                     |
| kommee+A+Sg+Superl+Nom                   | kommein                     |
| kirmee+A+Sg+Superl+Nom                   | kirmein                     |
| kirmee+A+Sg+Superl+Nom                   | kirmein                     |
| ahnee+A+Sg+Superl+Nom                    | ahnein                      |
| ahnee+A+Sg+Superl+Nom                    | ahnein                      |
| kappee+A+Sg+Superl+Nom                   | kappein                     |
| kappee+A+Sg+Superl+Nom                   | kappein                     |
| rappee+A+Sg+Superl+Nom                   | rappein                     |
| rappee+A+Sg+Superl+Nom                   | rappein                     |
| lieppee+A+Sg+Superl+Nom                  | lieppein                    |
| lieppee+A+Sg+Superl+Nom                  | lieppein                    |
| kippee+A+Sg+Superl+Nom                   | kippein                     |
| kippee+A+Sg+Superl+Nom                   | kippein                     |
| merikippee+A+Sg+Superl+Nom               | merikippein                 |
| merikippee+A+Sg+Superl+Nom               | merikippein                 |
| ylppee+A+Sg+Superl+Nom                   | ylppein                     |
| ylppee+A+Sg+Superl+Nom                   | ylppein                     |
| noppee+A+Sg+Superl+Nom                   | noppein                     |
| noppee+A+Sg+Superl+Nom                   | noppein                     |
| virree+A+Sg+Superl+Nom                   | virrein                     |
| virree+A+Sg+Superl+Nom                   | virrein                     |
| korree+A+Sg+Superl+Nom                   | korrein                     |
| korree+A+Sg+Superl+Nom                   | korrein                     |
| murree+A+Sg+Superl+Nom                   | murrein                     |
| murree+A+Sg+Superl+Nom                   | murrein                     |
| pyöree+A+Sg+Superl+Nom                   | pyörein                     |
| pyöree+A+Sg+Superl+Nom                   | pyörein                     |
| kalssee+A+Sg+Superl+Nom                  | kalssein                    |
| kalssee+A+Sg+Superl+Nom                  | kalssein                    |
| kostee+A+Sg+Superl+Nom                   | kostein                     |
| kostee+A+Sg+Superl+Nom                   | kostein                     |
| laattee+A+Sg+Superl+Nom                  | laattein                    |
| laattee+A+Sg+Superl+Nom                  | laattein                    |
| kiinttee+A+Sg+Superl+Nom                 | kiinttein                   |
| kiinttee+A+Sg+Superl+Nom                 | kiinttein                   |
| hirvee+A+Sg+Superl+Nom                   | hirvein                     |
| hirvee+A+Sg+Superl+Nom                   | hirvein                     |
| kevvee+A+Sg+Superl+Nom                   | kevvein                     |
| kevvee+A+Sg+Superl+Nom                   | kevvein                     |
| levvee+A+Sg+Superl+Nom                   | levvein                     |
| levvee+A+Sg+Superl+Nom                   | levvein                     |
| oranši+A+Sg+Superl+Nom                   | oranšiin                    |
| paha+A+Sg+Superl+Nom                     | pahhiin                     |
| pyhä+A+Sg+Superl+Nom                     | pyhhiin                     |
| vähä+A+Sg+Superl+Nom                     | vähhiin                     |
| laiha+A+Sg+Superl+Nom                    | laihiin                     |
| kallis+A+Sg+Superl+Nom                   | kallhiin                    |
| valmis+A+Sg+Superl+Nom                   | valmhiin                    |
| vanhaa+A+Sg+Superl+Nom                   | vanhiin                     |
| kaunis+A+Sg+Superl+Nom                   | kaunhiin                    |
| turha+A+Sg+Superl+Nom                    | turhiin                     |
| tyyris+A+Sg+Superl+Nom                   | tyyrhiin                    |
| raitis+A+Sg+Superl+Nom                   | raitthiin                   |
| lauha+A+Sg+Superl+Nom                    | lauhiin                     |
| tivis+A+Sg+Superl+Nom                    | tivhiin                     |
| tyyhä+A+Sg+Superl+Nom                    | tyyhiin                     |
| köyhä+A+Sg+Superl+Nom                    | köyhiin                     |
| löyhä+A+Sg+Superl+Nom                    | löyhiin                     |
| laaja+A+Sg+Superl+Nom                    | laajiin                     |
| harmaaja+A+Sg+Superl+Nom                 | harmaajiin                  |
| hoppeeharmaaja+A+Sg+Superl+Nom           | hoppeeharmaajiin            |
| taaja+A+Sg+Superl+Nom                    | taajiin                     |
| tyhjä+A+Sg+Superl+Nom                    | tyhjiin                     |
| luja+A+Sg+Superl+Nom                     | lujjiin                     |
| väljä+A+Sg+Superl+Nom                    | väljiin                     |
| hurja+A+Sg+Superl+Nom                    | hurjiin                     |
| kurja+A+Sg+Superl+Nom                    | kurjiin                     |
| raaka+A+Sg+Superl+Nom                    | raakkiin                    |
| fakki+A+Sg+Superl+Nom                    | fakkiin                     |
| liika+A+Sg+Superl+Nom                    | liikkiin                    |
| hoikka+A+Sg+Superl+Nom                   | hoikkiin                    |
| pelkkä+A+Sg+Superl+Nom                   | pelkkiin                    |
| plankki+A+Sg+Superl+Nom                  | plankkiin                   |
| vankka+A+Sg+Superl+Nom                   | vankkiin                    |
| flinkki+A+Sg+Superl+Nom                  | flinkkiin                   |
| synkkä+A+Sg+Superl+Nom                   | synkkiin                    |
| tarkka+A+Sg+Superl+Nom                   | tarkkiin                    |
| herkkä+A+Sg+Superl+Nom                   | herkkiin                    |
| jyrkkä+A+Sg+Superl+Nom                   | jyrkkiin                    |
| nyrkkä+A+Sg+Superl+Nom                   | nyrkkiin                    |
| märkä+A+Sg+Superl+Nom                    | märkkiin                    |
| läpimärkä+A+Sg+Superl+Nom                | läpimärkkiin                |
| tiukka+A+Sg+Superl+Nom                   | tiukkiin                    |
| soukka+A+Sg+Superl+Nom                   | soukkiin                    |
| nuuka+A+Sg+Superl+Nom                    | nuukkiin                    |
| mykkä+A+Sg+Superl+Nom                    | mykkiin                     |
| arka+A+Sg+Superl+Nom                     | arkiin                      |
| pimmeenarka+A+Sg+Superl+Nom              | pimmeenarkiin               |
| laiska+A+Sg+Superl+Nom                   | laiskiin                    |
| härski+A+Sg+Superl+Nom                   | härskiin                    |
| hauska+A+Sg+Superl+Nom                   | hauskiin                    |
| ratikaali+A+Sg+Superl+Nom                | ratikaaliin                 |
| normaali+A+Sg+Superl+Nom                 | normaaliin                  |
| rekiunaali+A+Sg+Superl+Nom               | rekiunaaliin                |
| liberaali+A+Sg+Superl+Nom                | liberaaliin                 |
| sentraali+A+Sg+Superl+Nom                | sentraaliin                 |
| hankala+A+Sg+Superl+Nom                  | hankaliin                   |
| kamala+A+Sg+Superl+Nom                   | kamaliin                    |
| matala+A+Sg+Superl+Nom                   | mataliin                    |
| kavala+A+Sg+Superl+Nom                   | kavaliin                    |
| happela+A+Sg+Superl+Nom                  | happeliin                   |
| simppeli+A+Sg+Superl+Nom                 | simppeliin                  |
| passeli+A+Sg+Superl+Nom                  | passeliin                   |
| ytelä+A+Sg+Superl+Nom                    | yteliin                     |
| siila+A+Sg+Superl+Nom                    | siiliin                     |
| villi+A+Sg+Superl+Nom                    | villiin                     |
| sula+A+Sg+Superl+Nom                     | sulliin                     |
| puoli+A+Sg+Superl+Nom                    | puoliin                     |
| puoli+A+Sg+Superl+Nom                    | puoliin                     |
| käsipuoli+A+Sg+Superl+Nom                | käsipuoliin                 |
| käsipuoli+A+Sg+Superl+Nom                | käsipuoliin                 |
| silmäpuoli+A+Sg+Superl+Nom               | silmäpuoliin                |
| silmäpuoli+A+Sg+Superl+Nom               | silmäpuoliin                |
| hööli+A+Sg+Superl+Nom                    | hööliin                     |
| veđenpillaama+A+Sg+Superl+Nom            | veđenpillaamiin             |
| hapan+A+Sg+Superl+Nom                    | happamiin                   |
| ulosantama+A+Sg+Superl+Nom               | ulosantamiin                |
| vasen+A+Sg+Superl+Nom                    | vasemiin                    |
| tyhmä+A+Sg+Superl+Nom                    | tyhmiin                     |
| parhain+A+Sg+Superl+Nom                  | parhaimiin                  |
| lämmin+A+Sg+Superl+Nom                   | lämpimiin                   |
| kylmä+A+Sg+Superl+Nom                    | kylmiin                     |
| jääkylmä+A+Sg+Superl+Nom                 | jääkylmiin                  |
| lama+A+Sg+Superl+Nom                     | lammiin                     |
| himmi+A+Sg+Superl+Nom                    | himmiin                     |
| soma+A+Sg+Superl+Nom                     | sommiin                     |
| alaston+A+Sg+Superl+Nom                  | alastommiin                 |
| rauhaton+A+Sg+Superl+Nom                 | rauhattommiin               |
| viaton+A+Sg+Superl+Nom                   | viattommiin                 |
| rajaton+A+Sg+Superl+Nom                  | rajattommiin                |
| pohjaton+A+Sg+Superl+Nom                 | pohjattommiin               |
| vijaton+A+Sg+Superl+Nom                  | vijattommiin                |
| saamaton+A+Sg+Superl+Nom                 | saamattommiin               |
| tottelematon+A+Sg+Superl+Nom             | tottelemattommiin           |
| naimaton+A+Sg+Superl+Nom                 | naimattommiin               |
| herraton+A+Sg+Superl+Nom                 | herrattommiin               |
| luvaton+A+Sg+Superl+Nom                  | luvattommiin                |
| toimeton+A+Sg+Superl+Nom                 | toimettommiin               |
| onneton+A+Sg+Superl+Nom                  | onnettommiin                |
| ruokoton+A+Sg+Superl+Nom                 | ruokottommiin               |
| uskoton+A+Sg+Superl+Nom                  | uskottommiin                |
| armoton+A+Sg+Superl+Nom                  | armottommiin                |
| painoton+A+Sg+Superl+Nom                 | painottommiin               |
| levoton+A+Sg+Superl+Nom                  | levottommiin                |
| kelvoton+A+Sg+Superl+Nom                 | kelvottommiin               |
| arvoton+A+Sg+Superl+Nom                  | arvottommiin                |
| mahđoton+A+Sg+Superl+Nom                 | mahđottommiin               |
| loputon+A+Sg+Superl+Nom                  | loputtommiin                |
| suruton+A+Sg+Superl+Nom                  | suruttommiin                |
| avuton+A+Sg+Superl+Nom                   | avuttommiin                 |
| mavuton+A+Sg+Superl+Nom                  | mavuttommiin                |
| kumma+A+Sg+Superl+Nom                    | kummiin                     |
| ruma+A+Sg+Superl+Nom                     | rummiin                     |
| tumma+A+Sg+Superl+Nom                    | tummiin                     |
| hengetön+A+Sg+Superl+Nom                 | hengettömmiin               |
| äänetön+A+Sg+Superl+Nom                  | äänettömmiin                |
| pilvetön+A+Sg+Superl+Nom                 | pilvettömmiin               |
| färitön+A+Sg+Superl+Nom                  | färittömmiin                |
| hävitön+A+Sg+Superl+Nom                  | hävittömmiin                |
| hävytön+A+Sg+Superl+Nom                  | hävyttömmiin                |
| kykenemätön+A+Sg+Superl+Nom              | kykenemättömmiin            |
| ymmärtämätön+A+Sg+Superl+Nom             | ymmärtämättömmiin           |
| määrätön+A+Sg+Superl+Nom                 | määrättömmiin               |
| mitätön+A+Sg+Superl+Nom                  | mitättömmiin                |
| jumalaton+A+Sg+Superl+Nom                | jumalattomiin               |
| vallaton+A+Sg+Superl+Nom                 | vallattomiin                |
| mittaamaton+A+Sg+Superl+Nom              | mittaamattomiin             |
| maksamaton+A+Sg+Superl+Nom               | maksamattomiin              |
| perhäänantamaton+A+Sg+Superl+Nom         | perhäänantamattomiin        |
| paistamaton+A+Sg+Superl+Nom              | paistamattomiin             |
| luottamaton+A+Sg+Superl+Nom              | luottamattomiin             |
| ajattelematon+A+Sg+Superl+Nom            | ajattelemattomiin           |
| vaihettelematon+A+Sg+Superl+Nom          | vaihettelemattomiin         |
| valettelematon+A+Sg+Superl+Nom           | valettelemattomiin          |
| olematon+A+Sg+Superl+Nom                 | olemattomiin                |
| tuntematon+A+Sg+Superl+Nom               | tuntemattomiin              |
| huolimaton+A+Sg+Superl+Nom               | huolimattomiin              |
| oppimaton+A+Sg+Superl+Nom                | oppimattomiin               |
| vaatimaton+A+Sg+Superl+Nom               | vaatimattomiin              |
| uskomaton+A+Sg+Superl+Nom                | uskomattomiin               |
| liikkumaton+A+Sg+Superl+Nom              | liikkumattomiin             |
| taipumaton+A+Sg+Superl+Nom               | taipumattomiin              |
| loppumaton+A+Sg+Superl+Nom               | loppumattomiin              |
| muuttumaton+A+Sg+Superl+Nom              | muuttumattomiin             |
| varma+A+Sg+Superl+Nom                    | varmiin                     |
| epävarma+A+Sg+Superl+Nom                 | epävarmiin                  |
| kuuma+A+Sg+Superl+Nom                    | kuumiin                     |
| kärsimätön+A+Sg+Superl+Nom               | kärsimättömiin              |
| näkymätön+A+Sg+Superl+Nom                | näkymättömiin               |
| tietämätön+A+Sg+Superl+Nom               | tietämättömiin              |
| välttämätön+A+Sg+Superl+Nom              | välttämättömiin             |
| ihana+A+Sg+Superl+Nom                    | ihaniin                     |
| pieni+A+Sg+Superl+Nom                    | pieniin                     |
| pieni+A+Sg+Superl+Nom                    | pieniin                     |
| tyven+A+Sg+Superl+Nom                    | tyveniin                    |
| tinatyven+A+Sg+Superl+Nom                | tinatyveniin                |
| kleini+A+Sg+Superl+Nom                   | kleiniin                    |
| fiini+A+Sg+Superl+Nom                    | fiiniin                     |
| moni+A+Sg+Superl+Nom                     | moniin                      |
| pruuni+A+Sg+Superl+Nom                   | pruuniin                    |
| seppä+A+Sg+Superl+Nom                    | seppiin                     |
| halpa+A+Sg+Superl+Nom                    | halppiin                    |
| umpi+A+Sg+Superl+Nom                     | umppiin                     |
| klaari+A+Sg+Superl+Nom                   | klaariin                    |
| naakkari+A+Sg+Superl+Nom                 | naakkariin                  |
| sikkari+A+Sg+Superl+Nom                  | sikkariin                   |
| ankara+A+Sg+Superl+Nom                   | ankariin                    |
| tieđonankara+A+Sg+Superl+Nom             | tieđonankariin              |
| ahkera+A+Sg+Superl+Nom                   | ahkeriin                    |
| näpperä+A+Sg+Superl+Nom                  | näpperiin                   |
| höperä+A+Sg+Superl+Nom                   | höperiin                    |
| uuttera+A+Sg+Superl+Nom                  | uutteriin                   |
| kiverä+A+Sg+Superl+Nom                   | kiveriin                    |
| nuori+A+Sg+Superl+Nom                    | nuoriin                     |
| nuori+A+Sg+Superl+Nom                    | nuoriin                     |
| suora+A+Sg+Superl+Nom                    | suoriin                     |
| pystösuora+A+Sg+Superl+Nom               | pystösuoriin                |
| eri+A+Sg+Superl+Nom                      | erriin                      |
| saura+A+Sg+Superl+Nom                    | sauriin                     |
| kippura+A+Sg+Superl+Nom                  | kippuriin                   |
| suuri+A+Sg+Superl+Nom                    | suuriin                     |
| suuri+A+Sg+Superl+Nom                    | suuriin                     |
| käyrä+A+Sg+Superl+Nom                    | käyriin                     |
| nöyrä+A+Sg+Superl+Nom                    | nöyriin                     |
| näppärä+A+Sg+Superl+Nom                  | näppäriin                   |
| primääri+A+Sg+Superl+Nom                 | primääriin                  |
| väärä+A+Sg+Superl+Nom                    | vääriin                     |
| veres+A+Sg+Superl+Nom                    | vereksiin                   |
| oransi+A+Sg+Superl+Nom                   | oransiin                    |
| käpsä+A+Sg+Superl+Nom                    | käpsiin                     |
| näpsä+A+Sg+Superl+Nom                    | näpsiin                     |
| vihanen+A+Sg+Superl+Nom                  | vihassiin                   |
| samanaikhanen+A+Sg+Superl+Nom            | samanaikhassiin             |
| uuđenaikhanen+A+Sg+Superl+Nom            | uuđenaikhassiin             |
| nykyaikhanen+A+Sg+Superl+Nom             | nykyaikhassiin              |
| tuhanen+A+Sg+Superl+Nom                  | tuhassiin                   |
| pohjanen+A+Sg+Superl+Nom                 | pohjassiin                  |
| sekanen+A+Sg+Superl+Nom                  | sekassiin                   |
| hoikkanen+A+Sg+Superl+Nom                | hoikkassiin                 |
| kukkanen+A+Sg+Superl+Nom                 | kukkassiin                  |
| mukkanen+A+Sg+Superl+Nom                 | mukkassiin                  |
| tummatukkanen+A+Sg+Superl+Nom            | tummatukkassiin             |
| pitkäjalkanen+A+Sg+Superl+Nom            | pitkäjalkassiin             |
| lokanen+A+Sg+Superl+Nom                  | lokassiin                   |
| neljennuskanen+A+Sg+Superl+Nom           | neljennuskassiin            |
| salanen+A+Sg+Superl+Nom                  | salassiin                   |
| kiimanen+A+Sg+Superl+Nom                 | kiimassiin                  |
| ylivoimanen+A+Sg+Superl+Nom              | ylivoimassiin               |
| punanen+A+Sg+Superl+Nom                  | punassiin                   |
| vaaleepunanen+A+Sg+Superl+Nom            | vaaleepunassiin             |
| aniliinipunanen+A+Sg+Superl+Nom          | aniliinipunassiin           |
| vähävoipanen+A+Sg+Superl+Nom             | vähävoipassiin              |
| tasanen+A+Sg+Superl+Nom                  | tasassiin                   |
| kaitanen+A+Sg+Superl+Nom                 | kaitassiin                  |
| keltainen+A+Sg+Superl+Nom                | keltassiin                  |
| puolihintanen+A+Sg+Superl+Nom            | puolihintassiin             |
| monikertanen+A+Sg+Superl+Nom             | monikertassiin              |
| yksinkertanen+A+Sg+Superl+Nom            | yksinkertassiin             |
| vihainen+A+Sg+Superl+Nom                 | vihaissiin                  |
| vanhaanaikhainen+A+Sg+Superl+Nom         | vanhaanaikhaissiin          |
| samanaikhainen+A+Sg+Superl+Nom           | samanaikhaissiin            |
| uuđenaikhainen+A+Sg+Superl+Nom           | uuđenaikhaissiin            |
| nykyaikhainen+A+Sg+Superl+Nom            | nykyaikhaissiin             |
| pitkäaikhainen+A+Sg+Superl+Nom           | pitkäaikhaissiin            |
| kaukhainen+A+Sg+Superl+Nom               | kaukhaissiin                |
| alhainen+A+Sg+Superl+Nom                 | alhaissiin                  |
| salhainen+A+Sg+Superl+Nom                | salhaissiin                 |
| eriskumhainen+A+Sg+Superl+Nom            | eriskumhaissiin             |
| varhainen+A+Sg+Superl+Nom                | varhaissiin                 |
| aijankohthainen+A+Sg+Superl+Nom          | aijankohthaissiin           |
| pohjainen+A+Sg+Superl+Nom                | pohjaissiin                 |
| hiljainen+A+Sg+Superl+Nom                | hiljaissiin                 |
| sekainen+A+Sg+Superl+Nom                 | sekaissiin                  |
| väliaikainen+A+Sg+Superl+Nom             | väliaikaissiin              |
| likainen+A+Sg+Superl+Nom                 | likaissiin                  |
| nollapaikkainen+A+Sg+Superl+Nom          | nollapaikkaissiin           |
| kolmipaikkainen+A+Sg+Superl+Nom          | kolmipaikkaissiin           |
| kaksipaikkainen+A+Sg+Superl+Nom          | kaksipaikkaissiin           |
| yksipaikkainen+A+Sg+Superl+Nom           | yksipaikkaissiin            |
| tummatukkainen+A+Sg+Superl+Nom           | tummatukkaissiin            |
| neljenjalkainen+A+Sg+Superl+Nom          | neljenjalkaissiin           |
| pitkäjalkainen+A+Sg+Superl+Nom           | pitkäjalkaissiin            |
| vastahankainen+A+Sg+Superl+Nom           | vastahankaissiin            |
| kaksirankainen+A+Sg+Superl+Nom           | kaksirankaissiin            |
| yksirankainen+A+Sg+Superl+Nom            | yksirankaissiin             |
| konsonanttirankainen+A+Sg+Superl+Nom     | konsonanttirankaissiin      |
| lokainen+A+Sg+Superl+Nom                 | lokaissiin                  |
| paskainen+A+Sg+Superl+Nom                | paskaissiin                 |
| nelinuskainen+A+Sg+Superl+Nom            | nelinuskaissiin             |
| puskainen+A+Sg+Superl+Nom                | puskaissiin                 |
| latuskainen+A+Sg+Superl+Nom              | latuskaissiin               |
| ohukainen+A+Sg+Superl+Nom                | ohukaissiin                 |
| korkukainen+A+Sg+Superl+Nom              | korkukaissiin               |
| oikkeuđenmukainen+A+Sg+Superl+Nom        | oikkeuđenmukaissiin         |
| reekelinmukainen+A+Sg+Superl+Nom         | reekelinmukaissiin          |
| epäreekelinmukainen+A+Sg+Superl+Nom      | epäreekelinmukaissiin       |
| suurukainen+A+Sg+Superl+Nom              | suurukaissiin               |
| pitukainen+A+Sg+Superl+Nom               | pitukaissiin                |
| maalainen+A+Sg+Superl+Nom                | maalaissiin                 |
| ulkomaalainen+A+Sg+Superl+Nom            | ulkomaalaissiin             |
| ruijalainen+A+Sg+Superl+Nom              | ruijalaissiin               |
| talosvankkalainen+A+Sg+Superl+Nom        | talosvankkalaissiin         |
| jokalainen+A+Sg+Superl+Nom               | jokalaissiin                |
| tuiskalainen+A+Sg+Superl+Nom             | tuiskalaissiin              |
| tanskalainen+A+Sg+Superl+Nom             | tanskalaissiin              |
| roomalainen+A+Sg+Superl+Nom              | roomalaissiin               |
| suomalainen+A+Sg+Superl+Nom              | suomalaissiin               |
| norjalais-suomalainen+A+Sg+Superl+Nom    | norjalais-suomalaissiin     |
| suursuomalainen+A+Sg+Superl+Nom          | suursuomalaissiin           |
| salainen+A+Sg+Superl+Nom                 | salaissiin                  |
| saksalainen+A+Sg+Superl+Nom              | saksalaissiin               |
| tromssalainen+A+Sg+Superl+Nom            | tromssalaissiin             |
| ruottalainen+A+Sg+Superl+Nom             | ruottalaissiin              |
| juutalainen+A+Sg+Superl+Nom              | juutalaissiin               |
| vesisaarelainen+A+Sg+Superl+Nom          | vesisaarelaissiin           |
| pyssyjokilainen+A+Sg+Superl+Nom          | pyssyjokilaissiin           |
| puolilainen+A+Sg+Superl+Nom              | puolilaissiin               |
| saamilainen+A+Sg+Superl+Nom              | saamilaissiin               |
| erilainen+A+Sg+Superl+Nom                | erilaissiin                 |
| evankeelis-lutherilainen+A+Sg+Superl+Nom | evankeelis-lutherilaissiin  |
| suomalais-ugrilainen+A+Sg+Superl+Nom     | suomalais-ugrilaissiin      |
| raisilainen+A+Sg+Superl+Nom              | raisilaissiin               |
| englantilainen+A+Sg+Superl+Nom           | englantilaissiin            |
| hollantilainen+A+Sg+Superl+Nom           | hollantilaissiin            |
| paavilainen+A+Sg+Superl+Nom              | paavilaissiin               |
| villainen+A+Sg+Superl+Nom                | villaissiin                 |
| tällainen+A+Sg+Superl+Nom                | tällaissiin                 |
| samanlainen+A+Sg+Superl+Nom              | samanlaissiin               |
| muutamanlainen+A+Sg+Superl+Nom           | muutamanlaissiin            |
| kaikenlainen+A+Sg+Superl+Nom             | kaikenlaissiin              |
| pienenlainen+A+Sg+Superl+Nom             | pienenlaissiin              |
| monenlainen+A+Sg+Superl+Nom              | monenlaissiin               |
| nuorenlainen+A+Sg+Superl+Nom             | nuorenlaissiin              |
| senlainen+A+Sg+Superl+Nom                | senlaissiin                 |
| toisenlainen+A+Sg+Superl+Nom             | toisenlaissiin              |
| kahđenlainen+A+Sg+Superl+Nom             | kahđenlaissiin              |
| yhđenlainen+A+Sg+Superl+Nom              | yhđenlaissiin               |
| tyyrhinlainen+A+Sg+Superl+Nom            | tyyrhinlaissiin             |
| isonlainen+A+Sg+Superl+Nom               | isonlaissiin                |
| tämänlainen+A+Sg+Superl+Nom              | tämänlaissiin               |
| höperänlainen+A+Sg+Superl+Nom            | höperänlaissiin             |
| vanholainen+A+Sg+Superl+Nom              | vanholaissiin               |
| lestadiolainen+A+Sg+Superl+Nom           | lestadiolaissiin            |
| torniolainen+A+Sg+Superl+Nom             | torniolaissiin              |
| vanholaislestaatiolainen+A+Sg+Superl+Nom | vanholaislestaatiolaissiin  |
| alattiolainen+A+Sg+Superl+Nom            | alattiolaissiin             |
| tornionlaksolainen+A+Sg+Superl+Nom       | tornionlaksolaissiin        |
| suolainen+A+Sg+Superl+Nom                | suolaissiin                 |
| tuolainen+A+Sg+Superl+Nom                | tuolaissiin                 |
| savolainen+A+Sg+Superl+Nom               | savolaissiin                |
| jonkulainen+A+Sg+Superl+Nom              | jonkulaissiin               |
| kainulainen+A+Sg+Superl+Nom              | kainulaissiin               |
| vestakainulainen+A+Sg+Superl+Nom         | vestakainulaissiin          |
| minkälainen+A+Sg+Superl+Nom              | minkälaissiin               |
| kiimainen+A+Sg+Superl+Nom                | kiimaissiin                 |
| alimainen+A+Sg+Superl+Nom                | alimaissiin                 |
| ylivoimainen+A+Sg+Superl+Nom             | ylivoimaissiin              |
| ulomainen+A+Sg+Superl+Nom                | ulomaissiin                 |
| etumainen+A+Sg+Superl+Nom                | etumaissiin                 |
| yksituumainen+A+Sg+Superl+Nom            | yksituumaissiin             |
| hajanainen+A+Sg+Superl+Nom               | hajanaissiin                |
| vähäsanainen+A+Sg+Superl+Nom             | vähäsanaissiin              |
| aukinainen+A+Sg+Superl+Nom               | aukinaissiin                |
| harvinainen+A+Sg+Superl+Nom              | harvinaissiin               |
| kokonainen+A+Sg+Superl+Nom               | kokonaissiin                |
| punainen+A+Sg+Superl+Nom                 | punaissiin                  |
| vaaleepunainen+A+Sg+Superl+Nom           | vaaleepunaissiin            |
| aniliinipunainen+A+Sg+Superl+Nom         | aniliinipunaissiin          |
| ruusunpunainen+A+Sg+Superl+Nom           | ruusunpunaissiin            |
| vähävoipainen+A+Sg+Superl+Nom            | vähävoipaissiin             |
| pikkurainen+A+Sg+Superl+Nom              | pikkuraissiin               |
| tasainen+A+Sg+Superl+Nom                 | tasaissiin                  |
| epätasainen+A+Sg+Superl+Nom              | epätasaissiin               |
| hietainen+A+Sg+Superl+Nom                | hietaissiin                 |
| kaitainen+A+Sg+Superl+Nom                | kaitaissiin                 |
| ristiraitainen+A+Sg+Superl+Nom           | ristiraitaissiin            |
| väkivaltainen+A+Sg+Superl+Nom            | väkivaltaissiin             |
| keltainen+A+Sg+Superl+Nom                | keltaissiin                 |
| punaisenkeltainen+A+Sg+Superl+Nom        | punaisenkeltaissiin         |
| puolihintainen+A+Sg+Superl+Nom           | puolihintaissiin            |
| monikertainen+A+Sg+Superl+Nom            | monikertaissiin             |
| monenkertainen+A+Sg+Superl+Nom           | monenkertaissiin            |
| kahđenkertainen+A+Sg+Superl+Nom          | kahđenkertaissiin           |
| yhđenkertainen+A+Sg+Superl+Nom           | yhđenkertaissiin            |
| yksinkertainen+A+Sg+Superl+Nom           | yksinkertaissiin            |
| virtainen+A+Sg+Superl+Nom                | virtaissiin                 |
| vestainen+A+Sg+Superl+Nom                | vestaissiin                 |
| luottavainen+A+Sg+Superl+Nom             | luottavaissiin              |
| vaivainen+A+Sg+Superl+Nom                | vaivaissiin                 |
| uskovainen+A+Sg+Superl+Nom               | uskovaissiin                |
| varovainen+A+Sg+Superl+Nom               | varovaissiin                |
| karvainen+A+Sg+Superl+Nom                | karvaissiin                 |
| rasvainen+A+Sg+Superl+Nom                | rasvaissiin                 |
| likheinen+A+Sg+Superl+Nom                | likheissiin                 |
| melkheinen+A+Sg+Superl+Nom               | melkheissiin                |
| ylheinen+A+Sg+Superl+Nom                 | ylheissiin                  |
| yhtheinen+A+Sg+Superl+Nom                | yhtheissiin                 |
| myöntheinen+A+Sg+Superl+Nom              | myöntheissiin               |
| auringonpaistheinen+A+Sg+Superl+Nom      | auringonpaistheissiin       |
| fonoginen+A+Sg+Superl+Nom                | fonologissiin               |
| morfofonologinen+A+Sg+Superl+Nom         | morfofonologissiin          |
| biolooginen+A+Sg+Superl+Nom              | bioloogissiin               |
| psykolooginen+A+Sg+Superl+Nom            | psykoloogissiin             |
| ökolooginen+A+Sg+Superl+Nom              | ökoloogissiin               |
| vierhiinen+A+Sg+Superl+Nom               | vierhiissiin                |
| produktiivinen+A+Sg+Superl+Nom           | produktiissiin              |
| iänkaikkinen+A+Sg+Superl+Nom             | iänkaikkissiin              |
| piikkinen+A+Sg+Superl+Nom                | piikkissiin                 |
| pahanilkinen+A+Sg+Superl+Nom             | pahanilkissiin              |
| nokinen+A+Sg+Superl+Nom                  | nokissiin                   |
| modaalinen+A+Sg+Superl+Nom               | modaalissiin                |
| sosiaalinen+A+Sg+Superl+Nom              | sosiaalissiin               |
| lyhykäisvokaalinen+A+Sg+Superl+Nom       | lyhykäisvokaalissiin        |
| maalinen+A+Sg+Superl+Nom                 | maalissiin                  |
| tradittiinaalinen+A+Sg+Superl+Nom        | tradittiinaalissiin         |
| pluraalinen+A+Sg+Superl+Nom              | pluraalissiin               |
| digitaalinen+A+Sg+Superl+Nom             | digitaalissiin              |
| aspektuaalinen+A+Sg+Superl+Nom           | aspektuaalissiin            |
| rauhalinen+A+Sg+Superl+Nom               | rauhalissiin                |
| histoorialinen+A+Sg+Superl+Nom           | histoorialissiin            |
| historialinen+A+Sg+Superl+Nom            | historialissiin             |
| paikalinen+A+Sg+Superl+Nom               | paikalissiin                |
| kummalinen+A+Sg+Superl+Nom               | kummalissiin                |
| vaaralinen+A+Sg+Superl+Nom               | vaaralissiin                |
| viralinen+A+Sg+Superl+Nom                | viralissiin                 |
| kansalinen+A+Sg+Superl+Nom               | kansalissiin                |
| osalinen+A+Sg+Superl+Nom                 | osalissiin                  |
| tavalinen+A+Sg+Superl+Nom                | tavalissiin                 |
| epätavalinen+A+Sg+Superl+Nom             | epätavalissiin              |
| turvalinen+A+Sg+Superl+Nom               | turvalissiin                |
| luvalinen+A+Sg+Superl+Nom                | luvalissiin                 |
| raiđalinen+A+Sg+Superl+Nom               | raiđalissiin                |
| tarpheelinen+A+Sg+Superl+Nom             | tarpheelissiin              |
| murheelinen+A+Sg+Superl+Nom              | murheelissiin               |
| katheelinen+A+Sg+Superl+Nom              | katheelissiin               |
| satheelinen+A+Sg+Superl+Nom              | satheelissiin               |
| puutheelinen+A+Sg+Superl+Nom             | puutheelissiin              |
| tervheelinen+A+Sg+Superl+Nom             | tervheelissiin              |
| hengelinen+A+Sg+Superl+Nom               | hengelissiin                |
| rehelinen+A+Sg+Superl+Nom                | rehelissiin                 |
| kolmikielinen+A+Sg+Superl+Nom            | kolmikielissiin             |
| kaksikielinen+A+Sg+Superl+Nom            | kaksikielissiin             |
| suomenkielinen+A+Sg+Superl+Nom           | suomenkielissiin            |
| kainunkielinen+A+Sg+Superl+Nom           | kainunkielissiin            |
| ylimielinen+A+Sg+Superl+Nom              | ylimielissiin               |
| yksmielinen+A+Sg+Superl+Nom              | yksmielissiin               |
| onnelinen+A+Sg+Superl+Nom                | onnelissiin                 |
| äänelinen+A+Sg+Superl+Nom                | äänelissiin                 |
| lapselinen+A+Sg+Superl+Nom               | lapselissiin                |
| ittelinen+A+Sg+Superl+Nom                | ittelissiin                 |
| tähđelinen+A+Sg+Superl+Nom               | tähđelissiin                |
| tođelinen+A+Sg+Superl+Nom                | tođelissiin                 |
| täyđelinen+A+Sg+Superl+Nom               | täyđelissiin                |
| eilinen+A+Sg+Superl+Nom                  | eilissiin                   |
| ruumhiilinen+A+Sg+Superl+Nom             | ruumhiilissiin              |
| faakilinen+A+Sg+Superl+Nom               | faakilissiin                |
| arkiivifaakilinen+A+Sg+Superl+Nom        | arkiivifaakilissiin         |
| merkilinen+A+Sg+Superl+Nom               | merkilissiin                |
| teknilinen+A+Sg+Superl+Nom               | teknilissiin                |
| kropilinen+A+Sg+Superl+Nom               | kropilissiin                |
| tyypilinen+A+Sg+Superl+Nom               | tyypilissiin                |
| sportilinen+A+Sg+Superl+Nom              | sportilissiin               |
| kristilinen+A+Sg+Superl+Nom              | kristilissiin               |
| paralellinen+A+Sg+Superl+Nom             | paralellissiin              |
| histoorillinen+A+Sg+Superl+Nom           | histoorillissiin            |
| uskonollinen+A+Sg+Superl+Nom             | uskonollissiin              |
| ystävällinen+A+Sg+Superl+Nom             | ystävällissiin              |
| pakolinen+A+Sg+Superl+Nom                | pakolissiin                 |
| uskolinen+A+Sg+Superl+Nom                | uskolissiin                 |
| joukolinen+A+Sg+Superl+Nom               | joukolissiin                |
| armolinen+A+Sg+Superl+Nom                | armolissiin                 |
| painolinen+A+Sg+Superl+Nom               | painolissiin                |
| valtapainolinen+A+Sg+Superl+Nom          | valtapainolissiin           |
| sivvupainolinen+A+Sg+Superl+Nom          | sivvupainolissiin           |
| kunnolinen+A+Sg+Superl+Nom               | kunnolissiin                |
| luonolinen+A+Sg+Superl+Nom               | luonolissiin                |
| urhoolinen+A+Sg+Superl+Nom               | urhoolissiin                |
| ehtoolinen+A+Sg+Superl+Nom               | ehtoolissiin                |
| kiitolinen+A+Sg+Superl+Nom               | kiitolissiin                |
| luontolinen+A+Sg+Superl+Nom              | luontolissiin               |
| javolinen+A+Sg+Superl+Nom                | javolissiin                 |
| velvolinen+A+Sg+Superl+Nom               | velvolissiin                |
| mahđolinen+A+Sg+Superl+Nom               | mahđolissiin                |
| prikulinen+A+Sg+Superl+Nom               | prikulissiin                |
| lopulinen+A+Sg+Superl+Nom                | lopulissiin                 |
| pirulinen+A+Sg+Superl+Nom                | pirulissiin                 |
| surulinen+A+Sg+Superl+Nom                | surulissiin                 |
| ruuđulinen+A+Sg+Superl+Nom               | ruuđulissiin                |
| ylinen+A+Sg+Superl+Nom                   | ylissiin                    |
| myrkylinen+A+Sg+Superl+Nom               | myrkylissiin                |
| lykylinen+A+Sg+Superl+Nom                | lykylissiin                 |
| hyöđylinen+A+Sg+Superl+Nom               | hyöđylissiin                |
| pitkälinen+A+Sg+Superl+Nom               | pitkälissiin                |
| välinen+A+Sg+Superl+Nom                  | välissiin                   |
| viiminen+A+Sg+Superl+Nom                 | viimissiin                  |
| ekonominen+A+Sg+Superl+Nom               | ekonomissiin                |
| autonoominen+A+Sg+Superl+Nom             | autonoomissiin              |
| luminen+A+Sg+Superl+Nom                  | lumissiin                   |
| synonyyminen+A+Sg+Superl+Nom             | synonyymissiin              |
| sininen+A+Sg+Superl+Nom                  | sinissiin                   |
| vaaleesininen+A+Sg+Superl+Nom            | vaaleesinissiin             |
| elektroninen+A+Sg+Superl+Nom             | elektronissiin              |
| pahanjuoninen+A+Sg+Superl+Nom            | pahanjuonissiin             |
| vastahakoinen+A+Sg+Superl+Nom            | vastahakoissiin             |
| kotitekoinen+A+Sg+Superl+Nom             | kotitekoissiin              |
| erikoinen+A+Sg+Superl+Nom                | erikoissiin                 |
| louhikkoinen+A+Sg+Superl+Nom             | louhikkoissiin              |
| alinkoinen+A+Sg+Superl+Nom               | alinkoissiin                |
| aurinkoinen+A+Sg+Superl+Nom              | aurinkoissiin               |
| kokoinen+A+Sg+Superl+Nom                 | kokoissiin                  |
| puolikokoinen+A+Sg+Superl+Nom            | puolikokoissiin             |
| epäuskoinen+A+Sg+Superl+Nom              | epäuskoissiin               |
| iloinen+A+Sg+Superl+Nom                  | iloissiin                   |
| kiloinen+A+Sg+Superl+Nom                 | kiloissiin                  |
| suloinen+A+Sg+Superl+Nom                 | suloissiin                  |
| epäluuloinen+A+Sg+Superl+Nom             | epäluuloissiin              |
| kivuloinen+A+Sg+Superl+Nom               | kivuloissiin                |
| aikamoinen+A+Sg+Superl+Nom               | aikamoissiin                |
| semmoinen+A+Sg+Superl+Nom                | semmoissiin                 |
| tuomoinen+A+Sg+Superl+Nom                | tuomoissiin                 |
| toinen+A+Sg+Superl+Nom                   | toissiin                    |
| pitkävetoinen+A+Sg+Superl+Nom            | pitkävetoissiin             |
| vapaaehtoinen+A+Sg+Superl+Nom            | vapaaehtoissiin             |
| hyvämuistoinen+A+Sg+Superl+Nom           | hyvämuistoissiin            |
| samanarvoinen+A+Sg+Superl+Nom            | samanarvoissiin             |
| pitkä+A+Sg+Superl+Nom                    | pissiin                     |
| prototyyppinen+A+Sg+Superl+Nom           | prototyyppissiin            |
| populaarinen+A+Sg+Superl+Nom             | populaarissiin              |
| porvarinen+A+Sg+Superl+Nom               | porvarissiin                |
| geneerinen+A+Sg+Superl+Nom               | geneerissiin                |
| tummaverinen+A+Sg+Superl+Nom             | tummaverissiin              |
| vihrinen+A+Sg+Superl+Nom                 | vihrissiin                  |
| kelta-vihrinen+A+Sg+Superl+Nom           | kelta-vihrissiin            |
| sini-vihrinen+A+Sg+Superl+Nom            | sini-vihrissiin             |
| obligatoorinen+A+Sg+Superl+Nom           | obligatoorissiin            |
| elektrinen+A+Sg+Superl+Nom               | elektrissiin                |
| pahankurinen+A+Sg+Superl+Nom             | pahankurissiin              |
| hullunkurinen+A+Sg+Superl+Nom            | hullunkurissiin             |
| kulttuurinen+A+Sg+Superl+Nom             | kulttuurissiin              |
| färinen+A+Sg+Superl+Nom                  | färissiin                   |
| erifärinen+A+Sg+Superl+Nom               | erifärissiin                |
| samanfärinen+A+Sg+Superl+Nom             | samanfärissiin              |
| sisä+A+Sg+Superl+Nom                     | sissiin                     |
| vesinen+A+Sg+Superl+Nom                  | vesissiin                   |
| kaksinen+A+Sg+Superl+Nom                 | kaksissiin                  |
| kompleksinen+A+Sg+Superl+Nom             | kompleksissiin              |
| pitkävarsinen+A+Sg+Superl+Nom            | pitkävarsissiin             |
| saftinen+A+Sg+Superl+Nom                 | saftissiin                  |
| syntaktinen+A+Sg+Superl+Nom              | syntaktissiin               |
| entinen+A+Sg+Superl+Nom                  | entissiin                   |
| syntinen+A+Sg+Superl+Nom                 | syntissiin                  |
| läntinen+A+Sg+Superl+Nom                 | läntissiin                  |
| totinen+A+Sg+Superl+Nom                  | totissiin                   |
| vuotinen+A+Sg+Superl+Nom                 | vuotissiin                  |
| dramaattinen+A+Sg+Superl+Nom             | dramaattissiin              |
| systemaattinen+A+Sg+Superl+Nom           | systemaattissiin            |
| symptomaattinen+A+Sg+Superl+Nom          | symptomaattissiin           |
| sympaattinen+A+Sg+Superl+Nom             | sympaattissiin              |
| konkreettinen+A+Sg+Superl+Nom            | konkreettissiin             |
| poliittinen+A+Sg+Superl+Nom              | poliittissiin               |
| polittinen+A+Sg+Superl+Nom               | polittissiin                |
| pulittinen+A+Sg+Superl+Nom               | pulittissiin                |
| neljenkanttinen+A+Sg+Superl+Nom          | neljenkanttissiin           |
| kahđeksenkanttinen+A+Sg+Superl+Nom       | kahđeksenkanttissiin        |
| neliskanttinen+A+Sg+Superl+Nom           | neliskanttissiin            |
| semanttinen+A+Sg+Superl+Nom              | semanttissiin               |
| romanttinen+A+Sg+Superl+Nom              | romanttissiin               |
| identtinen+A+Sg+Superl+Nom               | identtissiin                |
| yhđensorttinen+A+Sg+Superl+Nom           | yhđensorttissiin            |
| uuđenaikhuinen+A+Sg+Superl+Nom           | uuđenaikhuissiin            |
| mielhuinen+A+Sg+Superl+Nom               | mielhuissiin                |
| ikuinen+A+Sg+Superl+Nom                  | ikuissiin                   |
| pikkuinen+A+Sg+Superl+Nom                | pikkuissiin                 |
| harkkuinen+A+Sg+Superl+Nom               | harkkuissiin                |
| korkuinen+A+Sg+Superl+Nom                | korkuissiin                 |
| suomensukuinen+A+Sg+Superl+Nom           | suomensukuissiin            |
| luinen+A+Sg+Superl+Nom                   | luissiin                    |
| viluinen+A+Sg+Superl+Nom                 | viluissiin                  |
| hirmuinen+A+Sg+Superl+Nom                | hirmuissiin                 |
| sumuinen+A+Sg+Superl+Nom                 | sumuissiin                  |
| hoppuinen+A+Sg+Superl+Nom                | hoppuissiin                 |
| sananloppuinen+A+Sg+Superl+Nom           | sananloppuissiin            |
| vakituinen+A+Sg+Superl+Nom               | vakituissiin                |
| omituinen+A+Sg+Superl+Nom                | omituissiin                 |
| pituinen+A+Sg+Superl+Nom                 | pituissiin                  |
| vasituinen+A+Sg+Superl+Nom               | vasituissiin                |
| joutuinen+A+Sg+Superl+Nom                | joutuissiin                 |
| usheempitavuinen+A+Sg+Superl+Nom         | usheempitavuissiin          |
| kaksitavuinen+A+Sg+Superl+Nom            | kaksitavuissiin             |
| yksitavuinen+A+Sg+Superl+Nom             | yksitavuissiin              |
| vissi+A+Sg+Superl+Nom                    | vissiin                     |
| skandinaavinen+A+Sg+Superl+Nom           | skandinaavissiin            |
| passiivinen+A+Sg+Superl+Nom              | passiivissiin               |
| abessiivinen+A+Sg+Superl+Nom             | abessiivissiin              |
| kreatiivinen+A+Sg+Superl+Nom             | kreatiivissiin              |
| nekatiivinen+A+Sg+Superl+Nom             | nekatiivissiin              |
| administratiivinen+A+Sg+Superl+Nom       | administratiivissiin        |
| kausatiivinen+A+Sg+Superl+Nom            | kausatiivissiin             |
| primitiivinen+A+Sg+Superl+Nom            | primitiivissiin             |
| positiivinen+A+Sg+Superl+Nom             | positiivissiin              |
| pusitiivinen+A+Sg+Superl+Nom             | pusitiivissiin              |
| aktiivinen+A+Sg+Superl+Nom               | aktiivissiin                |
| effektiivinen+A+Sg+Superl+Nom            | effektiivissiin             |
| konnektiivinen+A+Sg+Superl+Nom           | konnektiivissiin            |
| fiktiivinen+A+Sg+Superl+Nom              | fiktiivissiin               |
| disjunktiivinen+A+Sg+Superl+Nom          | disjunktiivissiin           |
| kivinen+A+Sg+Superl+Nom                  | kivissiin                   |
| pilvinen+A+Sg+Superl+Nom                 | pilvissiin                  |
| epävissi+A+Sg+Superl+Nom                 | epävissiin                  |
| rynkkyinen+A+Sg+Superl+Nom               | rynkkyissiin                |
| nykyinen+A+Sg+Superl+Nom                 | nykyissiin                  |
| pölyinen+A+Sg+Superl+Nom                 | pölyissiin                  |
| erityinen+A+Sg+Superl+Nom                | erityissiin                 |
| ikhäinen+A+Sg+Superl+Nom                 | ikhäissiin                  |
| keski-ikhäinen+A+Sg+Superl+Nom           | keski-ikhäissiin            |
| alaikhäinen+A+Sg+Superl+Nom              | alaikhäissiin               |
| vähäinen+A+Sg+Superl+Nom                 | vähäissiin                  |
| alaikäinen+A+Sg+Superl+Nom               | alaikäissiin                |
| reikäinen+A+Sg+Superl+Nom                | reikäissiin                 |
| koukkuselkäinen+A+Sg+Superl+Nom          | koukkuselkäissiin           |
| koukkusölkäinen+A+Sg+Superl+Nom          | koukkusölkäissiin           |
| ymmyrkäinen+A+Sg+Superl+Nom              | ymmyrkäissiin               |
| lyhykäinen+A+Sg+Superl+Nom               | lyhykäissiin                |
| äkäinen+A+Sg+Superl+Nom                  | äkäissiin                   |
| itteläinen+A+Sg+Superl+Nom               | itteläissiin                |
| briittiläinen+A+Sg+Superl+Nom            | briittiläissiin             |
| pitkyläinen+A+Sg+Superl+Nom              | pitkyläissiin               |
| yykeäläinen+A+Sg+Superl+Nom              | yykeäläissiin               |
| pykejäläinen+A+Sg+Superl+Nom             | pykejäläissiin              |
| tyskäläinen+A+Sg+Superl+Nom              | tyskäläissiin               |
| venäläinen+A+Sg+Superl+Nom               | venäläissiin                |
| ryssäläinen+A+Sg+Superl+Nom              | ryssäläissiin               |
| likimäinen+A+Sg+Superl+Nom               | likimäissiin                |
| jälkimäinen+A+Sg+Superl+Nom              | jälkimäissiin               |
| keskimäinen+A+Sg+Superl+Nom              | keskimäissiin               |
| täkimäinen+A+Sg+Superl+Nom               | täkimäissiin                |
| ylimäinen+A+Sg+Superl+Nom                | ylimäissiin                 |
| päälimäinen+A+Sg+Superl+Nom              | päälimäissiin               |
| ensimäinen+A+Sg+Superl+Nom               | ensimäissiin                |
| tämmäinen+A+Sg+Superl+Nom                | tämmäissiin                 |
| pörämäinen+A+Sg+Superl+Nom               | pörämäissiin                |
| ittenäinen+A+Sg+Superl+Nom               | ittenäissiin                |
| äkkinäinen+A+Sg+Superl+Nom               | äkkinäissiin                |
| yksinäinen+A+Sg+Superl+Nom               | yksinäissiin                |
| ittepäinen+A+Sg+Superl+Nom               | ittepäissiin                |
| kaljupäinen+A+Sg+Superl+Nom              | kaljupäissiin               |
| ymmyräinen+A+Sg+Superl+Nom               | ymmyräissiin                |
| alkupöräinen+A+Sg+Superl+Nom             | alkupöräissiin              |
| pahasäinen+A+Sg+Superl+Nom               | pahasäissiin                |
| sisäinen+A+Sg+Superl+Nom                 | sisäissiin                  |
| öystäinen+A+Sg+Superl+Nom                | öystäissiin                 |
| myötäinen+A+Sg+Superl+Nom                | myötäissiin                 |
| tytyväinen+A+Sg+Superl+Nom               | tytyväissiin                |
| näköinen+A+Sg+Superl+Nom                 | näköissiin                  |
| pirunnäköinen+A+Sg+Superl+Nom            | pirunnäköissiin             |
| tämmöinen+A+Sg+Superl+Nom                | tämmöissiin                 |
| vähätöinen+A+Sg+Superl+Nom               | vähätöissiin                |
| tylsä+A+Sg+Superl+Nom                    | tylssiin                    |
| oranssi+A+Sg+Superl+Nom                  | oranssiin                   |
| kotitekonen+A+Sg+Superl+Nom              | kotitekossiin               |
| louhikkonen+A+Sg+Superl+Nom              | louhikkossiin               |
| pilkkonen+A+Sg+Superl+Nom                | pilkkossiin                 |
| puolikokonen+A+Sg+Superl+Nom             | puolikokossiin              |
| semmonen+A+Sg+Superl+Nom                 | semmossiin                  |
| tuomoinen+A+Sg+Superl+Nom                | tuomossiin                  |
| tosi+A+Sg+Superl+Nom                     | tossiin                     |
| vapaaehtonen+A+Sg+Superl+Nom             | vapaaehtossiin              |
| kotonen+A+Sg+Superl+Nom                  | kotossiin                   |
| ikunen+A+Sg+Superl+Nom                   | ikussiin                    |
| pikkunen+A+Sg+Superl+Nom                 | pikkussiin                  |
| harkkunen+A+Sg+Superl+Nom                | harkkussiin                 |
| vilunen+A+Sg+Superl+Nom                  | vilussiin                   |
| hirmunen+A+Sg+Superl+Nom                 | hirmussiin                  |
| uusi+A+Sg+Superl+Nom                     | uussiin                     |
| rynkkynen+A+Sg+Superl+Nom                | rynkkyssiin                 |
| nykynen+A+Sg+Superl+Nom                  | nykyssiin                   |
| pölynen+A+Sg+Superl+Nom                  | pölyssiin                   |
| täysi+A+Sg+Superl+Nom                    | täyssiin                    |
| löysä+A+Sg+Superl+Nom                    | löyssiin                    |
| vähänen+A+Sg+Superl+Nom                  | vähässiin                   |
| alaikänen+A+Sg+Superl+Nom                | alaikässiin                 |
| äkänen+A+Sg+Superl+Nom                   | äkässiin                    |
| tämmänen+A+Sg+Superl+Nom                 | tämmässiin                  |
| alkupöränen+A+Sg+Superl+Nom              | alkupörässiin               |
| sisänen+A+Sg+Superl+Nom                  | sisässiin                   |
| näkönen+A+Sg+Superl+Nom                  | näkössiin                   |
| pirunnäkönen+A+Sg+Superl+Nom             | pirunnäkössiin              |
| fasta+A+Sg+Superl+Nom                    | fastiin                     |
| siisti+A+Sg+Superl+Nom                   | siistiin                    |
| musta+A+Sg+Superl+Nom                    | mustiin                     |
| pikimusta+A+Sg+Superl+Nom                | pikimustiin                 |
| fioletti+A+Sg+Superl+Nom                 | fiolettiin                  |
| ultrafioletti+A+Sg+Superl+Nom            | ultrafiolettiin             |
| interesantti+A+Sg+Superl+Nom             | interesanttiin              |
| ekvivalentti+A+Sg+Superl+Nom             | ekvivalenttiin              |
| auttii+A+Sg+Superl+Nom                   | auttiin                     |
| mätä+A+Sg+Superl+Nom                     | mättiin                     |
| ryöttä+A+Sg+Superl+Nom                   | ryöttiin                    |
| söötti+A+Sg+Superl+Nom                   | sööttiin                    |
| kirjaava+A+Sg+Superl+Nom                 | kirjaaviin                  |
| yhtheenhenkkaava+A+Sg+Superl+Nom         | yhtheenhenkkaaviin          |
| seuraava+A+Sg+Superl+Nom                 | seuraaviin                  |
| mahtaava+A+Sg+Superl+Nom                 | mahtaaviin                  |
| loistaava+A+Sg+Superl+Nom                | loistaaviin                 |
| valttaava+A+Sg+Superl+Nom                | valttaaviin                 |
| virttaava+A+Sg+Superl+Nom                | virttaaviin                 |
| jouttaava+A+Sg+Superl+Nom                | jouttaaviin                 |
| lihava+A+Sg+Superl+Nom                   | lihaviin                    |
| vakava+A+Sg+Superl+Nom                   | vakaviin                    |
| mukava+A+Sg+Superl+Nom                   | mukaviin                    |
| painava+A+Sg+Superl+Nom                  | painaviin                   |
| herrattava+A+Sg+Superl+Nom               | herrattaviin                |
| yhđentekkeevä+A+Sg+Superl+Nom            | yhđentekkeeviin             |
| järkkeevä+A+Sg+Superl+Nom                | järkkeeviin                 |
| väkkeevä+A+Sg+Superl+Nom                 | väkkeeviin                  |
| pulleeva+A+Sg+Superl+Nom                 | pulleeviin                  |
| tulleeva+A+Sg+Superl+Nom                 | tulleeviin                  |
| lievä+A+Sg+Superl+Nom                    | lieviin                     |
| sievä+A+Sg+Superl+Nom                    | sieviin                     |
| vahva+A+Sg+Superl+Nom                    | vahviin                     |
| tyhvä+A+Sg+Superl+Nom                    | tyhviin                     |
| soppiiva+A+Sg+Superl+Nom                 | soppiiviin                  |
| kärsiivä+A+Sg+Superl+Nom                 | kärsiiviin                  |
| nekatiivi+A+Sg+Superl+Nom                | nekatiiviin                 |
| primitiivi+A+Sg+Superl+Nom               | primitiiviin                |
| loiva+A+Sg+Superl+Nom                    | loiviin                     |
| kuiva+A+Sg+Superl+Nom                    | kuiviin                     |
| selvä+A+Sg+Superl+Nom                    | selviin                     |
| epäselvä+A+Sg+Superl+Nom                 | epäselviin                  |
| pälvi+A+Sg+Superl+Nom                    | pälviin                     |
| harva+A+Sg+Superl+Nom                    | harviin                     |
| krouvi+A+Sg+Superl+Nom                   | krouviin                    |
| puolikassuuva+A+Sg+Superl+Nom            | puolikassuuviin             |
| leppääkassuuva+A+Sg+Superl+Nom           | leppääkassuuviin            |
| tunttuuva+A+Sg+Superl+Nom                | tunttuuviin                 |
| kiva+A+Sg+Superl+Nom                     | kivviin                     |
| kova+A+Sg+Superl+Nom                     | kovviin                     |
| syvä+A+Sg+Superl+Nom                     | syvviin                     |
| ikävä+A+Sg+Superl+Nom                    | ikäviin                     |
| terävä+A+Sg+Superl+Nom                   | teräviin                    |
| veđenpitävä+A+Sg+Superl+Nom              | veđenpitäviin               |
| merkittävä+A+Sg+Superl+Nom               | merkittäviin                |
| syötävä+A+Sg+Superl+Nom                  | syötäviin                   |
| elläävä+A+Sg+Superl+Nom                  | ellääviin                   |
| ymmärettäävä+A+Sg+Superl+Nom             | ymmärettääviin              |
| jännittäävä+A+Sg+Superl+Nom              | jännittääviin               |
| kiilttäävä+A+Sg+Superl+Nom               | kiilttääviin                |
| virkistyttäävä+A+Sg+Superl+Nom           | virkistyttääviin            |
| irtain+A+Sg+Superl+Nom                   | irtaimin                    |
| laho+A+Sg+Superl+Nom                     | lahhoin                     |
| mainio+A+Sg+Superl+Nom                   | mainioin                    |
| ujo+A+Sg+Superl+Nom                      | ujjoin                      |
| ilakka+A+Sg+Superl+Nom                   | ilakkoin                    |
| heikko+A+Sg+Superl+Nom                   | heikkoin                    |
| silko+A+Sg+Superl+Nom                    | silkkoin                    |
| ulko+A+Sg+Superl+Nom                     | ulkkoin                     |
| kaalo+A+Sg+Superl+Nom                    | kaaloin                     |
| kolo+A+Sg+Superl+Nom                     | kolloin                     |
| tollo+A+Sg+Superl+Nom                    | tolloin                     |
| hieno+A+Sg+Superl+Nom                    | hienoin                     |
| kehno+A+Sg+Superl+Nom                    | kehnoin                     |
| huono+A+Sg+Superl+Nom                    | huonoin                     |
| helppo+A+Sg+Superl+Nom                   | helppoin                    |
| juoppo+A+Sg+Superl+Nom                   | juoppoin                    |
| suipero+A+Sg+Superl+Nom                  | suiperoin                   |
| kuuro+A+Sg+Superl+Nom                    | kuuroin                     |
| lakso+A+Sg+Superl+Nom                    | laksoin                     |
| iso+A+Sg+Superl+Nom                      | issoin                      |
| viinto+A+Sg+Superl+Nom                   | viintoin                    |
| vaisto+A+Sg+Superl+Nom                   | vaistoin                    |
| pisto+A+Sg+Superl+Nom                    | pistoin                     |
| visto+A+Sg+Superl+Nom                    | vistoin                     |
| kaltto+A+Sg+Superl+Nom                   | kalttoin                    |
| ontto+A+Sg+Superl+Nom                    | onttoin                     |
| outo+A+Sg+Superl+Nom                     | outtoin                     |
| rutto+A+Sg+Superl+Nom                    | ruttoin                     |
| siivo+A+Sg+Superl+Nom                    | siivoin                     |
| raju+A+Sg+Superl+Nom                     | rajjuin                     |
| kalju+A+Sg+Superl+Nom                    | kaljuin                     |
| virkku+A+Sg+Superl+Nom                   | virkkuin                    |
| hullu+A+Sg+Superl+Nom                    | hulluin                     |
| sotahullu+A+Sg+Superl+Nom                | sotahulluin                 |
| kuulu+A+Sg+Superl+Nom                    | kuuluin                     |
| liehmuu+A+Sg+Superl+Nom                  | liehmuin                    |
| lamu+A+Sg+Superl+Nom                     | lammuin                     |
| karu+A+Sg+Superl+Nom                     | karruin                     |
| paksu+A+Sg+Superl+Nom                    | paksuin                     |
| kalsu+A+Sg+Superl+Nom                    | kalsuin                     |
| kesu+A+Sg+Superl+Nom                     | kessuin                     |
| visu+A+Sg+Superl+Nom                     | vissuin                     |
| merkattu+A+Sg+Superl+Nom                 | merkattuin                  |
| maalattu+A+Sg+Superl+Nom                 | maalattuin                  |
| ulkokullattu+A+Sg+Superl+Nom             | ulkokullattuin              |
| kevveestisuolattu+A+Sg+Superl+Nom        | kevveestisuolattuin         |
| siunattu+A+Sg+Superl+Nom                 | siunattuin                  |
| tunnettu+A+Sg+Superl+Nom                 | tunnettuin                  |
| opetettu+A+Sg+Superl+Nom                 | opetettuin                  |
| valittu+A+Sg+Superl+Nom                  | valittuin                   |
| vasittu+A+Sg+Superl+Nom                  | vasittuin                   |
| kuvailtu+A+Sg+Superl+Nom                 | kuvailttuin                 |
| kranttu+A+Sg+Superl+Nom                  | kranttuin                   |
| kattottu+A+Sg+Superl+Nom                 | kattottuin                  |
| kotonakuottu+A+Sg+Superl+Nom             | kotonakuottuin              |
| koutu+A+Sg+Superl+Nom                    | kouttuin                    |
| tuttu+A+Sg+Superl+Nom                    | tuttuin                     |
| kärys+A+Sg+Superl+Nom                    | kärhyin                     |
| häijy+A+Sg+Superl+Nom                    | häijyin                     |
| syyry+A+Sg+Superl+Nom                    | syyryin                     |
| kypsy+A+Sg+Superl+Nom                    | kypsyin                     |
| niinkäsketty+A+Sg+Superl+Nom             | niinkäskettyin              |
| kylmetty+A+Sg+Superl+Nom                 | kylmettyin                  |
| pyhitetty+A+Sg+Superl+Nom                | pyhitettyin                 |
| käytetty+A+Sg+Superl+Nom                 | käytettyin                  |
| kristitty+A+Sg+Superl+Nom                | kristittyin                 |
| määrätty+A+Sg+Superl+Nom                 | määrättyin                  |
| präntätty+A+Sg+Superl+Nom                | präntättyin                 |
| sinnikäs+A+Sg+Superl+Nom                 | sinnikkhäin                 |
| pystö+A+Sg+Superl+Nom                    | pystöin                     |
