|                                   |                           |
|-----------------------------------|---------------------------|
| +A+Pl+Gen                         | +A+Pl+Gen                 |
| viimi+A+Pl+Gen                    | viimi+A+Pl+Gen            |
| turkkiisi+A+Pl+Gen                | turkkiisi+A+Pl+Gen        |
| ensi+A+Pl+Gen                     | ensi+A+Pl+Gen             |
| vaiti+A+Pl+Gen                    | vaiti+A+Pl+Gen            |
| irti+A+Pl+Gen                     | irti+A+Pl+Gen             |
| fonologinen+A+Pl+Gen              | fonologinen+A+Pl+Gen      |
| paras+A+Pl+Gen                    | paras+A+Pl+Gen            |
| ohut+A+Pl+Gen                     | ohut+A+Pl+Gen             |
| ehyt+A+Pl+Gen                     | ehyt+A+Pl+Gen             |
| lyhyt+A+Pl+Gen                    | lyhyt+A+Pl+Gen            |
| ohu+A+Pl+Gen                      | ohu+A+Pl+Gen              |
| pikku+A+Pl+Gen                    | pikku+A+Pl+Gen            |
| lyhy+A+Pl+Gen                     | lyhy+A+Pl+Gen             |
| puoli+A+Pl+Gen                    | puolten                   |
| käsipuoli+A+Pl+Gen                | käsipuolten               |
| silmäpuoli+A+Pl+Gen               | silmäpuolten              |
| pieni+A+Pl+Gen                    | pienten                   |
| nuori+A+Pl+Gen                    | nuorten                   |
| suuri+A+Pl+Gen                    | suurten                   |
| vihanen+A+Pl+Gen                  | vihasten                  |
| samanaikhanen+A+Pl+Gen            | samanaikhasten            |
| uuđenaikhanen+A+Pl+Gen            | uuđenaikhasten            |
| nykyaikhanen+A+Pl+Gen             | nykyaikhasten             |
| tuhanen+A+Pl+Gen                  | tuhasten                  |
| pohjanen+A+Pl+Gen                 | pohjasten                 |
| sekanen+A+Pl+Gen                  | sekasten                  |
| hoikkanen+A+Pl+Gen                | hoikkasten                |
| kukkanen+A+Pl+Gen                 | kukkasten                 |
| mukkanen+A+Pl+Gen                 | mukkasten                 |
| tummatukkanen+A+Pl+Gen            | tummatukkasten            |
| pitkäjalkanen+A+Pl+Gen            | pitkäjalkasten            |
| lokanen+A+Pl+Gen                  | lokasten                  |
| neljennuskanen+A+Pl+Gen           | neljennuskasten           |
| salanen+A+Pl+Gen                  | salasten                  |
| kiimanen+A+Pl+Gen                 | kiimasten                 |
| ylivoimanen+A+Pl+Gen              | ylivoimasten              |
| punanen+A+Pl+Gen                  | punasten                  |
| vaaleepunanen+A+Pl+Gen            | vaaleepunasten            |
| aniliinipunanen+A+Pl+Gen          | aniliinipunasten          |
| vähävoipanen+A+Pl+Gen             | vähävoipasten             |
| tasanen+A+Pl+Gen                  | tasasten                  |
| kaitanen+A+Pl+Gen                 | kaitasten                 |
| keltainen+A+Pl+Gen                | keltasten                 |
| puolihintanen+A+Pl+Gen            | puolihintasten            |
| monikertanen+A+Pl+Gen             | monikertasten             |
| yksinkertanen+A+Pl+Gen            | yksinkertasten            |
| veres+A+Pl+Gen                    | veresten                  |
| vihainen+A+Pl+Gen                 | vihaisten                 |
| vanhaanaikhainen+A+Pl+Gen         | vanhaanaikhaisten         |
| samanaikhainen+A+Pl+Gen           | samanaikhaisten           |
| uuđenaikhainen+A+Pl+Gen           | uuđenaikhaisten           |
| nykyaikhainen+A+Pl+Gen            | nykyaikhaisten            |
| pitkäaikhainen+A+Pl+Gen           | pitkäaikhaisten           |
| kaukhainen+A+Pl+Gen               | kaukhaisten               |
| alhainen+A+Pl+Gen                 | alhaisten                 |
| salhainen+A+Pl+Gen                | salhaisten                |
| eriskumhainen+A+Pl+Gen            | eriskumhaisten            |
| varhainen+A+Pl+Gen                | varhaisten                |
| aijankohthainen+A+Pl+Gen          | aijankohthaisten          |
| pohjainen+A+Pl+Gen                | pohjaisten                |
| hiljainen+A+Pl+Gen                | hiljaisten                |
| sekainen+A+Pl+Gen                 | sekaisten                 |
| väliaikainen+A+Pl+Gen             | väliaikaisten             |
| likainen+A+Pl+Gen                 | likaisten                 |
| nollapaikkainen+A+Pl+Gen          | nollapaikkaisten          |
| kolmipaikkainen+A+Pl+Gen          | kolmipaikkaisten          |
| kaksipaikkainen+A+Pl+Gen          | kaksipaikkaisten          |
| yksipaikkainen+A+Pl+Gen           | yksipaikkaisten           |
| tummatukkainen+A+Pl+Gen           | tummatukkaisten           |
| neljenjalkainen+A+Pl+Gen          | neljenjalkaisten          |
| pitkäjalkainen+A+Pl+Gen           | pitkäjalkaisten           |
| vastahankainen+A+Pl+Gen           | vastahankaisten           |
| kaksirankainen+A+Pl+Gen           | kaksirankaisten           |
| yksirankainen+A+Pl+Gen            | yksirankaisten            |
| konsonanttirankainen+A+Pl+Gen     | konsonanttirankaisten     |
| lokainen+A+Pl+Gen                 | lokaisten                 |
| paskainen+A+Pl+Gen                | paskaisten                |
| nelinuskainen+A+Pl+Gen            | nelinuskaisten            |
| puskainen+A+Pl+Gen                | puskaisten                |
| latuskainen+A+Pl+Gen              | latuskaisten              |
| ohukainen+A+Pl+Gen                | ohukaisten                |
| korkukainen+A+Pl+Gen              | korkukaisten              |
| oikkeuđenmukainen+A+Pl+Gen        | oikkeuđenmukaisten        |
| reekelinmukainen+A+Pl+Gen         | reekelinmukaisten         |
| epäreekelinmukainen+A+Pl+Gen      | epäreekelinmukaisten      |
| suurukainen+A+Pl+Gen              | suurukaisten              |
| pitukainen+A+Pl+Gen               | pitukaisten               |
| maalainen+A+Pl+Gen                | maalaisten                |
| ulkomaalainen+A+Pl+Gen            | ulkomaalaisten            |
| ruijalainen+A+Pl+Gen              | ruijalaisten              |
| talosvankkalainen+A+Pl+Gen        | talosvankkalaisten        |
| jokalainen+A+Pl+Gen               | jokalaisten               |
| tuiskalainen+A+Pl+Gen             | tuiskalaisten             |
| tanskalainen+A+Pl+Gen             | tanskalaisten             |
| roomalainen+A+Pl+Gen              | roomalaisten              |
| suomalainen+A+Pl+Gen              | suomalaisten              |
| norjalais-suomalainen+A+Pl+Gen    | norjalais-suomalaisten    |
| suursuomalainen+A+Pl+Gen          | suursuomalaisten          |
| salainen+A+Pl+Gen                 | salaisten                 |
| saksalainen+A+Pl+Gen              | saksalaisten              |
| tromssalainen+A+Pl+Gen            | tromssalaisten            |
| ruottalainen+A+Pl+Gen             | ruottalaisten             |
| juutalainen+A+Pl+Gen              | juutalaisten              |
| vesisaarelainen+A+Pl+Gen          | vesisaarelaisten          |
| pyssyjokilainen+A+Pl+Gen          | pyssyjokilaisten          |
| puolilainen+A+Pl+Gen              | puolilaisten              |
| saamilainen+A+Pl+Gen              | saamilaisten              |
| erilainen+A+Pl+Gen                | erilaisten                |
| evankeelis-lutherilainen+A+Pl+Gen | evankeelis-lutherilaisten |
| suomalais-ugrilainen+A+Pl+Gen     | suomalais-ugrilaisten     |
| raisilainen+A+Pl+Gen              | raisilaisten              |
| englantilainen+A+Pl+Gen           | englantilaisten           |
| hollantilainen+A+Pl+Gen           | hollantilaisten           |
| paavilainen+A+Pl+Gen              | paavilaisten              |
| villainen+A+Pl+Gen                | villaisten                |
| tällainen+A+Pl+Gen                | tällaisten                |
| samanlainen+A+Pl+Gen              | samanlaisten              |
| muutamanlainen+A+Pl+Gen           | muutamanlaisten           |
| kaikenlainen+A+Pl+Gen             | kaikenlaisten             |
| pienenlainen+A+Pl+Gen             | pienenlaisten             |
| monenlainen+A+Pl+Gen              | monenlaisten              |
| nuorenlainen+A+Pl+Gen             | nuorenlaisten             |
| senlainen+A+Pl+Gen                | senlaisten                |
| toisenlainen+A+Pl+Gen             | toisenlaisten             |
| kahđenlainen+A+Pl+Gen             | kahđenlaisten             |
| yhđenlainen+A+Pl+Gen              | yhđenlaisten              |
| tyyrhinlainen+A+Pl+Gen            | tyyrhinlaisten            |
| isonlainen+A+Pl+Gen               | isonlaisten               |
| tämänlainen+A+Pl+Gen              | tämänlaisten              |
| höperänlainen+A+Pl+Gen            | höperänlaisten            |
| vanholainen+A+Pl+Gen              | vanholaisten              |
| lestadiolainen+A+Pl+Gen           | lestadiolaisten           |
| torniolainen+A+Pl+Gen             | torniolaisten             |
| vanholaislestaatiolainen+A+Pl+Gen | vanholaislestaatiolaisten |
| alattiolainen+A+Pl+Gen            | alattiolaisten            |
| tornionlaksolainen+A+Pl+Gen       | tornionlaksolaisten       |
| suolainen+A+Pl+Gen                | suolaisten                |
| tuolainen+A+Pl+Gen                | tuolaisten                |
| savolainen+A+Pl+Gen               | savolaisten               |
| jonkulainen+A+Pl+Gen              | jonkulaisten              |
| kainulainen+A+Pl+Gen              | kainulaisten              |
| vestakainulainen+A+Pl+Gen         | vestakainulaisten         |
| minkälainen+A+Pl+Gen              | minkälaisten              |
| kiimainen+A+Pl+Gen                | kiimaisten                |
| alimainen+A+Pl+Gen                | alimaisten                |
| ylivoimainen+A+Pl+Gen             | ylivoimaisten             |
| ulomainen+A+Pl+Gen                | ulomaisten                |
| etumainen+A+Pl+Gen                | etumaisten                |
| yksituumainen+A+Pl+Gen            | yksituumaisten            |
| hajanainen+A+Pl+Gen               | hajanaisten               |
| vähäsanainen+A+Pl+Gen             | vähäsanaisten             |
| aukinainen+A+Pl+Gen               | aukinaisten               |
| harvinainen+A+Pl+Gen              | harvinaisten              |
| kokonainen+A+Pl+Gen               | kokonaisten               |
| punainen+A+Pl+Gen                 | punaisten                 |
| vaaleepunainen+A+Pl+Gen           | vaaleepunaisten           |
| aniliinipunainen+A+Pl+Gen         | aniliinipunaisten         |
| ruusunpunainen+A+Pl+Gen           | ruusunpunaisten           |
| vähävoipainen+A+Pl+Gen            | vähävoipaisten            |
| pikkurainen+A+Pl+Gen              | pikkuraisten              |
| tasainen+A+Pl+Gen                 | tasaisten                 |
| epätasainen+A+Pl+Gen              | epätasaisten              |
| hietainen+A+Pl+Gen                | hietaisten                |
| kaitainen+A+Pl+Gen                | kaitaisten                |
| ristiraitainen+A+Pl+Gen           | ristiraitaisten           |
| väkivaltainen+A+Pl+Gen            | väkivaltaisten            |
| keltainen+A+Pl+Gen                | keltaisten                |
| punaisenkeltainen+A+Pl+Gen        | punaisenkeltaisten        |
| puolihintainen+A+Pl+Gen           | puolihintaisten           |
| monikertainen+A+Pl+Gen            | monikertaisten            |
| monenkertainen+A+Pl+Gen           | monenkertaisten           |
| kahđenkertainen+A+Pl+Gen          | kahđenkertaisten          |
| yhđenkertainen+A+Pl+Gen           | yhđenkertaisten           |
| yksinkertainen+A+Pl+Gen           | yksinkertaisten           |
| virtainen+A+Pl+Gen                | virtaisten                |
| vestainen+A+Pl+Gen                | vestaisten                |
| luottavainen+A+Pl+Gen             | luottavaisten             |
| vaivainen+A+Pl+Gen                | vaivaisten                |
| uskovainen+A+Pl+Gen               | uskovaisten               |
| varovainen+A+Pl+Gen               | varovaisten               |
| karvainen+A+Pl+Gen                | karvaisten                |
| rasvainen+A+Pl+Gen                | rasvaisten                |
| likheinen+A+Pl+Gen                | likheisten                |
| melkheinen+A+Pl+Gen               | melkheisten               |
| ylheinen+A+Pl+Gen                 | ylheisten                 |
| yhtheinen+A+Pl+Gen                | yhtheisten                |
| myöntheinen+A+Pl+Gen              | myöntheisten              |
| auringonpaistheinen+A+Pl+Gen      | auringonpaistheisten      |
| fonoginen+A+Pl+Gen                | fonologisten              |
| morfofonologinen+A+Pl+Gen         | morfofonologisten         |
| biolooginen+A+Pl+Gen              | bioloogisten              |
| psykolooginen+A+Pl+Gen            | psykoloogisten            |
| ökolooginen+A+Pl+Gen              | ökoloogisten              |
| vierhiinen+A+Pl+Gen               | vierhiisten               |
| produktiivinen+A+Pl+Gen           | produktiisten             |
| iänkaikkinen+A+Pl+Gen             | iänkaikkisten             |
| piikkinen+A+Pl+Gen                | piikkisten                |
| pahanilkinen+A+Pl+Gen             | pahanilkisten             |
| nokinen+A+Pl+Gen                  | nokisten                  |
| modaalinen+A+Pl+Gen               | modaalisten               |
| sosiaalinen+A+Pl+Gen              | sosiaalisten              |
| lyhykäisvokaalinen+A+Pl+Gen       | lyhykäisvokaalisten       |
| maalinen+A+Pl+Gen                 | maalisten                 |
| tradittiinaalinen+A+Pl+Gen        | tradittiinaalisten        |
| pluraalinen+A+Pl+Gen              | pluraalisten              |
| digitaalinen+A+Pl+Gen             | digitaalisten             |
| aspektuaalinen+A+Pl+Gen           | aspektuaalisten           |
| rauhalinen+A+Pl+Gen               | rauhalisten               |
| histoorialinen+A+Pl+Gen           | histoorialisten           |
| historialinen+A+Pl+Gen            | historialisten            |
| paikalinen+A+Pl+Gen               | paikalisten               |
| kummalinen+A+Pl+Gen               | kummalisten               |
| vaaralinen+A+Pl+Gen               | vaaralisten               |
| viralinen+A+Pl+Gen                | viralisten                |
| kansalinen+A+Pl+Gen               | kansalisten               |
| osalinen+A+Pl+Gen                 | osalisten                 |
| tavalinen+A+Pl+Gen                | tavalisten                |
| epätavalinen+A+Pl+Gen             | epätavalisten             |
| turvalinen+A+Pl+Gen               | turvalisten               |
| luvalinen+A+Pl+Gen                | luvalisten                |
| raiđalinen+A+Pl+Gen               | raiđalisten               |
| tarpheelinen+A+Pl+Gen             | tarpheelisten             |
| murheelinen+A+Pl+Gen              | murheelisten              |
| katheelinen+A+Pl+Gen              | katheelisten              |
| satheelinen+A+Pl+Gen              | satheelisten              |
| puutheelinen+A+Pl+Gen             | puutheelisten             |
| tervheelinen+A+Pl+Gen             | tervheelisten             |
| hengelinen+A+Pl+Gen               | hengelisten               |
| rehelinen+A+Pl+Gen                | rehelisten                |
| kolmikielinen+A+Pl+Gen            | kolmikielisten            |
| kaksikielinen+A+Pl+Gen            | kaksikielisten            |
| suomenkielinen+A+Pl+Gen           | suomenkielisten           |
| kainunkielinen+A+Pl+Gen           | kainunkielisten           |
| ylimielinen+A+Pl+Gen              | ylimielisten              |
| yksmielinen+A+Pl+Gen              | yksmielisten              |
| onnelinen+A+Pl+Gen                | onnelisten                |
| äänelinen+A+Pl+Gen                | äänelisten                |
| lapselinen+A+Pl+Gen               | lapselisten               |
| ittelinen+A+Pl+Gen                | ittelisten                |
| tähđelinen+A+Pl+Gen               | tähđelisten               |
| tođelinen+A+Pl+Gen                | tođelisten                |
| täyđelinen+A+Pl+Gen               | täyđelisten               |
| eilinen+A+Pl+Gen                  | eilisten                  |
| ruumhiilinen+A+Pl+Gen             | ruumhiilisten             |
| faakilinen+A+Pl+Gen               | faakilisten               |
| arkiivifaakilinen+A+Pl+Gen        | arkiivifaakilisten        |
| merkilinen+A+Pl+Gen               | merkilisten               |
| teknilinen+A+Pl+Gen               | teknilisten               |
| kropilinen+A+Pl+Gen               | kropilisten               |
| tyypilinen+A+Pl+Gen               | tyypilisten               |
| sportilinen+A+Pl+Gen              | sportilisten              |
| kristilinen+A+Pl+Gen              | kristilisten              |
| paralellinen+A+Pl+Gen             | paralellisten             |
| histoorillinen+A+Pl+Gen           | histoorillisten           |
| uskonollinen+A+Pl+Gen             | uskonollisten             |
| ystävällinen+A+Pl+Gen             | ystävällisten             |
| pakolinen+A+Pl+Gen                | pakolisten                |
| uskolinen+A+Pl+Gen                | uskolisten                |
| joukolinen+A+Pl+Gen               | joukolisten               |
| armolinen+A+Pl+Gen                | armolisten                |
| painolinen+A+Pl+Gen               | painolisten               |
| valtapainolinen+A+Pl+Gen          | valtapainolisten          |
| sivvupainolinen+A+Pl+Gen          | sivvupainolisten          |
| kunnolinen+A+Pl+Gen               | kunnolisten               |
| luonolinen+A+Pl+Gen               | luonolisten               |
| urhoolinen+A+Pl+Gen               | urhoolisten               |
| ehtoolinen+A+Pl+Gen               | ehtoolisten               |
| kiitolinen+A+Pl+Gen               | kiitolisten               |
| luontolinen+A+Pl+Gen              | luontolisten              |
| javolinen+A+Pl+Gen                | javolisten                |
| velvolinen+A+Pl+Gen               | velvolisten               |
| mahđolinen+A+Pl+Gen               | mahđolisten               |
| prikulinen+A+Pl+Gen               | prikulisten               |
| lopulinen+A+Pl+Gen                | lopulisten                |
| pirulinen+A+Pl+Gen                | pirulisten                |
| surulinen+A+Pl+Gen                | surulisten                |
| ruuđulinen+A+Pl+Gen               | ruuđulisten               |
| ylinen+A+Pl+Gen                   | ylisten                   |
| myrkylinen+A+Pl+Gen               | myrkylisten               |
| lykylinen+A+Pl+Gen                | lykylisten                |
| hyöđylinen+A+Pl+Gen               | hyöđylisten               |
| pitkälinen+A+Pl+Gen               | pitkälisten               |
| välinen+A+Pl+Gen                  | välisten                  |
| viiminen+A+Pl+Gen                 | viimisten                 |
| ekonominen+A+Pl+Gen               | ekonomisten               |
| autonoominen+A+Pl+Gen             | autonoomisten             |
| luminen+A+Pl+Gen                  | lumisten                  |
| synonyyminen+A+Pl+Gen             | synonyymisten             |
| sininen+A+Pl+Gen                  | sinisten                  |
| vaaleesininen+A+Pl+Gen            | vaaleesinisten            |
| elektroninen+A+Pl+Gen             | elektronisten             |
| pahanjuoninen+A+Pl+Gen            | pahanjuonisten            |
| vastahakoinen+A+Pl+Gen            | vastahakoisten            |
| kotitekoinen+A+Pl+Gen             | kotitekoisten             |
| erikoinen+A+Pl+Gen                | erikoisten                |
| louhikkoinen+A+Pl+Gen             | louhikkoisten             |
| alinkoinen+A+Pl+Gen               | alinkoisten               |
| aurinkoinen+A+Pl+Gen              | aurinkoisten              |
| kokoinen+A+Pl+Gen                 | kokoisten                 |
| puolikokoinen+A+Pl+Gen            | puolikokoisten            |
| epäuskoinen+A+Pl+Gen              | epäuskoisten              |
| iloinen+A+Pl+Gen                  | iloisten                  |
| kiloinen+A+Pl+Gen                 | kiloisten                 |
| suloinen+A+Pl+Gen                 | suloisten                 |
| epäluuloinen+A+Pl+Gen             | epäluuloisten             |
| kivuloinen+A+Pl+Gen               | kivuloisten               |
| aikamoinen+A+Pl+Gen               | aikamoisten               |
| semmoinen+A+Pl+Gen                | semmoisten                |
| tuomoinen+A+Pl+Gen                | tuomoisten                |
| toinen+A+Pl+Gen                   | toisten                   |
| pitkävetoinen+A+Pl+Gen            | pitkävetoisten            |
| vapaaehtoinen+A+Pl+Gen            | vapaaehtoisten            |
| hyvämuistoinen+A+Pl+Gen           | hyvämuistoisten           |
| samanarvoinen+A+Pl+Gen            | samanarvoisten            |
| prototyyppinen+A+Pl+Gen           | prototyyppisten           |
| populaarinen+A+Pl+Gen             | populaaristen             |
| porvarinen+A+Pl+Gen               | porvaristen               |
| geneerinen+A+Pl+Gen               | geneeristen               |
| tummaverinen+A+Pl+Gen             | tummaveristen             |
| vihrinen+A+Pl+Gen                 | vihristen                 |
| kelta-vihrinen+A+Pl+Gen           | kelta-vihristen           |
| sini-vihrinen+A+Pl+Gen            | sini-vihristen            |
| obligatoorinen+A+Pl+Gen           | obligatooristen           |
| elektrinen+A+Pl+Gen               | elektristen               |
| pahankurinen+A+Pl+Gen             | pahankuristen             |
| hullunkurinen+A+Pl+Gen            | hullunkuristen            |
| kulttuurinen+A+Pl+Gen             | kulttuuristen             |
| färinen+A+Pl+Gen                  | färisten                  |
| erifärinen+A+Pl+Gen               | erifäristen               |
| samanfärinen+A+Pl+Gen             | samanfäristen             |
| vesinen+A+Pl+Gen                  | vesisten                  |
| kaksinen+A+Pl+Gen                 | kaksisten                 |
| kompleksinen+A+Pl+Gen             | kompleksisten             |
| pitkävarsinen+A+Pl+Gen            | pitkävarsisten            |
| saftinen+A+Pl+Gen                 | saftisten                 |
| syntaktinen+A+Pl+Gen              | syntaktisten              |
| entinen+A+Pl+Gen                  | entisten                  |
| syntinen+A+Pl+Gen                 | syntisten                 |
| läntinen+A+Pl+Gen                 | läntisten                 |
| totinen+A+Pl+Gen                  | totisten                  |
| vuotinen+A+Pl+Gen                 | vuotisten                 |
| dramaattinen+A+Pl+Gen             | dramaattisten             |
| systemaattinen+A+Pl+Gen           | systemaattisten           |
| symptomaattinen+A+Pl+Gen          | symptomaattisten          |
| sympaattinen+A+Pl+Gen             | sympaattisten             |
| konkreettinen+A+Pl+Gen            | konkreettisten            |
| poliittinen+A+Pl+Gen              | poliittisten              |
| polittinen+A+Pl+Gen               | polittisten               |
| pulittinen+A+Pl+Gen               | pulittisten               |
| neljenkanttinen+A+Pl+Gen          | neljenkanttisten          |
| kahđeksenkanttinen+A+Pl+Gen       | kahđeksenkanttisten       |
| neliskanttinen+A+Pl+Gen           | neliskanttisten           |
| semanttinen+A+Pl+Gen              | semanttisten              |
| romanttinen+A+Pl+Gen              | romanttisten              |
| identtinen+A+Pl+Gen               | identtisten               |
| yhđensorttinen+A+Pl+Gen           | yhđensorttisten           |
| uuđenaikhuinen+A+Pl+Gen           | uuđenaikhuisten           |
| mielhuinen+A+Pl+Gen               | mielhuisten               |
| ikuinen+A+Pl+Gen                  | ikuisten                  |
| pikkuinen+A+Pl+Gen                | pikkuisten                |
| harkkuinen+A+Pl+Gen               | harkkuisten               |
| korkuinen+A+Pl+Gen                | korkuisten                |
| suomensukuinen+A+Pl+Gen           | suomensukuisten           |
| luinen+A+Pl+Gen                   | luisten                   |
| viluinen+A+Pl+Gen                 | viluisten                 |
| hirmuinen+A+Pl+Gen                | hirmuisten                |
| sumuinen+A+Pl+Gen                 | sumuisten                 |
| hoppuinen+A+Pl+Gen                | hoppuisten                |
| sananloppuinen+A+Pl+Gen           | sananloppuisten           |
| vakituinen+A+Pl+Gen               | vakituisten               |
| omituinen+A+Pl+Gen                | omituisten                |
| pituinen+A+Pl+Gen                 | pituisten                 |
| vasituinen+A+Pl+Gen               | vasituisten               |
| joutuinen+A+Pl+Gen                | joutuisten                |
| usheempitavuinen+A+Pl+Gen         | usheempitavuisten         |
| kaksitavuinen+A+Pl+Gen            | kaksitavuisten            |
| yksitavuinen+A+Pl+Gen             | yksitavuisten             |
| skandinaavinen+A+Pl+Gen           | skandinaavisten           |
| passiivinen+A+Pl+Gen              | passiivisten              |
| abessiivinen+A+Pl+Gen             | abessiivisten             |
| kreatiivinen+A+Pl+Gen             | kreatiivisten             |
| nekatiivinen+A+Pl+Gen             | nekatiivisten             |
| administratiivinen+A+Pl+Gen       | administratiivisten       |
| kausatiivinen+A+Pl+Gen            | kausatiivisten            |
| primitiivinen+A+Pl+Gen            | primitiivisten            |
| positiivinen+A+Pl+Gen             | positiivisten             |
| pusitiivinen+A+Pl+Gen             | pusitiivisten             |
| aktiivinen+A+Pl+Gen               | aktiivisten               |
| effektiivinen+A+Pl+Gen            | effektiivisten            |
| konnektiivinen+A+Pl+Gen           | konnektiivisten           |
| fiktiivinen+A+Pl+Gen              | fiktiivisten              |
| disjunktiivinen+A+Pl+Gen          | disjunktiivisten          |
| kivinen+A+Pl+Gen                  | kivisten                  |
| pilvinen+A+Pl+Gen                 | pilvisten                 |
| rynkkyinen+A+Pl+Gen               | rynkkyisten               |
| nykyinen+A+Pl+Gen                 | nykyisten                 |
| pölyinen+A+Pl+Gen                 | pölyisten                 |
| erityinen+A+Pl+Gen                | erityisten                |
| ikhäinen+A+Pl+Gen                 | ikhäisten                 |
| keski-ikhäinen+A+Pl+Gen           | keski-ikhäisten           |
| alaikhäinen+A+Pl+Gen              | alaikhäisten              |
| vähäinen+A+Pl+Gen                 | vähäisten                 |
| alaikäinen+A+Pl+Gen               | alaikäisten               |
| reikäinen+A+Pl+Gen                | reikäisten                |
| koukkuselkäinen+A+Pl+Gen          | koukkuselkäisten          |
| koukkusölkäinen+A+Pl+Gen          | koukkusölkäisten          |
| ymmyrkäinen+A+Pl+Gen              | ymmyrkäisten              |
| lyhykäinen+A+Pl+Gen               | lyhykäisten               |
| äkäinen+A+Pl+Gen                  | äkäisten                  |
| itteläinen+A+Pl+Gen               | itteläisten               |
| briittiläinen+A+Pl+Gen            | briittiläisten            |
| pitkyläinen+A+Pl+Gen              | pitkyläisten              |
| yykeäläinen+A+Pl+Gen              | yykeäläisten              |
| pykejäläinen+A+Pl+Gen             | pykejäläisten             |
| tyskäläinen+A+Pl+Gen              | tyskäläisten              |
| venäläinen+A+Pl+Gen               | venäläisten               |
| ryssäläinen+A+Pl+Gen              | ryssäläisten              |
| likimäinen+A+Pl+Gen               | likimäisten               |
| jälkimäinen+A+Pl+Gen              | jälkimäisten              |
| keskimäinen+A+Pl+Gen              | keskimäisten              |
| täkimäinen+A+Pl+Gen               | täkimäisten               |
| ylimäinen+A+Pl+Gen                | ylimäisten                |
| päälimäinen+A+Pl+Gen              | päälimäisten              |
| ensimäinen+A+Pl+Gen               | ensimäisten               |
| tämmäinen+A+Pl+Gen                | tämmäisten                |
| pörämäinen+A+Pl+Gen               | pörämäisten               |
| ittenäinen+A+Pl+Gen               | ittenäisten               |
| äkkinäinen+A+Pl+Gen               | äkkinäisten               |
| yksinäinen+A+Pl+Gen               | yksinäisten               |
| ittepäinen+A+Pl+Gen               | ittepäisten               |
| kaljupäinen+A+Pl+Gen              | kaljupäisten              |
| ymmyräinen+A+Pl+Gen               | ymmyräisten               |
| alkupöräinen+A+Pl+Gen             | alkupöräisten             |
| pahasäinen+A+Pl+Gen               | pahasäisten               |
| sisäinen+A+Pl+Gen                 | sisäisten                 |
| öystäinen+A+Pl+Gen                | öystäisten                |
| myötäinen+A+Pl+Gen                | myötäisten                |
| tytyväinen+A+Pl+Gen               | tytyväisten               |
| näköinen+A+Pl+Gen                 | näköisten                 |
| pirunnäköinen+A+Pl+Gen            | pirunnäköisten            |
| tämmöinen+A+Pl+Gen                | tämmöisten                |
| vähätöinen+A+Pl+Gen               | vähätöisten               |
| kotitekonen+A+Pl+Gen              | kotitekosten              |
| louhikkonen+A+Pl+Gen              | louhikkosten              |
| pilkkonen+A+Pl+Gen                | pilkkosten                |
| puolikokonen+A+Pl+Gen             | puolikokosten             |
| semmonen+A+Pl+Gen                 | semmosten                 |
| tuomoinen+A+Pl+Gen                | tuomosten                 |
| vapaaehtonen+A+Pl+Gen             | vapaaehtosten             |
| kotonen+A+Pl+Gen                  | kotosten                  |
| ikunen+A+Pl+Gen                   | ikusten                   |
| pikkunen+A+Pl+Gen                 | pikkusten                 |
| harkkunen+A+Pl+Gen                | harkkusten                |
| vilunen+A+Pl+Gen                  | vilusten                  |
| hirmunen+A+Pl+Gen                 | hirmusten                 |
| rynkkynen+A+Pl+Gen                | rynkkysten                |
| nykynen+A+Pl+Gen                  | nykysten                  |
| pölynen+A+Pl+Gen                  | pölysten                  |
| vähänen+A+Pl+Gen                  | vähästen                  |
| alaikänen+A+Pl+Gen                | alaikästen                |
| äkänen+A+Pl+Gen                   | äkästen                   |
| tämmänen+A+Pl+Gen                 | tämmästen                 |
| alkupöränen+A+Pl+Gen              | alkupörästen              |
| sisänen+A+Pl+Gen                  | sisästen                  |
| näkönen+A+Pl+Gen                  | näkösten                  |
| pirunnäkönen+A+Pl+Gen             | pirunnäkösten             |
| pahas+A+Pl+Gen                    | pahhaitten                |
| puhelias+A+Pl+Gen                 | puhelihaitten             |
| laupias+A+Pl+Gen                  | laupihaitten              |
| kaikkivaltias+A+Pl+Gen            | kaikkivaltihaitten        |
| paljas+A+Pl+Gen                   | paljhaitten               |
| voimakas+A+Pl+Gen                 | voimakkhaitten            |
| rakas+A+Pl+Gen                    | rakkhaitten               |
| viekas+A+Pl+Gen                   | viekkhaitten              |
| onnekas+A+Pl+Gen                  | onnekkhaitten             |
| raikas+A+Pl+Gen                   | raikkhaitten              |
| vitamiinikas+A+Pl+Gen             | vitamiinikkhaitten        |
| rikas+A+Pl+Gen                    | rikkhaitten               |
| raharikas+A+Pl+Gen                | raharikkhaitten           |
| fantasiirikas+A+Pl+Gen            | fantasiirikkhaitten       |
| lajirikas+A+Pl+Gen                | lajirikkhaitten           |
| färirikas+A+Pl+Gen                | färirikkhaitten           |
| tietorikas+A+Pl+Gen               | tietorikkhaitten          |
| sađetrikas+A+Pl+Gen               | sađetrikkhaitten          |
| lapsikas+A+Pl+Gen                 | lapsikkhaitten            |
| praatikas+A+Pl+Gen                | praatikkhaitten           |
| vilkas+A+Pl+Gen                   | vilkkhaitten              |
| nerokas+A+Pl+Gen                  | nerokkhaitten             |
| arvokas+A+Pl+Gen                  | arvokkhaitten             |
| kirkas+A+Pl+Gen                   | kirkkhaitten              |
| liukas+A+Pl+Gen                   | liukkhaitten              |
| raskas+A+Pl+Gen                   | raskhaitten               |
| hurskas+A+Pl+Gen                  | hurskhaitten              |
| vanhurskas+A+Pl+Gen               | vanhurskhaitten           |
| joutilas+A+Pl+Gen                 | joutilhaitten             |
| armas+A+Pl+Gen                    | armhaitten                |
| vapaa+A+Pl+Gen                    | vaphaitten                |
| reipas+A+Pl+Gen                   | reipphaitten              |
| opas+A+Pl+Gen                     | opphaitten                |
| vieras+A+Pl+Gen                   | vierhaitten               |
| ventovieras+A+Pl+Gen              | ventovierhaitten          |
| sairas+A+Pl+Gen                   | sairhaitten               |
| viisas+A+Pl+Gen                   | viishaitten               |
| itteviisas+A+Pl+Gen               | itteviishaitten           |
| runsas+A+Pl+Gen                   | runshaitten               |
| karsas+A+Pl+Gen                   | karshaitten               |
| ahđas+A+Pl+Gen                    | ahthaitten                |
| puhđas+A+Pl+Gen                   | puhthaitten               |
| hiđas+A+Pl+Gen                    | hithaitten                |
| harras+A+Pl+Gen                   | harthaitten               |
| laatas+A+Pl+Gen                   | laatthaitten              |
| rietas+A+Pl+Gen                   | rietthaitten              |
| autuas+A+Pl+Gen                   | autuhaitten               |
| raavas+A+Pl+Gen                   | raavhaitten               |
| karvas+A+Pl+Gen                   | karvhaitten               |
| ehhee+A+Pl+Gen                    | ehheitten                 |
| tihhee+A+Pl+Gen                   | tihheitten                |
| kuolu+A+Pl+Gen                    | kuolheitten               |
| kokenu+A+Pl+Gen                   | kokenheitten              |
| ahnet+A+Pl+Gen                    | ahnheitten                |
| nainu+A+Pl+Gen                    | nainheitten               |
| tiinet+A+Pl+Gen                   | tiinheitten               |
| oppinu+A+Pl+Gen                   | oppinheitten              |
| ravistunnu+A+Pl+Gen               | ravistunnheitten          |
| hermostunnu+A+Pl+Gen              | hermostunnheitten         |
| hengestynny+A+Pl+Gen              | hengestynnheitten         |
| hengistynny+A+Pl+Gen              | hengistynnheitten         |
| vaipunu+A+Pl+Gen                  | vaipunheitten             |
| suuttunu+A+Pl+Gen                 | suuttunheitten            |
| väsyny+A+Pl+Gen                   | väsynheitten              |
| tuoret+A+Pl+Gen                   | tuorheitten               |
| ussee+A+Pl+Gen                    | usheitten                 |
| kauhhee+A+Pl+Gen                  | kauheitten                |
| tervet+A+Pl+Gen                   | tervheitten               |
| sakea+A+Pl+Gen                    | sakeitten                 |
| rohkee+A+Pl+Gen                   | rohkeitten                |
| laakkee+A+Pl+Gen                  | laakkeitten               |
| makkee+A+Pl+Gen                   | makkeitten                |
| sakkee+A+Pl+Gen                   | sakkeitten                |
| vaikkee+A+Pl+Gen                  | vaikkeitten               |
| oikkee+A+Pl+Gen                   | oikkeitten                |
| muikkee+A+Pl+Gen                  | muikkeitten               |
| valkkee+A+Pl+Gen                  | valkkeitten               |
| ilmivalkkee+A+Pl+Gen              | ilmivalkkeitten           |
| vitivalkkee+A+Pl+Gen              | vitivalkkeitten           |
| selkkee+A+Pl+Gen                  | selkkeitten               |
| ilkkee+A+Pl+Gen                   | ilkkeitten                |
| sokkee+A+Pl+Gen                   | sokkeitten                |
| huokkee+A+Pl+Gen                  | huokkeitten               |
| karkkee+A+Pl+Gen                  | karkkeitten               |
| korkkee+A+Pl+Gen                  | korkkeitten               |
| tärkkee+A+Pl+Gen                  | tärkkeitten               |
| aukkee+A+Pl+Gen                   | aukkeitten                |
| laukkee+A+Pl+Gen                  | laukkeitten               |
| korkea+A+Pl+Gen                   | korkeitten                |
| ruskea+A+Pl+Gen                   | ruskeitten                |
| ruskee+A+Pl+Gen                   | ruskeitten                |
| sitkee+A+Pl+Gen                   | sitkeitten                |
| notkee+A+Pl+Gen                   | notkeitten                |
| haalee+A+Pl+Gen                   | haaleitten                |
| vaalee+A+Pl+Gen                   | vaaleitten                |
| haalee+A+Pl+Gen                   | halleitten                |
| sillee+A+Pl+Gen                   | silleitten                |
| pehmee+A+Pl+Gen                   | pehmeitten                |
| himmee+A+Pl+Gen                   | himmeitten                |
| pimmee+A+Pl+Gen                   | pimmeitten                |
| pilkkapimmee+A+Pl+Gen             | pilkkapimmeitten          |
| säkkipimmee+A+Pl+Gen              | säkkipimmeitten           |
| syyspimmee+A+Pl+Gen               | syyspimmeitten            |
| kommee+A+Pl+Gen                   | kommeitten                |
| kirmee+A+Pl+Gen                   | kirmeitten                |
| ahnee+A+Pl+Gen                    | ahneitten                 |
| kappee+A+Pl+Gen                   | kappeitten                |
| rappee+A+Pl+Gen                   | rappeitten                |
| lieppee+A+Pl+Gen                  | lieppeitten               |
| kippee+A+Pl+Gen                   | kippeitten                |
| merikippee+A+Pl+Gen               | merikippeitten            |
| ylppee+A+Pl+Gen                   | ylppeitten                |
| noppee+A+Pl+Gen                   | noppeitten                |
| virree+A+Pl+Gen                   | virreitten                |
| korree+A+Pl+Gen                   | korreitten                |
| murree+A+Pl+Gen                   | murreitten                |
| pyöree+A+Pl+Gen                   | pyöreitten                |
| kalssee+A+Pl+Gen                  | kalsseitten               |
| kostee+A+Pl+Gen                   | kosteitten                |
| laattee+A+Pl+Gen                  | laatteitten               |
| kiinttee+A+Pl+Gen                 | kiintteitten              |
| hirvee+A+Pl+Gen                   | hirveitten                |
| kevvee+A+Pl+Gen                   | kevveitten                |
| levvee+A+Pl+Gen                   | levveitten                |
| oranši+A+Pl+Gen                   | oranšiitten               |
| kallis+A+Pl+Gen                   | kallhiitten               |
| valmis+A+Pl+Gen                   | valmhiitten               |
| kaunis+A+Pl+Gen                   | kaunhiitten               |
| tyyris+A+Pl+Gen                   | tyyrhiitten               |
| raitis+A+Pl+Gen                   | raitthiitten              |
| tivis+A+Pl+Gen                    | tivhiitten                |
| harmaaja+A+Pl+Gen                 | harmaajiitten             |
| hoppeeharmaaja+A+Pl+Gen           | hoppeeharmaajiitten       |
| ratikaali+A+Pl+Gen                | ratikaaliitten            |
| normaali+A+Pl+Gen                 | normaaliitten             |
| rekiunaali+A+Pl+Gen               | rekiunaaliitten           |
| liberaali+A+Pl+Gen                | liberaaliitten            |
| sentraali+A+Pl+Gen                | sentraaliitten            |
| hankala+A+Pl+Gen                  | hankaliitten              |
| kamala+A+Pl+Gen                   | kamaliitten               |
| matala+A+Pl+Gen                   | mataliitten               |
| kavala+A+Pl+Gen                   | kavaliitten               |
| happela+A+Pl+Gen                  | happeliitten              |
| simppeli+A+Pl+Gen                 | simppeliitten             |
| passeli+A+Pl+Gen                  | passeliitten              |
| ytelä+A+Pl+Gen                    | yteliitten                |
| veđenpillaama+A+Pl+Gen            | veđenpillaamiitten        |
| hapan+A+Pl+Gen                    | happamiitten              |
| ulosantama+A+Pl+Gen               | ulosantamiitten           |
| vasen+A+Pl+Gen                    | vasemiitten               |
| parhain+A+Pl+Gen                  | parhaimiitten             |
| irtain+A+Pl+Gen                   | irtaimiitten              |
| lämmin+A+Pl+Gen                   | lämpimiitten              |
| alaston+A+Pl+Gen                  | alastomiitten             |
| rauhaton+A+Pl+Gen                 | rauhattomiitten           |
| viaton+A+Pl+Gen                   | viattomiitten             |
| rajaton+A+Pl+Gen                  | rajattomiitten            |
| pohjaton+A+Pl+Gen                 | pohjattomiitten           |
| vijaton+A+Pl+Gen                  | vijattomiitten            |
| jumalaton+A+Pl+Gen                | jumalattomiitten          |
| vallaton+A+Pl+Gen                 | vallattomiitten           |
| saamaton+A+Pl+Gen                 | saamattomiitten           |
| mittaamaton+A+Pl+Gen              | mittaamattomiitten        |
| maksamaton+A+Pl+Gen               | maksamattomiitten         |
| perhäänantamaton+A+Pl+Gen         | perhäänantamattomiitten   |
| paistamaton+A+Pl+Gen              | paistamattomiitten        |
| luottamaton+A+Pl+Gen              | luottamattomiitten        |
| ajattelematon+A+Pl+Gen            | ajattelemattomiitten      |
| vaihettelematon+A+Pl+Gen          | vaihettelemattomiitten    |
| valettelematon+A+Pl+Gen           | valettelemattomiitten     |
| tottelematon+A+Pl+Gen             | tottelemattomiitten       |
| olematon+A+Pl+Gen                 | olemattomiitten           |
| tuntematon+A+Pl+Gen               | tuntemattomiitten         |
| naimaton+A+Pl+Gen                 | naimattomiitten           |
| huolimaton+A+Pl+Gen               | huolimattomiitten         |
| oppimaton+A+Pl+Gen                | oppimattomiitten          |
| vaatimaton+A+Pl+Gen               | vaatimattomiitten         |
| uskomaton+A+Pl+Gen                | uskomattomiitten          |
| liikkumaton+A+Pl+Gen              | liikkumattomiitten        |
| taipumaton+A+Pl+Gen               | taipumattomiitten         |
| loppumaton+A+Pl+Gen               | loppumattomiitten         |
| muuttumaton+A+Pl+Gen              | muuttumattomiitten        |
| herraton+A+Pl+Gen                 | herrattomiitten           |
| luvaton+A+Pl+Gen                  | luvattomiitten            |
| toimeton+A+Pl+Gen                 | toimettomiitten           |
| onneton+A+Pl+Gen                  | onnettomiitten            |
| ruokoton+A+Pl+Gen                 | ruokottomiitten           |
| uskoton+A+Pl+Gen                  | uskottomiitten            |
| armoton+A+Pl+Gen                  | armottomiitten            |
| painoton+A+Pl+Gen                 | painottomiitten           |
| levoton+A+Pl+Gen                  | levottomiitten            |
| kelvoton+A+Pl+Gen                 | kelvottomiitten           |
| arvoton+A+Pl+Gen                  | arvottomiitten            |
| mahđoton+A+Pl+Gen                 | mahđottomiitten           |
| loputon+A+Pl+Gen                  | loputtomiitten            |
| suruton+A+Pl+Gen                  | suruttomiitten            |
| avuton+A+Pl+Gen                   | avuttomiitten             |
| mavuton+A+Pl+Gen                  | mavuttomiitten            |
| hengetön+A+Pl+Gen                 | hengettömiitten           |
| äänetön+A+Pl+Gen                  | äänettömiitten            |
| pilvetön+A+Pl+Gen                 | pilvettömiitten           |
| färitön+A+Pl+Gen                  | färittömiitten            |
| hävitön+A+Pl+Gen                  | hävittömiitten            |
| hävytön+A+Pl+Gen                  | hävyttömiitten            |
| kykenemätön+A+Pl+Gen              | kykenemättömiitten        |
| kärsimätön+A+Pl+Gen               | kärsimättömiitten         |
| näkymätön+A+Pl+Gen                | näkymättömiitten          |
| tietämätön+A+Pl+Gen               | tietämättömiitten         |
| ymmärtämätön+A+Pl+Gen             | ymmärtämättömiitten       |
| välttämätön+A+Pl+Gen              | välttämättömiitten        |
| määrätön+A+Pl+Gen                 | määrättömiitten           |
| mitätön+A+Pl+Gen                  | mitättömiitten            |
| ihana+A+Pl+Gen                    | ihaniitten                |
| tyven+A+Pl+Gen                    | tyveniitten               |
| tinatyven+A+Pl+Gen                | tinatyveniitten           |
| naakkari+A+Pl+Gen                 | naakkariitten             |
| sikkari+A+Pl+Gen                  | sikkariitten              |
| ankara+A+Pl+Gen                   | ankariitten               |
| tieđonankara+A+Pl+Gen             | tieđonankariitten         |
| ahkera+A+Pl+Gen                   | ahkeriitten               |
| näpperä+A+Pl+Gen                  | näpperiitten              |
| höperä+A+Pl+Gen                   | höperiitten               |
| uuttera+A+Pl+Gen                  | uutteriitten              |
| kiverä+A+Pl+Gen                   | kiveriitten               |
| kippura+A+Pl+Gen                  | kippuriitten              |
| näppärä+A+Pl+Gen                  | näppäriitten              |
| primääri+A+Pl+Gen                 | primääriitten             |
| oransi+A+Pl+Gen                   | oransiitten               |
| oranssi+A+Pl+Gen                  | oranssiitten              |
| fioletti+A+Pl+Gen                 | fioletiitten              |
| ultrafioletti+A+Pl+Gen            | ultrafioletiitten         |
| interesantti+A+Pl+Gen             | interesantiitten          |
| ekvivalentti+A+Pl+Gen             | ekvivalentiitten          |
| auttii+A+Pl+Gen                   | auttiitten                |
| kirjaava+A+Pl+Gen                 | kirjaaviitten             |
| yhtheenhenkkaava+A+Pl+Gen         | yhtheenhenkkaaviitten     |
| seuraava+A+Pl+Gen                 | seuraaviitten             |
| mahtaava+A+Pl+Gen                 | mahtaaviitten             |
| loistaava+A+Pl+Gen                | loistaaviitten            |
| valttaava+A+Pl+Gen                | valttaaviitten            |
| virttaava+A+Pl+Gen                | virttaaviitten            |
| jouttaava+A+Pl+Gen                | jouttaaviitten            |
| lihava+A+Pl+Gen                   | lihaviitten               |
| vakava+A+Pl+Gen                   | vakaviitten               |
| mukava+A+Pl+Gen                   | mukaviitten               |
| painava+A+Pl+Gen                  | painaviitten              |
| herrattava+A+Pl+Gen               | herrattaviitten           |
| yhđentekkeevä+A+Pl+Gen            | yhđentekkeeviitten        |
| järkkeevä+A+Pl+Gen                | järkkeeviitten            |
| väkkeevä+A+Pl+Gen                 | väkkeeviitten             |
| pulleeva+A+Pl+Gen                 | pulleeviitten             |
| tulleeva+A+Pl+Gen                 | tulleeviitten             |
| soppiiva+A+Pl+Gen                 | soppiiviitten             |
| kärsiivä+A+Pl+Gen                 | kärsiiviitten             |
| nekatiivi+A+Pl+Gen                | nekatiiviitten            |
| primitiivi+A+Pl+Gen               | primitiiviitten           |
| puolikassuuva+A+Pl+Gen            | puolikassuuviitten        |
| leppääkassuuva+A+Pl+Gen           | leppääkassuuviitten       |
| tunttuuva+A+Pl+Gen                | tunttuuviitten            |
| ikävä+A+Pl+Gen                    | ikäviitten                |
| terävä+A+Pl+Gen                   | teräviitten               |
| veđenpitävä+A+Pl+Gen              | veđenpitäviitten          |
| syötävä+A+Pl+Gen                  | syötäviitten              |
| elläävä+A+Pl+Gen                  | ellääviitten              |
| ymmärettäävä+A+Pl+Gen             | ymmärettääviitten         |
| jännittäävä+A+Pl+Gen              | jännittääviitten          |
| kiilttäävä+A+Pl+Gen               | kiilttääviitten           |
| virkistyttäävä+A+Pl+Gen           | virkistyttääviitten       |
| mainio+A+Pl+Gen                   | mainioitten               |
| ilakka+A+Pl+Gen                   | ilakoitten                |
| suipero+A+Pl+Gen                  | suiperoitten              |
| kuvailtu+A+Pl+Gen                 | kuvailuitten              |
| liehmuu+A+Pl+Gen                  | liehmuitten               |
| merkattu+A+Pl+Gen                 | merkatuitten              |
| maalattu+A+Pl+Gen                 | maalatuitten              |
| ulkokullattu+A+Pl+Gen             | ulkokullatuitten          |
| kevveestisuolattu+A+Pl+Gen        | kevveestisuolatuitten     |
| siunattu+A+Pl+Gen                 | siunatuitten              |
| tunnettu+A+Pl+Gen                 | tunnetuitten              |
| opetettu+A+Pl+Gen                 | opetetuitten              |
| valittu+A+Pl+Gen                  | valituitten               |
| vasittu+A+Pl+Gen                  | vasituitten               |
| kattottu+A+Pl+Gen                 | kattotuitten              |
| kotonakuottu+A+Pl+Gen             | kotonakuotuitten          |
| merkittävä+A+Pl+Gen               | merkittävitten            |
| kärys+A+Pl+Gen                    | kärhyitten                |
| niinkäsketty+A+Pl+Gen             | niinkäsketyitten          |
| kylmetty+A+Pl+Gen                 | kylmetyitten              |
| pyhitetty+A+Pl+Gen                | pyhitetyitten             |
| käytetty+A+Pl+Gen                 | käytetyitten              |
| kristitty+A+Pl+Gen                | kristityitten             |
| määrätty+A+Pl+Gen                 | määrätyitten              |
| präntätty+A+Pl+Gen                | präntätyitten             |
| sinnikäs+A+Pl+Gen                 | sinnikkhäitten            |
| epävarma+A+Pl+Gen                 | epävarmain                |
| pyhä+A+Pl+Gen                     | pyhhiin                   |
| vähä+A+Pl+Gen                     | vähhiin                   |
| turha+A+Pl+Gen                    | turhiin                   |
| tyyhä+A+Pl+Gen                    | tyyhiin                   |
| köyhä+A+Pl+Gen                    | köyhiin                   |
| löyhä+A+Pl+Gen                    | löyhiin                   |
| tyhjä+A+Pl+Gen                    | tyhjiin                   |
| luja+A+Pl+Gen                     | lujjiin                   |
| väljä+A+Pl+Gen                    | väljiin                   |
| hurja+A+Pl+Gen                    | hurjiin                   |
| kurja+A+Pl+Gen                    | kurjiin                   |
| fakki+A+Pl+Gen                    | fakkiin                   |
| hoikka+A+Pl+Gen                   | hoikkiin                  |
| pelkkä+A+Pl+Gen                   | pelkkiin                  |
| plankki+A+Pl+Gen                  | plankkiin                 |
| flinkki+A+Pl+Gen                  | flinkkiin                 |
| synkkä+A+Pl+Gen                   | synkkiin                  |
| herkkä+A+Pl+Gen                   | herkkiin                  |
| jyrkkä+A+Pl+Gen                   | jyrkkiin                  |
| nyrkkä+A+Pl+Gen                   | nyrkkiin                  |
| märkä+A+Pl+Gen                    | märkkiin                  |
| läpimärkä+A+Pl+Gen                | läpimärkkiin              |
| soukka+A+Pl+Gen                   | soukkiin                  |
| nuuka+A+Pl+Gen                    | nuukkiin                  |
| mykkä+A+Pl+Gen                    | mykkiin                   |
| pitkä+A+Pl+Gen                    | pitkiin                   |
| villi+A+Pl+Gen                    | villiin                   |
| sula+A+Pl+Gen                     | sulliin                   |
| puoli+A+Pl+Gen                    | puoliin                   |
| käsipuoli+A+Pl+Gen                | käsipuoliin               |
| silmäpuoli+A+Pl+Gen               | silmäpuoliin              |
| hööli+A+Pl+Gen                    | hööliin                   |
| hapan+A+Pl+Gen                    | happamiin                 |
| vasen+A+Pl+Gen                    | vasemiin                  |
| tyhmä+A+Pl+Gen                    | tyhmiin                   |
| parhain+A+Pl+Gen                  | parhaimiin                |
| lämmin+A+Pl+Gen                   | lämpimiin                 |
| kylmä+A+Pl+Gen                    | kylmiin                   |
| jääkylmä+A+Pl+Gen                 | jääkylmiin                |
| oma+A+Pl+Gen                      | ommiin                    |
| soma+A+Pl+Gen                     | sommiin                   |
| kumma+A+Pl+Gen                    | kummiin                   |
| ruma+A+Pl+Gen                     | rummiin                   |
| tumma+A+Pl+Gen                    | tummiin                   |
| alaston+A+Pl+Gen                  | alastomiin                |
| rauhaton+A+Pl+Gen                 | rauhattomiin              |
| viaton+A+Pl+Gen                   | viattomiin                |
| rajaton+A+Pl+Gen                  | rajattomiin               |
| pohjaton+A+Pl+Gen                 | pohjattomiin              |
| vijaton+A+Pl+Gen                  | vijattomiin               |
| jumalaton+A+Pl+Gen                | jumalattomiin             |
| vallaton+A+Pl+Gen                 | vallattomiin              |
| saamaton+A+Pl+Gen                 | saamattomiin              |
| mittaamaton+A+Pl+Gen              | mittaamattomiin           |
| maksamaton+A+Pl+Gen               | maksamattomiin            |
| perhäänantamaton+A+Pl+Gen         | perhäänantamattomiin      |
| paistamaton+A+Pl+Gen              | paistamattomiin           |
| luottamaton+A+Pl+Gen              | luottamattomiin           |
| ajattelematon+A+Pl+Gen            | ajattelemattomiin         |
| vaihettelematon+A+Pl+Gen          | vaihettelemattomiin       |
| valettelematon+A+Pl+Gen           | valettelemattomiin        |
| tottelematon+A+Pl+Gen             | tottelemattomiin          |
| olematon+A+Pl+Gen                 | olemattomiin              |
| tuntematon+A+Pl+Gen               | tuntemattomiin            |
| naimaton+A+Pl+Gen                 | naimattomiin              |
| huolimaton+A+Pl+Gen               | huolimattomiin            |
| oppimaton+A+Pl+Gen                | oppimattomiin             |
| vaatimaton+A+Pl+Gen               | vaatimattomiin            |
| uskomaton+A+Pl+Gen                | uskomattomiin             |
| liikkumaton+A+Pl+Gen              | liikkumattomiin           |
| taipumaton+A+Pl+Gen               | taipumattomiin            |
| loppumaton+A+Pl+Gen               | loppumattomiin            |
| muuttumaton+A+Pl+Gen              | muuttumattomiin           |
| herraton+A+Pl+Gen                 | herrattomiin              |
| luvaton+A+Pl+Gen                  | luvattomiin               |
| toimeton+A+Pl+Gen                 | toimettomiin              |
| onneton+A+Pl+Gen                  | onnettomiin               |
| ruokoton+A+Pl+Gen                 | ruokottomiin              |
| uskoton+A+Pl+Gen                  | uskottomiin               |
| armoton+A+Pl+Gen                  | armottomiin               |
| painoton+A+Pl+Gen                 | painottomiin              |
| levoton+A+Pl+Gen                  | levottomiin               |
| kelvoton+A+Pl+Gen                 | kelvottomiin              |
| arvoton+A+Pl+Gen                  | arvottomiin               |
| mahđoton+A+Pl+Gen                 | mahđottomiin              |
| loputon+A+Pl+Gen                  | loputtomiin               |
| suruton+A+Pl+Gen                  | suruttomiin               |
| avuton+A+Pl+Gen                   | avuttomiin                |
| mavuton+A+Pl+Gen                  | mavuttomiin               |
| kuuma+A+Pl+Gen                    | kuumiin                   |
| hengetön+A+Pl+Gen                 | hengettömiin              |
| äänetön+A+Pl+Gen                  | äänettömiin               |
| pilvetön+A+Pl+Gen                 | pilvettömiin              |
| färitön+A+Pl+Gen                  | färittömiin               |
| hävitön+A+Pl+Gen                  | hävittömiin               |
| hävytön+A+Pl+Gen                  | hävyttömiin               |
| kykenemätön+A+Pl+Gen              | kykenemättömiin           |
| kärsimätön+A+Pl+Gen               | kärsimättömiin            |
| näkymätön+A+Pl+Gen                | näkymättömiin             |
| tietämätön+A+Pl+Gen               | tietämättömiin            |
| ymmärtämätön+A+Pl+Gen             | ymmärtämättömiin          |
| välttämätön+A+Pl+Gen              | välttämättömiin           |
| määrätön+A+Pl+Gen                 | määrättömiin              |
| mitätön+A+Pl+Gen                  | mitättömiin               |
| pieni+A+Pl+Gen                    | pieniin                   |
| kleini+A+Pl+Gen                   | kleiniin                  |
| fiini+A+Pl+Gen                    | fiiniin                   |
| moni+A+Pl+Gen                     | monniin                   |
| pruuni+A+Pl+Gen                   | pruuniin                  |
| seppä+A+Pl+Gen                    | seppiin                   |
| umpi+A+Pl+Gen                     | umppiin                   |
| klaari+A+Pl+Gen                   | klaariin                  |
| nuori+A+Pl+Gen                    | nuoriin                   |
| suora+A+Pl+Gen                    | suoriin                   |
| pystösuora+A+Pl+Gen               | pystösuoriin              |
| suuri+A+Pl+Gen                    | suuriin                   |
| käyrä+A+Pl+Gen                    | käyriin                   |
| nöyrä+A+Pl+Gen                    | nöyriin                   |
| väärä+A+Pl+Gen                    | vääriin                   |
| käpsä+A+Pl+Gen                    | käpsiin                   |
| näpsä+A+Pl+Gen                    | näpsiin                   |
| sisä+A+Pl+Gen                     | sissiin                   |
| vissi+A+Pl+Gen                    | vissiin                   |
| epävissi+A+Pl+Gen                 | epävissiin                |
| tylsä+A+Pl+Gen                    | tylssiin                  |
| tosi+A+Pl+Gen                     | tossiin                   |
| uusi+A+Pl+Gen                     | uussiin                   |
| täysi+A+Pl+Gen                    | täyssiin                  |
| löysä+A+Pl+Gen                    | löyssiin                  |
| siisti+A+Pl+Gen                   | siistiin                  |
| musta+A+Pl+Gen                    | mustiin                   |
| pikimusta+A+Pl+Gen                | pikimustiin               |
| mätä+A+Pl+Gen                     | mättiin                   |
| ryöttä+A+Pl+Gen                   | ryöttiin                  |
| söötti+A+Pl+Gen                   | sööttiin                  |
| lievä+A+Pl+Gen                    | lieviin                   |
| sievä+A+Pl+Gen                    | sieviin                   |
| tyhvä+A+Pl+Gen                    | tyhviin                   |
| loiva+A+Pl+Gen                    | loiviin                   |
| kuiva+A+Pl+Gen                    | kuiviin                   |
| selvä+A+Pl+Gen                    | selviin                   |
| epäselvä+A+Pl+Gen                 | epäselviin                |
| pälvi+A+Pl+Gen                    | pälviin                   |
| krouvi+A+Pl+Gen                   | krouviin                  |
| kova+A+Pl+Gen                     | kovviin                   |
| hyvä+A+Pl+Gen                     | hyvviin                   |
| syvä+A+Pl+Gen                     | syvviin                   |
| härski+A+Pl+Gen                   | härskin                   |
| himmi+A+Pl+Gen                    | himmin                    |
| laho+A+Pl+Gen                     | lahhoin                   |
| paha+A+Pl+Gen                     | pahhoin                   |
| laiha+A+Pl+Gen                    | laihoin                   |
| vanhaa+A+Pl+Gen                   | vanhoin                   |
| lauha+A+Pl+Gen                    | lauhoin                   |
| laaja+A+Pl+Gen                    | laajoin                   |
| taaja+A+Pl+Gen                    | taajoin                   |
| ujo+A+Pl+Gen                      | ujjoin                    |
| raaka+A+Pl+Gen                    | raakkoin                  |
| heikko+A+Pl+Gen                   | heikkoin                  |
| liika+A+Pl+Gen                    | liikkoin                  |
| silko+A+Pl+Gen                    | silkkoin                  |
| ulko+A+Pl+Gen                     | ulkkoin                   |
| vankka+A+Pl+Gen                   | vankkoin                  |
| arka+A+Pl+Gen                     | arkkoin                   |
| pimmeenarka+A+Pl+Gen              | pimmeenarkkoin            |
| tarkka+A+Pl+Gen                   | tarkkoin                  |
| tiukka+A+Pl+Gen                   | tiukkoin                  |
| laiska+A+Pl+Gen                   | laiskoin                  |
| hauska+A+Pl+Gen                   | hauskoin                  |
| kaalo+A+Pl+Gen                    | kaaloin                   |
| siila+A+Pl+Gen                    | siiloin                   |
| kolo+A+Pl+Gen                     | kolloin                   |
| tollo+A+Pl+Gen                    | tolloin                   |
| lama+A+Pl+Gen                     | lammoin                   |
| varma+A+Pl+Gen                    | varmoin                   |
| hieno+A+Pl+Gen                    | hienoin                   |
| kehno+A+Pl+Gen                    | kehnoin                   |
| huono+A+Pl+Gen                    | huonoin                   |
| halpa+A+Pl+Gen                    | halppoin                  |
| helppo+A+Pl+Gen                   | helppoin                  |
| juoppo+A+Pl+Gen                   | juoppoin                  |
| saura+A+Pl+Gen                    | sauroin                   |
| kuuro+A+Pl+Gen                    | kuuroin                   |
| lakso+A+Pl+Gen                    | laksoin                   |
| iso+A+Pl+Gen                      | issoin                    |
| fasta+A+Pl+Gen                    | fastoin                   |
| vaisto+A+Pl+Gen                   | vaistoin                  |
| pisto+A+Pl+Gen                    | pistoin                   |
| visto+A+Pl+Gen                    | vistoin                   |
| kaltto+A+Pl+Gen                   | kalttoin                  |
| viinto+A+Pl+Gen                   | viinttoin                 |
| ontto+A+Pl+Gen                    | onttoin                   |
| outo+A+Pl+Gen                     | outtoin                   |
| rutto+A+Pl+Gen                    | ruttoin                   |
| vahva+A+Pl+Gen                    | vahvoin                   |
| siivo+A+Pl+Gen                    | siivoin                   |
| harva+A+Pl+Gen                    | harvoin                   |
| kiva+A+Pl+Gen                     | kivvoin                   |
| eri+A+Pl+Gen                      | erin                      |
| raju+A+Pl+Gen                     | rajjuin                   |
| kalju+A+Pl+Gen                    | kaljuin                   |
| virkku+A+Pl+Gen                   | virkkuin                  |
| hullu+A+Pl+Gen                    | hulluin                   |
| sotahullu+A+Pl+Gen                | sotahulluin               |
| kuulu+A+Pl+Gen                    | kuuluin                   |
| lamu+A+Pl+Gen                     | lammuin                   |
| karu+A+Pl+Gen                     | karruin                   |
| paksu+A+Pl+Gen                    | paksuin                   |
| kesu+A+Pl+Gen                     | kessuin                   |
| visu+A+Pl+Gen                     | vissuin                   |
| kalsu+A+Pl+Gen                    | kalssuin                  |
| kranttu+A+Pl+Gen                  | kranttuin                 |
| koutu+A+Pl+Gen                    | kouttuin                  |
| tuttu+A+Pl+Gen                    | tuttuin                   |
| häijy+A+Pl+Gen                    | häijyin                   |
| syyry+A+Pl+Gen                    | syyryin                   |
| kypsy+A+Pl+Gen                    | kypsyin                   |
| pystö+A+Pl+Gen                    | pystöin                   |
