|                             |                             |
|-----------------------------|-----------------------------|
| mie+Pron+Pers+Sg1+Nom       | mie                         |
| mie+Pron+Pers+Sg1+Gen       | mun                         |
| mie+Pron+Pers+Sg1+Gen       | minun                       |
| mie+Pron+Pers+Sg1+Ill       | minhuun                     |
| mie+Pron+Pers+Sg1+Par       | minnuu                      |
| mie+Pron+Pers+Sg1+Ess       | minuna                      |
| mie+Pron+Pers+Sg1+Tra       | minuksi                     |
| mie+Pron+Pers+Sg1+Ine       | minussa                     |
| mie+Pron+Pers+Sg1+Ela       | minusta                     |
| mie+Pron+Pers+Sg1+All       | mulle                       |
| mie+Pron+Pers+Sg1+All       | minule                      |
| mie+Pron+Pers+Sg1+Ade       | mulla                       |
| mie+Pron+Pers+Sg1+Ade       | minula                      |
| mie+Pron+Pers+Sg1+Abl       | multa                       |
| mie+Pron+Pers+Sg1+Abl       | minulta                     |
| mie+Pron+Pers+Sg1+Abe       | minutta                     |
| sie+Pron+Pers+Sg2+Nom       | sie                         |
| sie+Pron+Pers+Sg2+Gen       | sun                         |
| sie+Pron+Pers+Sg2+Gen       | sinun                       |
| sie+Pron+Pers+Sg2+Ill       | sinhuun                     |
| sie+Pron+Pers+Sg2+Par       | sinnuu                      |
| sie+Pron+Pers+Sg2+Ess       | sinuna                      |
| sie+Pron+Pers+Sg2+Tra       | sinuksi                     |
| sie+Pron+Pers+Sg2+Ine       | sinussa                     |
| sie+Pron+Pers+Sg2+Ela       | sinusta                     |
| sie+Pron+Pers+Sg2+All       | sulle                       |
| sie+Pron+Pers+Sg2+All       | sinule                      |
| sie+Pron+Pers+Sg2+Ade       | sulla                       |
| sie+Pron+Pers+Sg2+Ade       | sinula                      |
| sie+Pron+Pers+Sg2+Abl       | sulta                       |
| sie+Pron+Pers+Sg2+Abl       | sinulta                     |
| sie+Pron+Pers+Sg2+Abe       | sinutta                     |
| hän+Pron+Pers+Sg3+Nom       | hän                         |
| hän+Pron+Pers+Sg3+Gen       | hänen                       |
| hän+Pron+Pers+Sg3+Ill       | hänheen                     |
| hän+Pron+Pers+Sg3+Par       | häntä                       |
| hän+Pron+Pers+Sg3+Ess       | hänenä                      |
| hän+Pron+Pers+Sg3+Tra       | häneksi                     |
| hän+Pron+Pers+Sg3+Ine       | hänessä                     |
| hän+Pron+Pers+Sg3+Ela       | hänestä                     |
| hän+Pron+Pers+Sg3+All       | hänele                      |
| hän+Pron+Pers+Sg3+Ade       | hänelä                      |
| hän+Pron+Pers+Sg3+Abl       | häneltä                     |
| hän+Pron+Pers+Sg3+Abe       | hänettä                     |
| se+Pron+Pers+Sg3+Nom        | se                          |
| se+Pron+Pers+Sg3+Gen        | sen                         |
| se+Pron+Pers+Sg3+Ill        | siiheen                     |
| se+Pron+Pers+Sg3+Par        | sitä                        |
| se+Pron+Pers+Sg3+Ess        | sinä                        |
| se+Pron+Pers+Sg3+Tra        | siksi                       |
| se+Pron+Pers+Sg3+Ine        | siinä                       |
| se+Pron+Pers+Sg3+Ela        | siitä                       |
| se+Pron+Pers+Sg3+All        | sille                       |
| se+Pron+Pers+Sg3+Ade        | sillä                       |
| se+Pron+Pers+Sg3+Abl        | siltä                       |
| se+Pron+Pers+Sg3+Abe        | se+Pron+Pers+Sg3+Abe        |
| met+Pron+Pers+Pl1+Nom       | met                         |
| met+Pron+Pers+Pl1+Gen       | meiđän                      |
| met+Pron+Pers+Pl1+Ill       | meihiin                     |
| met+Pron+Pers+Pl1+Par       | meitä                       |
| met+Pron+Pers+Pl1+Ess       | meinä                       |
| met+Pron+Pers+Pl1+Tra       | meiksi                      |
| met+Pron+Pers+Pl1+Ine       | meissä                      |
| met+Pron+Pers+Pl1+Ela       | meistä                      |
| met+Pron+Pers+Pl1+All       | meile                       |
| met+Pron+Pers+Pl1+Ade       | meilä                       |
| met+Pron+Pers+Pl1+Abl       | meiltä                      |
| met+Pron+Pers+Pl1+Abe       | meittä                      |
| tet+Pron+Pers+Pl2+Nom       | tet                         |
| tet+Pron+Pers+Pl2+Gen       | teiđän                      |
| tet+Pron+Pers+Pl2+Ill       | teihiin                     |
| tet+Pron+Pers+Pl2+Par       | teitä                       |
| tet+Pron+Pers+Pl2+Ess       | teinä                       |
| tet+Pron+Pers+Pl2+Tra       | teiksi                      |
| tet+Pron+Pers+Pl2+Ine       | teissä                      |
| tet+Pron+Pers+Pl2+Ela       | teistä                      |
| tet+Pron+Pers+Pl2+All       | teile                       |
| tet+Pron+Pers+Pl2+Ade       | teilä                       |
| tet+Pron+Pers+Pl2+Abl       | teiltä                      |
| tet+Pron+Pers+Pl2+Abe       | teittä                      |
| het+Pron+Pers+Pl3+Nom       | het                         |
| het+Pron+Pers+Pl3+Gen       | heiđän                      |
| het+Pron+Pers+Pl3+Ill       | heihiin                     |
| het+Pron+Pers+Pl3+Par       | heitä                       |
| het+Pron+Pers+Pl3+Ess       | heinä                       |
| het+Pron+Pers+Pl3+Tra       | heiksi                      |
| het+Pron+Pers+Pl3+Ine       | heissä                      |
| het+Pron+Pers+Pl3+Ela       | heistä                      |
| het+Pron+Pers+Pl3+All       | heile                       |
| het+Pron+Pers+Pl3+Ade       | heilä                       |
| het+Pron+Pers+Pl3+Abl       | heiltä                      |
| het+Pron+Pers+Pl3+Abe       | heittä                      |
| net+Pron+Pers+Pl3+Nom       | net                         |
| net+Pron+Pers+Pl3+Gen       | niitten                     |
| net+Pron+Pers+Pl3+Ill       | niihiin                     |
| net+Pron+Pers+Pl3+Par       | niitä                       |
| net+Pron+Pers+Pl3+Ess       | niinä                       |
| net+Pron+Pers+Pl3+Tra       | niiksi                      |
| net+Pron+Pers+Pl3+Ine       | niissä                      |
| net+Pron+Pers+Pl3+Ela       | niistä                      |
| net+Pron+Pers+Pl3+All       | niile                       |
| net+Pron+Pers+Pl3+Ade       | niilä                       |
| net+Pron+Pers+Pl3+Abl       | niiltä                      |
| net+Pron+Pers+Pl3+Abe       | niittä                      |
| tämä+Pron+Dem+Sg+Nom        | tämä                        |
| tämä+Pron+Dem+Sg+Gen        | tämän                       |
| tämä+Pron+Dem+Sg+Ill        | tähän                       |
| tämä+Pron+Dem+Sg+Par        | tätä                        |
| tämä+Pron+Dem+Sg+Ess        | tänä                        |
| tämä+Pron+Dem+Sg+Ess        | tänä                        |
| tämä+Pron+Dem+Sg+Tra        | täksi                       |
| tämä+Pron+Dem+Sg+Ine        | tässä                       |
| tämä+Pron+Dem+Sg+Ela        | tästä                       |
| tämä+Pron+Dem+Sg+All        | tälle                       |
| tämä+Pron+Dem+Sg+Ade        | tällä                       |
| tämä+Pron+Dem+Sg+Abl        | tältä                       |
| tämä+Pron+Dem+Sg+Abe        | tämä+Pron+Dem+Sg+Abe        |
| tuo+Pron+Dem+Sg+Nom         | tuo                         |
| tuo+Pron+Dem+Sg+Gen         | tuon                        |
| tuo+Pron+Dem+Sg+Ill         | tuohon                      |
| tuo+Pron+Dem+Sg+Par         | tuota                       |
| tuo+Pron+Dem+Sg+Ess         | tuona                       |
| tuo+Pron+Dem+Sg+Tra         | tuoksi                      |
| tuo+Pron+Dem+Sg+Ine         | tuossa                      |
| tuo+Pron+Dem+Sg+Ela         | tuosta                      |
| tuo+Pron+Dem+Sg+All         | tuole                       |
| tuo+Pron+Dem+Sg+Ade         | tuola                       |
| tuo+Pron+Dem+Sg+Abl         | tuolta                      |
| tuo+Pron+Dem+Sg+Abe         | tuo+Pron+Dem+Sg+Abe         |
| se+Pron+Dem+Sg+Nom          | se                          |
| se+Pron+Dem+Sg+Gen          | sen                         |
| se+Pron+Dem+Sg+Ill          | siiheen                     |
| se+Pron+Dem+Sg+Par          | sitä                        |
| se+Pron+Dem+Sg+Ess          | sinä                        |
| se+Pron+Dem+Sg+Tra          | siksi                       |
| se+Pron+Dem+Sg+Ine          | siinä                       |
| se+Pron+Dem+Sg+Ela          | siitä                       |
| se+Pron+Dem+Sg+All          | sille                       |
| se+Pron+Dem+Sg+Ade          | sillä                       |
| se+Pron+Dem+Sg+Abl          | siltä                       |
| se+Pron+Dem+Sg+Abe          | se+Pron+Dem+Sg+Abe          |
| nämät+Pron+Dem+Nom          | nämät+Pron+Dem+Nom          |
| nämät+Pron+Dem+Gen          | nämät+Pron+Dem+Gen          |
| nämät+Pron+Dem+Ill          | nämät+Pron+Dem+Ill          |
| nämät+Pron+Dem+Par          | nämät+Pron+Dem+Par          |
| nämät+Pron+Dem+Ess          | nämät+Pron+Dem+Ess          |
| nämät+Pron+Dem+Tra          | nämät+Pron+Dem+Tra          |
| nämät+Pron+Dem+Ine          | nämät+Pron+Dem+Ine          |
| nämät+Pron+Dem+Ela          | nämät+Pron+Dem+Ela          |
| nämät+Pron+Dem+All          | nämät+Pron+Dem+All          |
| nämät+Pron+Dem+Ade          | nämät+Pron+Dem+Ade          |
| nämät+Pron+Dem+Abl          | nämät+Pron+Dem+Abl          |
| nämät+Pron+Dem+Abe          | nämät+Pron+Dem+Abe          |
| nuot+Pron+Dem+Nom           | nuot+Pron+Dem+Nom           |
| nuot+Pron+Dem+Gen           | nuot+Pron+Dem+Gen           |
| nuot+Pron+Dem+Ill           | nuot+Pron+Dem+Ill           |
| nuot+Pron+Dem+Par           | nuot+Pron+Dem+Par           |
| nuot+Pron+Dem+Ess           | nuot+Pron+Dem+Ess           |
| nuot+Pron+Dem+Tra           | nuot+Pron+Dem+Tra           |
| nuot+Pron+Dem+Ine           | nuot+Pron+Dem+Ine           |
| nuot+Pron+Dem+Ela           | nuot+Pron+Dem+Ela           |
| nuot+Pron+Dem+All           | nuot+Pron+Dem+All           |
| nuot+Pron+Dem+Ade           | nuot+Pron+Dem+Ade           |
| nuot+Pron+Dem+Abl           | nuot+Pron+Dem+Abl           |
| nuot+Pron+Dem+Abe           | nuot+Pron+Dem+Abe           |
| net+Pron+Dem+Nom            | net+Pron+Dem+Nom            |
| net+Pron+Dem+Gen            | net+Pron+Dem+Gen            |
| net+Pron+Dem+Ill            | net+Pron+Dem+Ill            |
| net+Pron+Dem+Par            | net+Pron+Dem+Par            |
| net+Pron+Dem+Ess            | net+Pron+Dem+Ess            |
| net+Pron+Dem+Tra            | net+Pron+Dem+Tra            |
| net+Pron+Dem+Ine            | net+Pron+Dem+Ine            |
| net+Pron+Dem+Ela            | net+Pron+Dem+Ela            |
| net+Pron+Dem+All            | net+Pron+Dem+All            |
| net+Pron+Dem+Ade            | net+Pron+Dem+Ade            |
| net+Pron+Dem+Abl            | net+Pron+Dem+Abl            |
| net+Pron+Dem+Abe            | net+Pron+Dem+Abe            |
| kuka+Pron+Interr+Sg+Nom     | kuka                        |
| kuka+Pron+Interr+Sg+Gen     | kenen                       |
| kuka+Pron+Interr+Sg+Gen     | kenenkä                     |
| kuka+Pron+Interr+Sg+Ill     | kenheen                     |
| kuka+Pron+Interr+Sg+Par     | ketä                        |
| kuka+Pron+Interr+Sg+Ess     | kenenä                      |
| kuka+Pron+Interr+Sg+Tra     | keneksi                     |
| kuka+Pron+Interr+Sg+Ine     | kenessä                     |
| kuka+Pron+Interr+Sg+Ela     | kenestä                     |
| kuka+Pron+Interr+Sg+All     | kelle                       |
| kuka+Pron+Interr+Sg+All     | kenele                      |
| kuka+Pron+Interr+Sg+Ade     | kellä                       |
| kuka+Pron+Interr+Sg+Ade     | kenelä                      |
| kuka+Pron+Interr+Sg+Abl     | keltä                       |
| kuka+Pron+Interr+Sg+Abl     | keneltä                     |
| kuka+Pron+Interr+Sg+Abe     | kuka+Pron+Interr+Sg+Abe     |
| kuka+Pron+Interr+Pl+Nom     | kukka                       |
| kuka+Pron+Interr+Pl+Nom     | kekkä                       |
| kuka+Pron+Interr+Pl+Gen     | kenen                       |
| kuka+Pron+Interr+Pl+Gen     | kenenkä                     |
| kuka+Pron+Interr+Pl+Ill     | kenheen                     |
| kuka+Pron+Interr+Pl+Par     | ketä                        |
| kuka+Pron+Interr+Pl+Par     | keitä                       |
| kuka+Pron+Interr+Pl+Ess     | kenenä                      |
| kuka+Pron+Interr+Pl+Tra     | keneksi                     |
| kuka+Pron+Interr+Pl+Ine     | kenessä                     |
| kuka+Pron+Interr+Pl+Ela     | kenestä                     |
| kuka+Pron+Interr+Pl+All     | kelle                       |
| kuka+Pron+Interr+Pl+All     | kenele                      |
| kuka+Pron+Interr+Pl+Ade     | kellä                       |
| kuka+Pron+Interr+Pl+Ade     | kenelä                      |
| kuka+Pron+Interr+Pl+Abl     | keltä                       |
| kuka+Pron+Interr+Pl+Abl     | keneltä                     |
| kuka+Pron+Interr+Pl+Abe     | kuka+Pron+Interr+Pl+Abe     |
| mikä+Pron+Interr+Nom        | mikä+Pron+Interr+Nom        |
| mikä+Pron+Interr+Gen        | mikä+Pron+Interr+Gen        |
| mikä+Pron+Interr+Ill        | mikä+Pron+Interr+Ill        |
| mikä+Pron+Interr+Par        | mikä+Pron+Interr+Par        |
| mikä+Pron+Interr+Ess        | mikä+Pron+Interr+Ess        |
| mikä+Pron+Interr+Tra        | mikä+Pron+Interr+Tra        |
| mikä+Pron+Interr+Ine        | mikä+Pron+Interr+Ine        |
| mikä+Pron+Interr+Ela        | mikä+Pron+Interr+Ela        |
| mikä+Pron+Interr+All        | mikä+Pron+Interr+All        |
| mikä+Pron+Interr+Ade        | mikä+Pron+Interr+Ade        |
| mikä+Pron+Interr+Abl        | mikä+Pron+Interr+Abl        |
| mikä+Pron+Interr+Abe        | mikä+Pron+Interr+Abe        |
| joka+Pron+Rel+Sg+Nom        | joka                        |
| joka+Pron+Rel+Sg+Gen        | jonka                       |
| joka+Pron+Rel+Sg+Ill        | johon                       |
| joka+Pron+Rel+Sg+Ill        | johonka                     |
| joka+Pron+Rel+Sg+Par        | jota                        |
| joka+Pron+Rel+Sg+Ess        | jona                        |
| joka+Pron+Rel+Sg+Tra        | joksi                       |
| joka+Pron+Rel+Sg+Ine        | jossa                       |
| joka+Pron+Rel+Sg+Ela        | josta                       |
| joka+Pron+Rel+Sg+All        | jolle                       |
| joka+Pron+Rel+Sg+Ade        | jolla                       |
| joka+Pron+Rel+Sg+Abl        | jolta                       |
| joka+Pron+Rel+Sg+Abe        | joka+Pron+Rel+Sg+Abe        |
| joka+Pron+Rel+Pl+Nom        | jokka                       |
| joka+Pron+Rel+Pl+Gen        | joitten                     |
| joka+Pron+Rel+Pl+Ill        | joihin                      |
| joka+Pron+Rel+Pl+Par        | joita                       |
| joka+Pron+Rel+Pl+Ess        | joina                       |
| joka+Pron+Rel+Pl+Tra        | joiksi                      |
| joka+Pron+Rel+Pl+Ine        | joissa                      |
| joka+Pron+Rel+Pl+Ela        | joista                      |
| joka+Pron+Rel+Pl+All        | joile                       |
| joka+Pron+Rel+Pl+Ade        | joila                       |
| joka+Pron+Rel+Pl+Abl        | joilta                      |
| joka+Pron+Rel+Pl+Abe        | joka+Pron+Rel+Pl+Abe        |
| mikä+Pron+Rel+Sg+Nom        | mikä                        |
| mikä+Pron+Rel+Sg+Gen        | minkä                       |
| mikä+Pron+Rel+Sg+Ill        | mihin                       |
| mikä+Pron+Rel+Sg+Ill        | mihinkä                     |
| mikä+Pron+Rel+Sg+Par        | mitä                        |
| mikä+Pron+Rel+Sg+Ess        | minä                        |
| mikä+Pron+Rel+Sg+Tra        | miksi                       |
| mikä+Pron+Rel+Sg+Ine        | missä                       |
| mikä+Pron+Rel+Sg+Ela        | mistä                       |
| mikä+Pron+Rel+Sg+All        | mille                       |
| mikä+Pron+Rel+Sg+Ade        | millä                       |
| mikä+Pron+Rel+Sg+Abl        | miltä                       |
| mikä+Pron+Rel+Sg+Abe        | mikä+Pron+Rel+Sg+Abe        |
| mikä+Pron+Rel+Pl+Nom        | mitkä                       |
| mikä+Pron+Rel+Pl+Nom        | mikkä                       |
| mikä+Pron+Rel+Pl+Gen        | minkä                       |
| mikä+Pron+Rel+Pl+Ill        | mihin                       |
| mikä+Pron+Rel+Pl+Ill        | mihinkä                     |
| mikä+Pron+Rel+Pl+Par        | mitä                        |
| mikä+Pron+Rel+Pl+Ess        | minä                        |
| mikä+Pron+Rel+Pl+Tra        | miksi                       |
| mikä+Pron+Rel+Pl+Ine        | missä                       |
| mikä+Pron+Rel+Pl+Ela        | mistä                       |
| mikä+Pron+Rel+Pl+All        | mille                       |
| mikä+Pron+Rel+Pl+Ade        | millä                       |
| mikä+Pron+Rel+Pl+Abl        | miltä                       |
| mikä+Pron+Rel+Pl+Abe        | mikä+Pron+Rel+Pl+Abe        |
| itteni+Pron+Refl+Sg+Nom     | itteni+Pron+Refl+Sg+Nom     |
| itteni+Pron+Refl+Sg+Gen     | itteni                      |
| itteni+Pron+Refl+Sg+Ill     | ittheeni                    |
| itteni+Pron+Refl+Sg+Par     | ittiäni                     |
| itteni+Pron+Refl+Sg+Par     | itteeni                     |
| itteni+Pron+Refl+Sg+Par     | itteäni                     |
| itteni+Pron+Refl+Sg+Ess     | ittenäni                    |
| itteni+Pron+Refl+Sg+Tra     | ittekseni                   |
| itteni+Pron+Refl+Sg+Ine     | ittessäni                   |
| itteni+Pron+Refl+Sg+Ela     | ittestäni                   |
| itteni+Pron+Refl+Sg+All     | itteleni                    |
| itteni+Pron+Refl+Sg+Ade     | itteläni                    |
| itteni+Pron+Refl+Sg+Abl     | itteltäni                   |
| itteni+Pron+Refl+Sg+Abe     | itteni+Pron+Refl+Sg+Abe     |
| ittesti+Pron+Refl+Sg+Nom    | ittesti+Pron+Refl+Sg+Nom    |
| ittesti+Pron+Refl+Sg+Gen    | ittsti                      |
| ittesti+Pron+Refl+Sg+Ill    | ittheesti                   |
| ittesti+Pron+Refl+Sg+Par    | ittiästi                    |
| ittesti+Pron+Refl+Sg+Par    | itteesti                    |
| ittesti+Pron+Refl+Sg+Par    | itteästi                    |
| ittesti+Pron+Refl+Sg+Ess    | ittenästi                   |
| ittesti+Pron+Refl+Sg+Tra    | itteksesti                  |
| ittesti+Pron+Refl+Sg+Ine    | ittessästi                  |
| ittesti+Pron+Refl+Sg+Ela    | ittestästi                  |
| ittesti+Pron+Refl+Sg+All    | ittelesti                   |
| ittesti+Pron+Refl+Sg+Ade    | ittelästi                   |
| ittesti+Pron+Refl+Sg+Abl    | itteltästi                  |
| ittesti+Pron+Refl+Sg+Abe    | ittesti+Pron+Refl+Sg+Abe    |
| ittemä+Pron+Refl+Pl+Nom     | ittemä+Pron+Refl+Pl+Nom     |
| ittemä+Pron+Refl+Pl+Gen     | ittmä                       |
| ittemä+Pron+Refl+Pl+Ill     | ittheemä                    |
| ittemä+Pron+Refl+Pl+Par     | ittiämä                     |
| ittemä+Pron+Refl+Pl+Par     | itteemä                     |
| ittemä+Pron+Refl+Pl+Par     | itteämä                     |
| ittemä+Pron+Refl+Pl+Ess     | ittenämmä                   |
| ittemä+Pron+Refl+Pl+Tra     | itteksemmä                  |
| ittemä+Pron+Refl+Pl+Ine     | ittessämmä                  |
| ittemä+Pron+Refl+Pl+Ela     | ittestämmä                  |
| ittemä+Pron+Refl+Pl+All     | ittelemmä                   |
| ittemä+Pron+Refl+Pl+Ade     | ittelämmä                   |
| ittemä+Pron+Refl+Pl+Abl     | itteltämmä                  |
| ittemä+Pron+Refl+Pl+Abe     | ittemä+Pron+Refl+Pl+Abe     |
| ittenä+Pron+Refl+Pl+Nom     | ittenä+Pron+Refl+Pl+Nom     |
| ittenä+Pron+Refl+Pl+Gen     | ittnä                       |
| ittenä+Pron+Refl+Pl+Ill     | ittheenä                    |
| ittenä+Pron+Refl+Pl+Par     | ittiännä                    |
| ittenä+Pron+Refl+Pl+Par     | itteenä                     |
| ittenä+Pron+Refl+Pl+Par     | itteännä                    |
| ittenä+Pron+Refl+Pl+Ess     | ittenännä                   |
| ittenä+Pron+Refl+Pl+Tra     | itteksennä                  |
| ittenä+Pron+Refl+Pl+Ine     | ittessännä                  |
| ittenä+Pron+Refl+Pl+Ela     | ittestännä                  |
| ittenä+Pron+Refl+Pl+All     | ittelennä                   |
| ittenä+Pron+Refl+Pl+Ade     | ittelännä                   |
| ittenä+Pron+Refl+Pl+Abl     | ittetännä                   |
| ittenä+Pron+Refl+Pl+Abe     | ittenä+Pron+Refl+Pl+Abe     |
| ittensä+Pron+Refl+Pl+Nom    | ittensä+Pron+Refl+Pl+Nom    |
| ittensä+Pron+Refl+Pl+Gen    | ittnä                       |
| ittensä+Pron+Refl+Pl+Ill    | ittheensä                   |
| ittensä+Pron+Refl+Pl+Par    | ittiänsä                    |
| ittensä+Pron+Refl+Pl+Par    | itteensä                    |
| ittensä+Pron+Refl+Pl+Par    | itteänsä                    |
| ittensä+Pron+Refl+Pl+Ess    | ittenänsä                   |
| ittensä+Pron+Refl+Pl+Tra    | itteksensä                  |
| ittensä+Pron+Refl+Pl+Ine    | ittessänsä                  |
| ittensä+Pron+Refl+Pl+Ela    | ittestänsä                  |
| ittensä+Pron+Refl+Pl+All    | ittelensä                   |
| ittensä+Pron+Refl+Pl+Ade    | ittelänsä                   |
| ittensä+Pron+Refl+Pl+Abl    | ittltänsä                   |
| ittensä+Pron+Refl+Pl+Abe    | ittensä+Pron+Refl+Pl+Abe    |
| toinen+Pron+Recipr+Attr+Nom | toinen+Pron+Recipr+Attr+Nom |
| toinen+Pron+Recipr+Attr+Gen | toinen+Pron+Recipr+Attr+Gen |
| toinen+Pron+Recipr+Attr+Ill | toinen+Pron+Recipr+Attr+Ill |
| toinen+Pron+Recipr+Attr+Par | toinen+Pron+Recipr+Attr+Par |
| toinen+Pron+Recipr+Attr+Ess | toinen+Pron+Recipr+Attr+Ess |
| toinen+Pron+Recipr+Attr+Tra | toinen+Pron+Recipr+Attr+Tra |
| toinen+Pron+Recipr+Attr+Ine | toinen+Pron+Recipr+Attr+Ine |
| toinen+Pron+Recipr+Attr+Ela | toinen+Pron+Recipr+Attr+Ela |
| toinen+Pron+Recipr+Attr+All | toinen+Pron+Recipr+Attr+All |
| toinen+Pron+Recipr+Attr+Ade | toinen+Pron+Recipr+Attr+Ade |
| toinen+Pron+Recipr+Attr+Abl | toinen+Pron+Recipr+Attr+Abl |
| toinen+Pron+Recipr+Attr+Abe | toinen+Pron+Recipr+Attr+Abe |
| toinen+Pron+Recipr+Sg+Nom   | toinen                      |
| toinen+Pron+Recipr+Sg+Gen   | toisen                      |
| toinen+Pron+Recipr+Sg+Ill   | toisheen                    |
| toinen+Pron+Recipr+Sg+Par   | toista                      |
| toinen+Pron+Recipr+Sg+Ess   | toisena                     |
| toinen+Pron+Recipr+Sg+Tra   | toiseksi                    |
| toinen+Pron+Recipr+Sg+Ine   | toisessa                    |
| toinen+Pron+Recipr+Sg+Ela   | toisesta                    |
| toinen+Pron+Recipr+Sg+All   | toisele                     |
| toinen+Pron+Recipr+Sg+Ade   | toisela                     |
| toinen+Pron+Recipr+Sg+Abl   | toiselta                    |
| toinen+Pron+Recipr+Sg+Abe   | toinen+Pron+Recipr+Sg+Abe   |
| toinen+Pron+Recipr+Pl+Nom   | toiset                      |
| toinen+Pron+Recipr+Pl+Gen   | toisten                     |
| toinen+Pron+Recipr+Pl+Ill   | toishiin                    |
| toinen+Pron+Recipr+Pl+Par   | toisia                      |
| toinen+Pron+Recipr+Pl+Ess   | toisina                     |
| toinen+Pron+Recipr+Pl+Tra   | toisiksi                    |
| toinen+Pron+Recipr+Pl+Ine   | toisissa                    |
| toinen+Pron+Recipr+Pl+Ela   | toisista                    |
| toinen+Pron+Recipr+Pl+All   | toisile                     |
| toinen+Pron+Recipr+Pl+Ade   | toisila                     |
| toinen+Pron+Recipr+Pl+Abl   | toisilta                    |
| toinen+Pron+Recipr+Pl+Abe   | toinen+Pron+Recipr+Pl+Abe   |
| joku+Pron+Indef+Sg+Nom      | joku                        |
| joku+Pron+Indef+Sg+Gen      | jonku                       |
| joku+Pron+Indef+Sg+Ill      | johonki                     |
| joku+Pron+Indef+Sg+Par      | jotaki                      |
| joku+Pron+Indef+Sg+Ess      | jonaki                      |
| joku+Pron+Indef+Sg+Tra      | joksiki                     |
| joku+Pron+Indef+Sg+Ine      | jossaki                     |
| joku+Pron+Indef+Sg+Ela      | jostaki                     |
| joku+Pron+Indef+Sg+All      | jolleki                     |
| joku+Pron+Indef+Sg+Ade      | jollaki                     |
| joku+Pron+Indef+Sg+Abl      | jolleki                     |
| joku+Pron+Indef+Sg+Abe      | joku+Pron+Indef+Sg+Abe      |
| jokku+Pron+Indef+Pl+Nom     | jokku+Pron+Indef+Pl+Nom     |
| jokku+Pron+Indef+Pl+Gen     | joittenki                   |
| jokku+Pron+Indef+Pl+Ill     | joihinki                    |
| jokku+Pron+Indef+Pl+Par     | joitaki                     |
| jokku+Pron+Indef+Pl+Ess     | joinaki                     |
| jokku+Pron+Indef+Pl+Tra     | joiksiki                    |
| jokku+Pron+Indef+Pl+Ine     | joissaki                    |
| jokku+Pron+Indef+Pl+Ela     | joistaki                    |
| jokku+Pron+Indef+Pl+All     | joilleki                    |
| jokku+Pron+Indef+Pl+Ade     | joillaki                    |
| jokku+Pron+Indef+Pl+Abl     | joilleki                    |
| jokku+Pron+Indef+Pl+Abe     | jokku+Pron+Indef+Pl+Abe     |
| muutampi+Pron+Indef+Sg+Nom  | muutampi                    |
| muutampi+Pron+Indef+Sg+Gen  | muutaman                    |
| muutampi+Pron+Indef+Sg+Ill  | muutamphaan                 |
| muutampi+Pron+Indef+Sg+Par  | muutammaa                   |
| muutampi+Pron+Indef+Sg+Par  | muutamppaa                  |
| muutampi+Pron+Indef+Sg+Ess  | muutaminna                  |
| muutampi+Pron+Indef+Sg+Ess  | muutampanna                 |
| muutampi+Pron+Indef+Sg+Tra  | muutamaksi                  |
| muutampi+Pron+Indef+Sg+Ine  | muutamassa                  |
| muutampi+Pron+Indef+Sg+Ela  | muutamasta                  |
| muutampi+Pron+Indef+Sg+All  | muutamalle                  |
| muutampi+Pron+Indef+Sg+Ade  | muutamalla                  |
| muutampi+Pron+Indef+Sg+Abl  | muutamalta                  |
| muutampi+Pron+Indef+Sg+Abe  | muutampi+Pron+Indef+Sg+Abe  |
| muutamat+Pron+Indef+Pl+Nom  | muutamat+Pron+Indef+Pl+Nom  |
| muutamat+Pron+Indef+Pl+Gen  | muutamitten                 |
| muutamat+Pron+Indef+Pl+Ill  | muutamphiin                 |
| muutamat+Pron+Indef+Pl+Par  | muutamppiita                |
| muutamat+Pron+Indef+Pl+Par  | muutammia                   |
| muutamat+Pron+Indef+Pl+Ess  | muutaminna                  |
| muutamat+Pron+Indef+Pl+Ess  | muutampinna                 |
| muutamat+Pron+Indef+Pl+Tra  | muutamiksi                  |
| muutamat+Pron+Indef+Pl+Ine  | muutamissa                  |
| muutamat+Pron+Indef+Pl+Ela  | muutamista                  |
| muutamat+Pron+Indef+Pl+All  | muutamille                  |
| muutamat+Pron+Indef+Pl+Ade  | muutamilla                  |
| muutamat+Pron+Indef+Pl+Abl  | muutamilta                  |
| muutamat+Pron+Indef+Pl+Abe  | muutamat+Pron+Indef+Pl+Abe  |
| sama+Pron+Indef+Sg+Nom      | sama                        |
| sama+Pron+Indef+Sg+Gen      | saman                       |
| sama+Pron+Indef+Sg+Ill      | samhaan                     |
| sama+Pron+Indef+Sg+Par      | sammaa                      |
| sama+Pron+Indef+Sg+Ess      | samana                      |
| sama+Pron+Indef+Sg+Tra      | samaksi                     |
| sama+Pron+Indef+Sg+Ine      | samassa                     |
| sama+Pron+Indef+Sg+Ela      | samasta                     |
| sama+Pron+Indef+Sg+All      | samale                      |
| sama+Pron+Indef+Sg+Ade      | samala                      |
| sama+Pron+Indef+Sg+Abl      | samalta                     |
| sama+Pron+Indef+Sg+Abe      | samatta                     |
| sama+Pron+Indef+Pl+Nom      | samat                       |
| sama+Pron+Indef+Pl+Gen      | samain                      |
| sama+Pron+Indef+Pl+Ill      | samahoin                    |
| sama+Pron+Indef+Pl+Par      | samai                       |
| sama+Pron+Indef+Pl+Ess      | samaina                     |
| sama+Pron+Indef+Pl+Tra      | samaiksi                    |
| sama+Pron+Indef+Pl+Ine      | samaissa                    |
| sama+Pron+Indef+Pl+Ela      | samaista                    |
| sama+Pron+Indef+Pl+All      | samaile                     |
| sama+Pron+Indef+Pl+Ade      | samaila                     |
| sama+Pron+Indef+Pl+Abl      | samailta                    |
| sama+Pron+Indef+Pl+Abe      | samaitta                    |
| muu+Pron+Indef+Sg+Nom       | muu                         |
| muu+Pron+Indef+Sg+Gen       | muun                        |
| muu+Pron+Indef+Sg+Ill       | muuhun                      |
| muu+Pron+Indef+Sg+Par       | muuta                       |
| muu+Pron+Indef+Sg+Ess       | muuna                       |
| muu+Pron+Indef+Sg+Tra       | muuksi                      |
| muu+Pron+Indef+Sg+Ine       | muussa                      |
| muu+Pron+Indef+Sg+Ela       | muusta                      |
| muu+Pron+Indef+Sg+All       | muule                       |
| muu+Pron+Indef+Sg+Ade       | muula                       |
| muu+Pron+Indef+Sg+Abl       | muulta                      |
| muu+Pron+Indef+Sg+Abe       | muutta                      |
| muu+Pron+Indef+Pl+Nom       | muut                        |
| muu+Pron+Indef+Pl+Gen       | muitten                     |
| muu+Pron+Indef+Pl+Gen       | muinen                      |
| muu+Pron+Indef+Pl+Ill       | muihin                      |
| muu+Pron+Indef+Pl+Par       | muita                       |
| muu+Pron+Indef+Pl+Ess       | muina                       |
| muu+Pron+Indef+Pl+Tra       | muiksi                      |
| muu+Pron+Indef+Pl+Ine       | muissa                      |
| muu+Pron+Indef+Pl+Ela       | muista                      |
| muu+Pron+Indef+Pl+All       | muile                       |
| muu+Pron+Indef+Pl+Ade       | muila                       |
| muu+Pron+Indef+Pl+Abl       | muilta                      |
| muu+Pron+Indef+Pl+Abe       | muitta                      |
| yksi+Pron+Indef+Sg+Nom      | yksi+Pron+Indef+Sg+Nom      |
| yksi+Pron+Indef+Sg+Gen      | yksi+Pron+Indef+Sg+Gen      |
| yksi+Pron+Indef+Sg+Ill      | yksi+Pron+Indef+Sg+Ill      |
| yksi+Pron+Indef+Sg+Par      | yksi+Pron+Indef+Sg+Par      |
| yksi+Pron+Indef+Sg+Ess      | yksi+Pron+Indef+Sg+Ess      |
| yksi+Pron+Indef+Sg+Tra      | yksi+Pron+Indef+Sg+Tra      |
| yksi+Pron+Indef+Sg+Ine      | yksi+Pron+Indef+Sg+Ine      |
| yksi+Pron+Indef+Sg+Ela      | yksi+Pron+Indef+Sg+Ela      |
| yksi+Pron+Indef+Sg+All      | yksi+Pron+Indef+Sg+All      |
| yksi+Pron+Indef+Sg+Ade      | yksi+Pron+Indef+Sg+Ade      |
| yksi+Pron+Indef+Sg+Abl      | yksi+Pron+Indef+Sg+Abl      |
| yksi+Pron+Indef+Sg+Abe      | yksi+Pron+Indef+Sg+Abe      |
| yksi+Pron+Indef+Pl+Nom      | yksi+Pron+Indef+Pl+Nom      |
| yksi+Pron+Indef+Pl+Gen      | yksi+Pron+Indef+Pl+Gen      |
| yksi+Pron+Indef+Pl+Ill      | yksi+Pron+Indef+Pl+Ill      |
| yksi+Pron+Indef+Pl+Par      | yksi+Pron+Indef+Pl+Par      |
| yksi+Pron+Indef+Pl+Ess      | yksi+Pron+Indef+Pl+Ess      |
| yksi+Pron+Indef+Pl+Tra      | yksi+Pron+Indef+Pl+Tra      |
| yksi+Pron+Indef+Pl+Ine      | yksi+Pron+Indef+Pl+Ine      |
| yksi+Pron+Indef+Pl+Ela      | yksi+Pron+Indef+Pl+Ela      |
| yksi+Pron+Indef+Pl+All      | yksi+Pron+Indef+Pl+All      |
| yksi+Pron+Indef+Pl+Ade      | yksi+Pron+Indef+Pl+Ade      |
| yksi+Pron+Indef+Pl+Abl      | yksi+Pron+Indef+Pl+Abl      |
| yksi+Pron+Indef+Pl+Abe      | yksi+Pron+Indef+Pl+Abe      |
| kaikki+Pron+Qu+Sg+Nom       | kaikki                      |
| kaikki+Pron+Qu+Sg+Gen       | kaiken                      |
| kaikki+Pron+Qu+Sg+Ill       | kaikkheen                   |
| kaikki+Pron+Qu+Sg+Par       | kaikkee                     |
| kaikki+Pron+Qu+Sg+Ess       | kaikkena                    |
| kaikki+Pron+Qu+Sg+Tra       | kaikeksi                    |
| kaikki+Pron+Qu+Sg+Ine       | kaikessa                    |
| kaikki+Pron+Qu+Sg+Ela       | kaikesta                    |
| kaikki+Pron+Qu+Sg+All       | kaikele                     |
| kaikki+Pron+Qu+Sg+Ade       | kaikela                     |
| kaikki+Pron+Qu+Sg+Abl       | kaikelta                    |
| kaikki+Pron+Qu+Sg+Abe       | kaikki+Pron+Qu+Sg+Abe       |
| kaikki+Pron+Qu+Pl+Nom       | kaiket                      |
| kaikki+Pron+Qu+Pl+Gen       | kaikkiin                    |
| kaikki+Pron+Qu+Pl+Ill       | kaikkhiin                   |
| kaikki+Pron+Qu+Pl+Par       | kaikkii                     |
| kaikki+Pron+Qu+Pl+Ess       | kaikkina                    |
| kaikki+Pron+Qu+Pl+Tra       | kaikiksi                    |
| kaikki+Pron+Qu+Pl+Ine       | kaikissa                    |
| kaikki+Pron+Qu+Pl+Ela       | kaikista                    |
| kaikki+Pron+Qu+Pl+All       | kaikile                     |
| kaikki+Pron+Qu+Pl+Ade       | kaikila                     |
| kaikki+Pron+Qu+Pl+Abl       | kaikilta                    |
| kaikki+Pron+Qu+Pl+Abe       | kaikki+Pron+Qu+Pl+Abe       |
| jokhainen+Pron+Qu+Sg+Nom    | jokhainen+Pron+Qu+Sg+Nom    |
| jokhainen+Pron+Qu+Sg+Gen    | jokhainen+Pron+Qu+Sg+Gen    |
| jokhainen+Pron+Qu+Sg+Ill    | jokhainen+Pron+Qu+Sg+Ill    |
| jokhainen+Pron+Qu+Sg+Par    | jokhainen+Pron+Qu+Sg+Par    |
| jokhainen+Pron+Qu+Sg+Ess    | jokhainen+Pron+Qu+Sg+Ess    |
| jokhainen+Pron+Qu+Sg+Tra    | jokhainen+Pron+Qu+Sg+Tra    |
| jokhainen+Pron+Qu+Sg+Ine    | jokhainen+Pron+Qu+Sg+Ine    |
| jokhainen+Pron+Qu+Sg+Ela    | jokhainen+Pron+Qu+Sg+Ela    |
| jokhainen+Pron+Qu+Sg+All    | jokhainen+Pron+Qu+Sg+All    |
| jokhainen+Pron+Qu+Sg+Ade    | jokhainen+Pron+Qu+Sg+Ade    |
| jokhainen+Pron+Qu+Sg+Abl    | jokhainen+Pron+Qu+Sg+Abl    |
| jokhainen+Pron+Qu+Sg+Abe    | jokhainen+Pron+Qu+Sg+Abe    |
| jokhainen+Pron+Qu+Pl+Nom    | jokhainen+Pron+Qu+Pl+Nom    |
| jokhainen+Pron+Qu+Pl+Gen    | jokhainen+Pron+Qu+Pl+Gen    |
| jokhainen+Pron+Qu+Pl+Ill    | jokhainen+Pron+Qu+Pl+Ill    |
| jokhainen+Pron+Qu+Pl+Par    | jokhainen+Pron+Qu+Pl+Par    |
| jokhainen+Pron+Qu+Pl+Ess    | jokhainen+Pron+Qu+Pl+Ess    |
| jokhainen+Pron+Qu+Pl+Tra    | jokhainen+Pron+Qu+Pl+Tra    |
| jokhainen+Pron+Qu+Pl+Ine    | jokhainen+Pron+Qu+Pl+Ine    |
| jokhainen+Pron+Qu+Pl+Ela    | jokhainen+Pron+Qu+Pl+Ela    |
| jokhainen+Pron+Qu+Pl+All    | jokhainen+Pron+Qu+Pl+All    |
| jokhainen+Pron+Qu+Pl+Ade    | jokhainen+Pron+Qu+Pl+Ade    |
| jokhainen+Pron+Qu+Pl+Abl    | jokhainen+Pron+Qu+Pl+Abl    |
| jokhainen+Pron+Qu+Pl+Abe    | jokhainen+Pron+Qu+Pl+Abe    |
| itte+Pron+Qu+Nom            | itte                        |
| itte+Pron+Qu+Gen            | itten                       |
| itte+Pron+Qu+Ill            | ittheen                     |
| itte+Pron+Qu+Par            | ittiä                       |
| itte+Pron+Qu+Par            | ittee                       |
| itte+Pron+Qu+Par            | itteä                       |
| itte+Pron+Qu+Ess            | ittenä                      |
| itte+Pron+Qu+Tra            | itteksi                     |
| itte+Pron+Qu+Ine            | ittessä                     |
| itte+Pron+Qu+Ela            | ittestä                     |
| itte+Pron+Qu+All            | ittele                      |
| itte+Pron+Qu+Ade            | ittelä                      |
| itte+Pron+Qu+Abl            | itteltä                     |
| itte+Pron+Qu+Abe            | itte+Pron+Qu+Abe            |
| kekin+Pron+Qu+Nom           | kekin+Pron+Qu+Nom           |
| kekin+Pron+Qu+Gen           | kenenki                     |
| kekin+Pron+Qu+Ill           | kehenki                     |
| kekin+Pron+Qu+Par           | ketaki                      |
| kekin+Pron+Qu+Ess           | kenäki                      |
| kekin+Pron+Qu+Tra           | keksiki                     |
| kekin+Pron+Qu+Ine           | kessäki                     |
| kekin+Pron+Qu+Ela           | kestäki                     |
| kekin+Pron+Qu+All           | kelleki                     |
| kekin+Pron+Qu+Ade           | kelläki                     |
| kekin+Pron+Qu+Abl           | keltäki                     |
| kekin+Pron+Qu+Abe           | kekin+Pron+Qu+Abe           |
| kukanen+Pron+Qu+Nom         | kukanen+Pron+Qu+Nom         |
| kukanen+Pron+Qu+Gen         | kukanen+Pron+Qu+Gen         |
| kukanen+Pron+Qu+Ill         | kukanen+Pron+Qu+Ill         |
| kukanen+Pron+Qu+Par         | kukanen+Pron+Qu+Par         |
| kukanen+Pron+Qu+Ess         | kukanen+Pron+Qu+Ess         |
| kukanen+Pron+Qu+Tra         | kukanen+Pron+Qu+Tra         |
| kukanen+Pron+Qu+Ine         | kukanen+Pron+Qu+Ine         |
| kukanen+Pron+Qu+Ela         | kukanen+Pron+Qu+Ela         |
| kukanen+Pron+Qu+All         | kukanen+Pron+Qu+All         |
| kukanen+Pron+Qu+Ade         | kukanen+Pron+Qu+Ade         |
| kukanen+Pron+Qu+Abl         | kukanen+Pron+Qu+Abl         |
| kukanen+Pron+Qu+Abe         | kukanen+Pron+Qu+Abe         |
| kumpiki+Pron+Qu+Sg+Nom      | kumpiki                     |
| kumpiki+Pron+Qu+Sg+Gen      | kummanki                    |
| kumpiki+Pron+Qu+Sg+Ill      | kumphaanki                  |
| kumpiki+Pron+Qu+Sg+Par      | kumpaaki                    |
| kumpiki+Pron+Qu+Sg+Par      | kumppaaki                   |
| kumpiki+Pron+Qu+Sg+Ess      | kumpanaki                   |
| kumpiki+Pron+Qu+Sg+Tra      | kummaksiki                  |
| kumpiki+Pron+Qu+Sg+Ine      | kummassaki                  |
| kumpiki+Pron+Qu+Sg+Ela      | kummastaki                  |
| kumpiki+Pron+Qu+Sg+All      | kummalleki                  |
| kumpiki+Pron+Qu+Sg+Ade      | kummallaki                  |
| kumpiki+Pron+Qu+Sg+Abl      | kummaltaki                  |
| kumpiki+Pron+Qu+Sg+Abe      | kumpiki+Pron+Qu+Sg+Abe      |
| kummatki+Pron+Qu+Pl+Nom     | kummatki                    |
| kummatki+Pron+Qu+Pl+Gen     | kumppinki                   |
| kummatki+Pron+Qu+Pl+Gen     | kummittenki                 |
| kummatki+Pron+Qu+Pl+Ill     | kumphiinki                  |
| kummatki+Pron+Qu+Pl+Par     | kumpiaki                    |
| kummatki+Pron+Qu+Pl+Par     | kumppiiki                   |
| kummatki+Pron+Qu+Pl+Ess     | kumpinaki                   |
| kummatki+Pron+Qu+Pl+Tra     | kummiksiki                  |
| kummatki+Pron+Qu+Pl+Ine     | kummissaki                  |
| kummatki+Pron+Qu+Pl+Ela     | kummistaki                  |
| kummatki+Pron+Qu+Pl+All     | kummileki                   |
| kummatki+Pron+Qu+Pl+Ade     | kummilaki                   |
| kummatki+Pron+Qu+Pl+Abl     | kummiltaki                  |
| kummatki+Pron+Qu+Pl+Abe     | kummatki+Pron+Qu+Pl+Abe     |
| molemat+Pron+Qu+Nom         | molemat                     |
| molemat+Pron+Qu+Gen         | molemman                    |
| molemat+Pron+Qu+Ill         | molemphaan                  |
| molemat+Pron+Qu+Par         | molemppaa                   |
| molemat+Pron+Qu+Ess         | molempanna                  |
| molemat+Pron+Qu+Tra         | molemaksi                   |
| molemat+Pron+Qu+Ine         | molemassa                   |
| molemat+Pron+Qu+Ela         | molemasta                   |
| molemat+Pron+Qu+All         | molemale                    |
| molemat+Pron+Qu+Ade         | molemila                    |
| molemat+Pron+Qu+Abl         | molemalta                   |
| molemat+Pron+Qu+Abe         | molemat+Pron+Qu+Abe         |
| moni+Pron+Qu+Sg+Nom         | moni                        |
| moni+Pron+Qu+Sg+Gen         | monen                       |
| moni+Pron+Qu+Sg+Ill         | moni+Pron+Qu+Sg+Ill         |
| moni+Pron+Qu+Sg+Par         | monta                       |
| moni+Pron+Qu+Sg+Ess         | monena                      |
| moni+Pron+Qu+Sg+Tra         | moneksi                     |
| moni+Pron+Qu+Sg+Ine         | monessa                     |
| moni+Pron+Qu+Sg+Ela         | monesta                     |
| moni+Pron+Qu+Sg+All         | monele                      |
| moni+Pron+Qu+Sg+Ade         | monela                      |
| moni+Pron+Qu+Sg+Abl         | monelta                     |
| moni+Pron+Qu+Sg+Abe         | moni+Pron+Qu+Sg+Abe         |
| moni+Pron+Qu+Pl+Nom         | monet                       |
| moni+Pron+Qu+Pl+Gen         | mon3en                      |
| moni+Pron+Qu+Pl+Ill         | moni+Pron+Qu+Pl+Ill         |
| moni+Pron+Qu+Pl+Par         | moniq                       |
| moni+Pron+Qu+Pl+Ess         | monina                      |
| moni+Pron+Qu+Pl+Tra         | moniksi                     |
| moni+Pron+Qu+Pl+Ine         | monissa                     |
| moni+Pron+Qu+Pl+Ela         | monista                     |
| moni+Pron+Qu+Pl+All         | monile                      |
| moni+Pron+Qu+Pl+Ade         | monila                      |
| moni+Pron+Qu+Pl+Abl         | monilta                     |
| moni+Pron+Qu+Pl+Abe         | moni+Pron+Qu+Pl+Abe         |
| kukhaan+Pron+Qu+Nom         | kukhaan+Pron+Qu+Nom         |
| kukhaan+Pron+Qu+Gen         | kenenkhään                  |
| kukhaan+Pron+Qu+Ill         | kenheenkhään                |
| kukhaan+Pron+Qu+Par         | kethään                     |
| kukhaan+Pron+Qu+Ess         | kenenäkhään                 |
| kukhaan+Pron+Qu+Tra         | keneksikhään                |
| kukhaan+Pron+Qu+Ine         | kenessäkhään                |
| kukhaan+Pron+Qu+Ela         | kenestäkhään                |
| kukhaan+Pron+Qu+All         | kelheen                     |
| kukhaan+Pron+Qu+All         | kenelekhään                 |
| kukhaan+Pron+Qu+Ade         | kethään                     |
| kukhaan+Pron+Qu+Ade         | kekeläkhään                 |
| kukhaan+Pron+Qu+Abl         | kelthään                    |
| kukhaan+Pron+Qu+Abl         | keneltäkhään                |
| kukhaan+Pron+Qu+Abe         | kukhaan+Pron+Qu+Abe         |
| mikhään+Pron+Qu+Nom         | mi                          |
| mikhään+Pron+Qu+Gen         | minkhään                    |
| mikhään+Pron+Qu+Ill         | mihinkhään                  |
| mikhään+Pron+Qu+Par         | mithään                     |
| mikhään+Pron+Qu+Ess         | minhään                     |
| mikhään+Pron+Qu+Tra         | miksikhään                  |
| mikhään+Pron+Qu+Ine         | mishään                     |
| mikhään+Pron+Qu+Ela         | misthään                    |
| mikhään+Pron+Qu+All         | millekhään                  |
| mikhään+Pron+Qu+Ade         | milhään                     |
| mikhään+Pron+Qu+Abl         | milthään                    |
| mikhään+Pron+Qu+Abe         | mikhään+Pron+Qu+Abe         |
| yksikhään+Pron+Qu+Nom       | yht                         |
| yksikhään+Pron+Qu+Gen       | yksikhään+Pron+Qu+Gen       |
| yksikhään+Pron+Qu+Ill       | yhtheenkään                 |
| yksikhään+Pron+Qu+Par       | yhtäkhään                   |
| yksikhään+Pron+Qu+Ess       | yksikhään+Pron+Qu+Ess       |
| yksikhään+Pron+Qu+Tra       | yksikhään+Pron+Qu+Tra       |
| yksikhään+Pron+Qu+Ine       | yksikhään+Pron+Qu+Ine       |
| yksikhään+Pron+Qu+Ela       | yksikhään+Pron+Qu+Ela       |
| yksikhään+Pron+Qu+All       | yksikhään+Pron+Qu+All       |
| yksikhään+Pron+Qu+Ade       | yksikhään+Pron+Qu+Ade       |
| yksikhään+Pron+Qu+Abl       | yksikhään+Pron+Qu+Abl       |
| yksikhään+Pron+Qu+Abe       | yksikhään+Pron+Qu+Abe       |
| kumpikhaan+Pron+Qu+Nom      | kumpikhaan+Pron+Qu+Nom      |
| kumpikhaan+Pron+Qu+Gen      | kumpikhaan+Pron+Qu+Gen      |
| kumpikhaan+Pron+Qu+Ill      | kumphaankaan                |
| kumpikhaan+Pron+Qu+Par      | kumpikhaan+Pron+Qu+Par      |
| kumpikhaan+Pron+Qu+Ess      | kumpikhaan+Pron+Qu+Ess      |
| kumpikhaan+Pron+Qu+Tra      | kumpikhaan+Pron+Qu+Tra      |
| kumpikhaan+Pron+Qu+Ine      | kumpikhaan+Pron+Qu+Ine      |
| kumpikhaan+Pron+Qu+Ela      | kumpikhaan+Pron+Qu+Ela      |
| kumpikhaan+Pron+Qu+All      | kumpikhaan+Pron+Qu+All      |
| kumpikhaan+Pron+Qu+Ade      | kumpikhaan+Pron+Qu+Ade      |
| kumpikhaan+Pron+Qu+Abl      | kumpikhaan+Pron+Qu+Abl      |
| kumpikhaan+Pron+Qu+Abe      | kumpikhaan+Pron+Qu+Abe      |
| ussee+Pron+Qu+Sg+Nom        | ussie                       |
| ussee+Pron+Qu+Sg+Nom        | ussea                       |
| ussee+Pron+Qu+Sg+Nom        | ussee                       |
| ussee+Pron+Qu+Sg+Gen        | usian                       |
| ussee+Pron+Qu+Sg+Gen        | usean                       |
| ussee+Pron+Qu+Sg+Gen        | usheen                      |
| ussee+Pron+Qu+Sg+Ill        | usheesseen                  |
| ussee+Pron+Qu+Sg+Ill        | usihan                      |
| ussee+Pron+Qu+Sg+Ill        | usehan                      |
| ussee+Pron+Qu+Sg+Par        | usiaa                       |
| ussee+Pron+Qu+Sg+Par        | useaa                       |
| ussee+Pron+Qu+Sg+Par        | usheeta                     |
| ussee+Pron+Qu+Sg+Ess        | usiana                      |
| ussee+Pron+Qu+Sg+Ess        | useana                      |
| ussee+Pron+Qu+Sg+Ess        | usheena                     |
| ussee+Pron+Qu+Sg+Tra        | usiaksi                     |
| ussee+Pron+Qu+Sg+Tra        | useaksi                     |
| ussee+Pron+Qu+Sg+Tra        | usheeksi                    |
| ussee+Pron+Qu+Sg+Ine        | usheessa                    |
| ussee+Pron+Qu+Sg+Ela        | usiasta                     |
| ussee+Pron+Qu+Sg+Ela        | useasta                     |
| ussee+Pron+Qu+Sg+Ela        | usheesta                    |
| ussee+Pron+Qu+Sg+All        | usialle                     |
| ussee+Pron+Qu+Sg+All        | usealle                     |
| ussee+Pron+Qu+Sg+All        | usheele                     |
| ussee+Pron+Qu+Sg+Ade        | usialla                     |
| ussee+Pron+Qu+Sg+Ade        | usealla                     |
| ussee+Pron+Qu+Sg+Ade        | usheela                     |
| ussee+Pron+Qu+Sg+Abl        | usialta                     |
| ussee+Pron+Qu+Sg+Abl        | usealta                     |
| ussee+Pron+Qu+Sg+Abl        | usheelta                    |
| ussee+Pron+Qu+Sg+Abe        | ussee+Pron+Qu+Sg+Abe        |
| ussee+Pron+Qu+Pl+Nom        | useat                       |
| ussee+Pron+Qu+Pl+Nom        | usiat                       |
| ussee+Pron+Qu+Pl+Nom        | usheeet                     |
| ussee+Pron+Qu+Pl+Gen        | usheitten                   |
| ussee+Pron+Qu+Pl+Ill        | usheissiin                  |
| ussee+Pron+Qu+Pl+Par        | usheita                     |
| ussee+Pron+Qu+Pl+Ess        | usheina                     |
| ussee+Pron+Qu+Pl+Tra        | usheiksi                    |
| ussee+Pron+Qu+Pl+Ine        | usheissa                    |
| ussee+Pron+Qu+Pl+Ela        | usheista                    |
| ussee+Pron+Qu+Pl+All        | usheile                     |
| ussee+Pron+Qu+Pl+Ade        | usheila                     |
| ussee+Pron+Qu+Pl+Abl        | usheilta                    |
| ussee+Pron+Qu+Pl+Abe        | ussee+Pron+Qu+Pl+Abe        |
| paljo+Pron+Qu+Pl+Nom        | paljo+Pron+Qu+Pl+Nom        |
| paljo+Pron+Qu+Pl+Gen        | paljo+Pron+Qu+Pl+Gen        |
| paljo+Pron+Qu+Pl+Ill        | paljo+Pron+Qu+Pl+Ill        |
| paljo+Pron+Qu+Pl+Par        | paljo+Pron+Qu+Pl+Par        |
| paljo+Pron+Qu+Pl+Ess        | paljo+Pron+Qu+Pl+Ess        |
| paljo+Pron+Qu+Pl+Tra        | paljo+Pron+Qu+Pl+Tra        |
| paljo+Pron+Qu+Pl+Ine        | paljo+Pron+Qu+Pl+Ine        |
| paljo+Pron+Qu+Pl+Ela        | paljosta                    |
| paljo+Pron+Qu+Pl+All        | paljoile                    |
| paljo+Pron+Qu+Pl+Ade        | paljo+Pron+Qu+Pl+Ade        |
| paljo+Pron+Qu+Pl+Abl        | paljo+Pron+Qu+Pl+Abl        |
| paljo+Pron+Qu+Pl+Abe        | paljo+Pron+Qu+Pl+Abe        |
| harva+Pron+Qu+Sg+Nom        | harva                       |
| harva+Pron+Qu+Sg+Gen        | harvan                      |
| harva+Pron+Qu+Sg+Ill        | harvaan                     |
| harva+Pron+Qu+Sg+Par        | harvasta                    |
| harva+Pron+Qu+Sg+Ess        | harvana                     |
| harva+Pron+Qu+Sg+Tra        | harvaksi                    |
| harva+Pron+Qu+Sg+Ine        | harvassa                    |
| harva+Pron+Qu+Sg+Ela        | harvasta                    |
| harva+Pron+Qu+Sg+All        | harvale                     |
| harva+Pron+Qu+Sg+Ade        | harvala                     |
| harva+Pron+Qu+Sg+Abl        | harvalta                    |
| harva+Pron+Qu+Sg+Abe        | harva+Pron+Qu+Sg+Abe        |
| harva+Pron+Qu+Pl+Nom        | harvat                      |
| harva+Pron+Qu+Pl+Gen        | harvoin                     |
| harva+Pron+Qu+Pl+Ill        | harvoihin                   |
| harva+Pron+Qu+Pl+Par        | harvoista                   |
| harva+Pron+Qu+Pl+Ess        | harvaina                    |
| harva+Pron+Qu+Pl+Tra        | harvaiksi                   |
| harva+Pron+Qu+Pl+Ine        | harvoissa                   |
| harva+Pron+Qu+Pl+Ela        | harvoista                   |
| harva+Pron+Qu+Pl+All        | harvoile                    |
| harva+Pron+Qu+Pl+Ade        | harvoila                    |
| harva+Pron+Qu+Pl+Abl        | harvoilta                   |
| harva+Pron+Qu+Pl+Abe        | harva+Pron+Qu+Pl+Abe        |
