template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "kven1236"
__REPO__ = "lang-fkv"
__UND2C__ = "fkv"
__UNDEFINED__ = "Kven Finnish"
__UND__ = "fkv"
