template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "kven1236"
__REPO__ = "lang-fkv"
__UND2C__ = "fkv"
__UNDEFINED__ = "Kven Finnish"
__UND__ = "fkv"
