template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "kven1236"
__REPO__ = "lang-fkv"
__UND2C__ = "fkv"
__UNDEFINED__ = "Kven Finnish"
__UND__ = "fkv"
