[package]
name = "fkv"
human_name = "Kven Finnish"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.fkv]
filename = "fkv-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-fkv"
platform = "windows"
uuid = "8F1DDBFF-F876-4E04-908F-03F26E9A2F9D"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.fkv"
package = "speller-fkv"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-fkv-mso"
platform = "windows"
uuid = "DDCCAFC4-0981-482E-8DD9-AFC5A75CCC7F"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-fkv"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
